(function(C){
 'use strict';
 // Reusable language data. Functions receive the current scientific atom.
 C.explanations={
  models:{
   bohr:{elementary:'The Bohr model shows electrons in rings around the nucleus. Each ring represents a different energy level.',middle:'The Bohr model places electrons in specific energy levels around the nucleus. It helps us understand electron shells and outer electrons.',high:'The Bohr model shows separate energy levels, called shells. The circles help us picture the shells, but real electrons do not follow fixed tracks.'},
   wave:{elementary:'Electrons can behave like both particles and waves. This model shows waves that fit around the atom.',middle:'De Broglie proposed that moving particles such as electrons also have wave properties. Only certain standing-wave patterns fit, helping explain specific energy levels.',high:'Electrons have a matter wavelength, a length associated with their wave behavior. Here, a whole number of waves fits around each closed path. This standing-wave picture connects Bohr’s shells to quantum models.'},
   quantum:{elementary:'We cannot follow an electron on one exact path. The cloud shows places where it might be found.',middle:'The Schrödinger model describes electrons using regions called orbitals. Denser parts of a cloud show where an electron is more likely to be detected.',high:'The Schrödinger model uses wavefunctions: mathematical descriptions of electron states. An orbital shows how likely an electron is to be detected in different places. Each orbital has a characteristic energy and shape.'}
  },
  concepts:{
   proton:{elementary:a=>'Protons are positive particles in the atom’s center. Every '+a.element.name.toLowerCase()+' atom has '+a.protons+(a.protons===1?' proton.':' protons.'),middle:a=>'Protons are found in the nucleus, the atom’s center. Their positive charge attracts electrons. Every '+a.element.name.toLowerCase()+' atom has '+a.protons+(a.protons===1?' proton.':' protons.'),high:a=>'Protons are found in the nucleus. The number of protons determines which element an atom is. Every '+a.element.name.toLowerCase()+' atom has '+a.protons+(a.protons===1?' proton.':' protons.')},
   neutron:{elementary:'Neutrons are in the atom’s center. They have no electric charge.',middle:'Neutrons are found in the nucleus and have no electric charge. Atoms of the same element can have different neutron counts. These versions are called isotopes.',high:'Neutrons are found in the nucleus and have no electric charge. Atoms of the same element can have different numbers of neutrons. These different versions are called isotopes.'},
   'inner-electron':{elementary:'Inner electrons are close to the atom’s center. The atom holds them tightly.',middle:'Inner electrons occupy the atom’s inner energy levels. They are held more tightly than outer electrons and do not move through a material as easily.',high:a=>'This electron occupies one of '+a.element.name.toLowerCase()+'’s inner energy levels. Inner electrons are held more tightly by the atom. They usually do not move through the material as easily as outer electrons.'},
   'valence-electron':{elementary:'This is an outer electron. In solid copper, outer electrons help carry electricity.',middle:'Copper has one electron in its outer shell in this model. In solid copper, outer electrons can move through the material and carry electrical current.',high:'This is copper’s outermost electron in the simplified shell model. In solid copper, outer electrons can move through the material and carry electrical current.'},
   nucleus:{elementary:'The nucleus is the tiny center of an atom. It holds protons and neutrons.',middle:'The nucleus is the small center of the atom. It contains protons and, in most isotopes, neutrons. Nearly all the atom’s mass is here.',high:'The nucleus contains protons and neutrons. It holds nearly all the mass of the atom. Its size is greatly enlarged in this model so you can inspect it.'},
   shell:{elementary:'A shell is an electron energy level. The rings help us picture these levels.',middle:'An electron shell groups states with the same main energy-level number. The rings show these groups, not real tracks.',high:'A shell groups electron states with the same principal quantum number, the main energy-level label. Copper’s simplified shell counts are 2, 8, 18, and 1. Shells are not solid surfaces or tracks.'},
   wave:{elementary:'Electrons can act like waves as well as particles. The wave fits all the way around this model.',middle:'A matter wave describes the wave-like behavior of a particle. Here, waves fit around a closed path to form a standing pattern. The electron is not a ball riding on the wave.',high:'Electrons show both particle-like and wave-like behavior. This model pictures allowed states as standing waves that fit around a closed path. The pattern is a teaching picture, not a moving electron’s path.'},
   orbital:{elementary:'An orbital shows where an electron might be found. The cloud is a picture, not a mist.',middle:'An orbital is a region used to show where an electron is likely to be detected. Denser cloud regions mean a greater chance of detection. The cloud is not a physical mist.',high:'An orbital describes where an electron is more or less likely to be detected. It does not give the electron a known path. The cloud is a picture of likelihood, not a physical mist.'},
   isotope:{elementary:'Isotopes are versions of the same element. They have different numbers of neutrons.',middle:'Isotopes have the same proton count but different neutron counts. Copper-63 has 29 protons and 34 neutrons.',high:a=>'Isotopes are atoms of the same element with different numbers of neutrons. '+a.element.name+'-'+a.massNumber+' has '+a.protons+' protons and '+a.neutrons+' neutrons. The mass number counts protons and neutrons together.'}
  },
  compare:{elementary:'These are three pictures of the same copper-63 atom. Bohr shows shells, de Broglie shows waves, and Schrödinger shows where electrons might be found. Changing the picture does not change the atom.',middle:'All three views represent the same copper-63 atom. Bohr helps explain shells and outer electrons. De Broglie introduces matter waves; Schrödinger shows orbitals and the chance of finding electrons. Models are tools for explaining different ideas.',high:'The element and isotope stay the same in all three views. Bohr emphasizes shells and valence electrons; de Broglie connects energy levels to matter waves. Schrödinger uses orbitals to describe detection probabilities—the chances of finding an electron. Scientific models are tools with different levels of detail.'}
 };
 C.explanations.regions={
  waveInner:{elementary:'This inner electron state is shown as a wave. Electrons can act like waves and particles.',middle:'This wave represents an inner electron state. Electrons have both wave-like and particle-like behavior. An allowed standing wave fits around the atom.',high:'This pattern represents an inner electron state, not a moving ball. Electrons show both particle-like and wave-like behavior. Allowed states are pictured as standing waves that close on themselves.'},
  waveValence:{elementary:'This outer wave represents copper’s outer electron. Electrons can act like waves and particles.',middle:'This outer pattern represents copper’s valence electron. Its wave fits around the atom as a standing pattern. In solid copper, outer electrons can carry current.',high:'This outer wave represents copper’s valence electron. Electrons show both particle-like and wave-like behavior. The closed standing wave is a picture of an allowed state. In solid copper, outer electrons can carry current.'},
  orbitalInner:{elementary:'This cloud shows where an inner electron might be found. It is a picture, not a mist.',middle:'This orbital represents an occupied inner electron state. The cloud shows where an electron is more likely to be detected. It does not show a path.',high:'This occupied inner orbital shows where an electron is more or less likely to be detected. The cloud is a picture of likelihood, not a physical mist. It gives no known path through the atom.'},
  orbitalValence:{elementary:'This cloud shows where copper’s outer electron might be found. It is a picture, not a mist.',middle:'This 4s cloud represents copper’s outer electron state. It shows the chance of finding an electron, not a path. In solid copper, outer electrons can carry current.',high:'The occupied 4s orbital represents copper’s outer electron state. The cloud shows where an electron is more or less likely to be detected. It is a picture, not a physical mist or a known path. In solid copper, outer electrons can carry current.'}
 };
 Object.assign(C.explanations.concepts,{
  element:{elementary:'An element is a kind of matter, such as copper. Its atoms share the same number of protons.',middle:'An element is identified by its proton count. All copper atoms have 29 protons.',high:'The number of protons defines the element. Changing neutrons makes a different isotope, while changing electrons makes an ion.'},
  atomicNumber:{elementary:'The atomic number counts protons. Copper’s atomic number is 29.',middle:'Atomic number is the number of protons. It identifies the element.',high:'Atomic number equals the proton count. It stays the same across an element’s isotopes and ions.'},
  massNumber:{elementary:'Mass number counts protons and neutrons together. Copper-63 has 63 of them.',middle:'Mass number is the total number of protons and neutrons. Copper-63 has 29 + 34 = 63.',high:'Mass number counts protons and neutrons in one isotope. It is not the weighted average atomic mass printed on a periodic table.'},
  ion:{elementary:'An ion is an atom that has gained or lost electrons. It has an electric charge.',middle:'An ion gains or loses electrons. Losing electrons gives a positive charge; gaining them gives a negative charge.',high:'An ion is an atom with a net charge from gaining or losing electrons. Changing isotope does not change its charge.'}
 });
 // Copper-specific teaching language belongs to its element record.
 const education={concepts:{'valence-electron':C.explanations.concepts['valence-electron']},regions:{waveValence:C.explanations.regions.waveValence,orbitalValence:C.explanations.regions.orbitalValence}};
 C.elements=C.deepFreeze({...C.elements,29:{...C.elements[29],education}});
 for(const level of ['elementary','middle','high']){
  C.explanations.concepts.shell[level]=a=>'Shells group electron energy levels. This atom has shell populations '+a.shells.join(', ')+'. Rings are not solid surfaces or literal tracks.';
  C.explanations.concepts.nucleus[level]='The nucleus is the small center of the atom. It contains protons and, in most isotopes, neutrons. The picture enlarges it for exploration.';
  C.explanations.concepts.element[level]=a=>a.element.name+' is identified by its '+a.protons+' protons. Isotopes of the element share this proton count.';
  C.explanations.concepts.atomicNumber[level]=a=>'Atomic number counts protons. This element has '+a.protons+'.';
  C.explanations.compare[level]='All three views show the same selected atom. Bohr shows shells, de Broglie shows standing waves, and Schrödinger shows where electrons might be found.';
 }
 C.explanations.concepts['valence-electron']={elementary:'This is an outer electron. Outer electrons help atoms interact.',middle:'This represents an outer electron. The number and arrangement of electrons affect how atoms interact.',high:'This is an outermost electron in the shell model. Other occupied subshells can also matter in bonding, especially in transition metals.'};
 C.explanations.regions.waveValence={elementary:'This wave stands for an outer electron level.',middle:'This standing-wave band represents an outer occupied level, not an electron riding a wave.',high:'This band represents an outer occupied level. It is a conceptual standing pattern, not an exact many-electron wavefunction.'};
 C.explanations.regions.orbitalValence={elementary:'This cloud shows where an outer electron might be.',middle:'This occupied outer region shows chances of finding an electron, not a path.',high:'This occupied outer subshell is shown as a probability region: places where an electron may be detected. It is not physical mist.'};
 C.explain=(group,key,level,atom)=>{const entry=atom.element.education?.[group]?.[key]||(key?C.explanations[group]?.[key]:C.explanations[group]);const text=entry?.[level]||entry?.high||'This is a simplified teaching representation.';return typeof text==='function'?text(atom):text;};
 C.modelNames={bohr:'Bohr Model',wave:'de Broglie Model',quantum:'Schrödinger Model'};
})(window.Copper);
