/* Phase 6J: curated neutral 5d ground states, consumed by the shared engine. */
(function(C){
 'use strict';
 const L=(elementary,middle,high)=>({elementary,middle,high}),elements={},isotopes={},sources={};
 const source=(key,organization,title,url,supports)=>sources[key]={organization,title,url,supports,accessed:'2026-09-12'};
 source('d5Abundance','CIAAW / IUPAC','Isotopic compositions 2024','https://www.ciaaw.org/isotopic-abundances.htm','Terrestrial isotope fractions and uncertainties for Hf–Au. Ta-180 abundance refers to its long-lived isomer. Rounded Hf percentages sum to 100.011%, within the quoted uncertainties; retain the source values.');
 source('d5Decay','NNDC / Brookhaven','Nuclear Wallet Cards, April 2005','https://www.lnl.infn.it/wp-content/uploads/Nuclear_Wallet_Cards.pdf','Named snapshot: Re-187 4.12e10 years beta-minus; Re-188 17.003 hours beta-minus; Os-186 2.0e15 years alpha; Ir-192 73.827 days beta-minus and electron capture; Au-198 2.6956 days beta-minus. Hf-174, W-180 and Pt-190 use separately cited measurements; search limits are not lifetimes.');
 source('d5Hf174','Caracciolo et al. / INFN collaboration','Search for alpha decay of naturally occurring Hf nuclides','https://arxiv.org/abs/2005.01373','Named 2020 observed Hf-174 alpha-decay result: (7.0 ± 1.2)e16 years, replacing the older 2e15-year value in the cited snapshot.');
 source('d5W180','CRESST collaboration','Detection of the natural decay of tungsten','https://journals.aps.org/prc/abstract/10.1103/PhysRevC.70.064606','2004 observed W-180 alpha decay: (1.8 ± 0.2)e18 years; other tungsten decay searches give limits.');
 source('d5Pt190','Braun et al.','A new precision measurement of the alpha-decay half-life of Pt-190','https://arxiv.org/abs/1703.00764','2017 measurement: (4.97 ± 0.16)e11 years, alpha decay to Os-186.');
 source('d5Ta180m','Majorana collaboration','Constraints on the decay of Ta-180m','https://arxiv.org/abs/2306.01965','2023 search with no observed decay; limits are not measured half-lives. Ta-180m is a long-lived excited nuclear state, not the short-lived ground state.');
 source('d5OsLimits','Belli et al. / INFN collaboration','Final results of the measurement to search for rare decays of naturally occurring osmium isotopes','https://arxiv.org/abs/2406.19062','2024 searches for rare Os decay give lower limits, including Os-184 and Os-192 channels; no limit is assigned as an observed lifetime.');
 source('d5Radiography','IAEA','Categorization of radioactive sources, TECDOC-1344','https://pub.iaea.org/MTCD/Publications/PDF/te_1344_web.pdf','Ir-192 industrial radiography and brachytherapy; historical/specialized Au-198 brachytherapy sources.');
 source('d5Re188','IAEA','Therapeutic Radionuclide Generators, TRS 470','https://www-pub.iaea.org/MTCD/Publications/PDF/trs470_web.pdf','W-188/Re-188 generators and specialized therapy research/application; not a universal treatment approval.');
 source('d5PlatinumMedicine','US National Cancer Institute','Cisplatin','https://www.cancer.gov/about-cancer/treatment/drugs/cisplatin','Cisplatin is a platinum-containing cancer medicine, not elemental platinum.');
 source('d5GoldColor','Royal Society of Chemistry','Is relativity creating cracks in the periodic table?','https://edu.rsc.org/feature/is-relativity-creating-cracks-in-the-periodic-table/2000091.article','Relativistic shifts in electronic energies contribute to gold absorbing blue light and appearing yellow.');
 source('d5Conductivity','NIST / National Bureau of Standards','Electrical properties of materials and their measurement at low temperatures, TN 1053','https://nvlpubs.nist.gov/nistpubs/Legacy/TN/nbstechnicalnote1053.pdf','Comparative electrical resistivity data: pure silver and copper conduct better than gold. Conductivity depends on material state and temperature.');
 const rows=[
  {z:72,name:'Hafnium',symbol:'Hf',d:2,s:2,mass:180,natural:[[174,.161,.002],[176,5.24,.14],[177,18.58,.09],[178,27.28,.06],[179,13.63,.03],[180,35.12,.16]],extra:[],
   descriptions:L('Hafnium (Hf) is a silvery metal. It helps make parts that work in very hot equipment.','Hafnium is transition metal 72, with 72 electrons in six shells. It is chemically similar to zirconium and is used in heat-resistant alloys and reactor controls.','Hafnium uses [Xe] 4f¹⁴ 5d² 6s². It begins this post-lanthanide sequence with two 5d electrons and a full 4f group. Both 5d and outer 6s electrons matter for bonding. Hafnium materials support high-temperature alloys and neutron-absorbing reactor controls. This atom is a simplified representation.'),
   engineering:L('Hafnium helps hot metal parts last. It also helps control nuclear reactors by capturing neutrons.','Some hafnium isotopes strongly absorb neutrons, making hafnium useful in reactor control rods. Hafnium oxide also insulates parts of microchips.','Hafnium-containing alloys serve high-temperature equipment, while neutron absorption supports reactor control rods. Hafnium oxide is an electrical insulator used in microchips. These are properties of materials and compounds, not a single isolated atom.')},
  {z:73,name:'Tantalum',symbol:'Ta',d:3,s:2,mass:181,natural:[['180m',.01176,.00023],[181,99.98824,.00023]],extra:[],
   descriptions:L('Tantalum (Ta) is a metal that resists corrosion. It helps some small electronic parts store electric charge.','Tantalum is transition metal 73, with 73 electrons in six shells. It resists corrosion and is used in some capacitors, components that store electric charge.','Tantalum uses [Xe] 4f¹⁴ 5d³ 6s². Its 5d group contains three electrons; both 5d and 6s affect bonding. A protective oxide layer helps tantalum resist corrosion and supports some capacitor designs. Natural Ta-180m is an unusual long-lived excited nucleus. The displayed atom is simplified.'),
   engineering:L('Some capacitors use tantalum to store charge in a small space. Tantalum is also used in certain medical implants.','A thin tantalum oxide layer acts as an electrical insulator in some capacitors. Its corrosion resistance also helps in specialized components and medical implants.','Tantalum oxide is the insulating layer in some compact capacitor technologies; not every capacitor uses tantalum. Corrosion resistance supports specialized electrodes and chemical equipment. Suitable tantalum implants are also valued for compatibility with body tissues.')},
  {z:74,name:'Tungsten',symbol:'W',d:4,s:2,mass:184,natural:[[180,.12,.01],[182,26.50,.16],[183,14.31,.04],[184,30.64,.02],[186,28.43,.19]],extra:[],
   descriptions:L('Tungsten (W) is a dense metal that withstands great heat. It has been used in glowing light-bulb wires.','Tungsten is transition metal 74, with 74 electrons in six shells. It has the highest melting point of the metals and is used in hot electrical parts and hard tools.','Tungsten uses [Xe] 4f¹⁴ 5d⁴ 6s². Four 5d electrons join the outer 6s pair in influencing bonding. Bulk tungsten withstands very high temperatures, and tungsten carbide makes hard cutting tools. Electrical uses include heating elements, contacts and filaments. This model simplifies the atom rather than reproducing the bulk material.'),
   engineering:L('Tungsten wires can glow while very hot. Tungsten-containing materials also make strong cutting tools.','Tungsten and its alloys are used in heating elements, electrical contacts and welding electrodes. Tungsten carbide is a hard compound used in cutting tools.','Tungsten supports high-temperature electrical contacts, heating elements and specialized electrodes. Incandescent filaments are a familiar historical example. Hard tungsten carbide tools are a compound application; these useful bulk properties do not belong to a lone tungsten atom.')},
  {z:75,name:'Rhenium',symbol:'Re',d:5,s:2,mass:187,natural:[[185,37.40,.05],[187,62.60,.05]],extra:[188],
   descriptions:L('Rhenium (Re) is a rare metal that withstands great heat. It helps some jet-engine parts last.','Rhenium is transition metal 75, with 75 electrons in six shells. It improves some high-temperature alloys, and natural Re-187 is radioactive but changes very slowly.','Rhenium uses [Xe] 4f¹⁴ 5d⁵ 6s². Its 5d group has five electrons, and both 5d and 6s affect bonding. Rhenium helps high-temperature superalloys and specialized reaction catalysts. Re-187 is naturally radioactive despite its extremely long lifetime. The atom shown is simplified.'),
   engineering:L('Rhenium helps some metal mixtures work in hot engines. Some rhenium materials also help chemical reactions.','Rhenium is added to some turbine-blade superalloys, metal mixtures made for harsh conditions. Rhenium catalysts help chemical reactions proceed.','Rhenium additions support some nickel-based turbine-blade superalloys and high-temperature tungsten alloys. Specialized rhenium catalysts help industrial chemical reactions. Rhenium can also serve wear-resistant electrical contacts; usefulness depends on the material and design.')},
  {z:76,name:'Osmium',symbol:'Os',d:6,s:2,mass:192,natural:[[184,.02,.02],[186,1.59,.64],[187,1.96,.17],[188,13.24,.27],[189,16.15,.23],[190,26.26,.20],[192,40.78,.32]],extra:[],
   descriptions:L('Osmium (Os) is a very dense metal. Its hard metal mixtures have specialized uses.','Osmium is transition metal 76, with 76 electrons in six shells. It is very dense, hard and brittle, and has specialized alloy and scientific uses.','Osmium uses [Xe] 4f¹⁴ 5d⁶ 6s². Six 5d electrons and the outer 6s pair influence bonding. Dense, hard osmium-containing alloys have specialized uses. Osmium tetroxide is a highly hazardous compound with different properties from the metal. This display simplifies the atom.'),
   engineering:L('Osmium helps make some very hard metal parts. Its compounds are not classroom handling materials.','Osmium alloys have been used in specialized electrical contacts and instrument parts. Osmium tetroxide is a highly hazardous compound, distinct from metallic osmium.','Hard osmium alloys have specialized contact and instrument uses, and osmium compounds support some chemical reactions and scientific work. The volatile compound osmium tetroxide can seriously harm eyes and lungs. Metallic osmium and this compound have different properties; neither is offered as a student handling activity.')},
  {z:77,name:'Iridium',symbol:'Ir',d:7,s:2,mass:193,natural:[[191,37.23,.09],[193,62.77,.09]],extra:[192],
   descriptions:L('Iridium (Ir) is a hard metal that resists corrosion. It helps some spark plugs last longer.','Iridium is transition metal 77, with 77 electrons in six shells. It resists corrosion and heat, making it useful in durable electrodes and spark plugs.','Iridium uses [Xe] 4f¹⁴ 5d⁷ 6s². Its 5d group contains seven electrons, and both 5d and 6s influence bonding. Corrosion resistance supports durable electrodes and high-temperature parts. Radioactive Ir-192 has separate, professionally controlled radiation-source uses. This model is simplified.'),
   engineering:L('Some spark-plug tips contain iridium. The metal resists heat and corrosion.','Iridium-containing electrodes can last in hot, demanding equipment. Ir-192 is radioactive and is used by specialists to inspect materials and treat some cancers.','Iridium supports durable spark-plug electrodes, electrical contacts and specialized high-temperature components. Separately, Ir-192 sources support industrial radiography and brachytherapy, treatment with a radiation source placed near a tumor. These radioactive sources require professional controls.')},
  {z:78,name:'Platinum',symbol:'Pt',d:9,s:1,mass:195,natural:[[190,.012,.002],[192,.782,.024],[194,32.864,.410],[195,33.775,.240],[196,25.211,.340],[198,7.356,.130]],extra:[],
   descriptions:L('Platinum (Pt) is a silvery metal used in jewelry. It also helps clean vehicle exhaust gases.','Platinum is transition metal 78, with 78 electrons in six shells. Its outermost shell has one electron, and platinum helps reactions in catalytic converters.','Platinum uses the measured [Xe] 4f¹⁴ 5d⁹ 6s¹ ground state. Nine electrons occupy 5d and one occupies 6s, rather than the simple filling prediction. Both groups influence bonding and platinum’s ability to help chemical reactions. Platinum materials serve converters and sensors, while particular platinum compounds are medicines. This atom is a simplified picture.'),
   engineering:L('Platinum helps reactions that clean exhaust gases. Certain platinum compounds are used in cancer medicines.','Platinum is used in sensors, electrodes and catalytic converters, devices that help change exhaust gases. Cancer medicines such as cisplatin are specific compounds, not pieces of platinum metal.','Platinum supports temperature sensors, electrodes, laboratory equipment and reaction catalysts, including catalytic converters. Its corrosion resistance also supports jewelry. Cisplatin and related cancer medicines are specific platinum compounds, not elemental platinum. These uses depend on material form and device design.')},
  {z:79,name:'Gold',symbol:'Au',d:10,s:1,mass:197,natural:[[197,100,0]],extra:[198],
   descriptions:L('Gold (Au) is a yellow metal used in jewelry. Thin gold coatings help electrical connections resist corrosion.','Gold is transition metal 79, with 79 electrons in six shells and one in the outside shell. Copper and silver conduct electricity better, but gold is useful on contacts because it conducts well and resists corrosion.','Gold uses [Xe] 4f¹⁴ 5d¹⁰ 6s¹. Its 5d group is full and one electron occupies 6s; both groups influence its properties. This is the experimentally supported lowest-energy arrangement, not a choice made by the electrons. Gold coatings protect electrical contacts from corrosion, although silver and copper conduct better. The displayed atom is simplified.'),
   engineering:L('Gold coatings help electrical connectors resist corrosion. Gold is also used in jewelry and has a long history in coins.','Gold conducts well and resists oxidation and corrosion. Silver and copper conduct better, so corrosion resistance is a main reason to plate electrical contacts with gold.','Gold is not the best conductor: silver and copper conduct better. Gold plating is useful on contacts and connectors because it conducts well while resisting oxidation and corrosion. Jewelry, decoration and historical coinage are other familiar uses. These are properties of bulk material, not a single atom.')}
 ];
 const progression=L('These metals come after the separate lanthanide row. An inner electron group fills as you move toward gold.','These Period 6 metals build up the 5d subshell, an electron group with room for ten. Hf through Ir have two through seven 5d electrons. Pt has nine 5d and one 6s electron; Au has ten 5d and one 6s.','The filled 4f¹⁴ core remains while 5d grows: Hf 5d², Ta 5d³, W 5d⁴, Re 5d⁵, Os 5d⁶ and Ir 5d⁷. Pt is 5d⁹ 6s¹ and Au is 5d¹⁰ 6s¹. A simple filling rule helps organize states but does not perfectly predict measured ground states. Both nearby 5d and outer 6s states matter for bonding.');
 const detail={
  'Hf-174':{half:[7e16,'years','About 7 × 10¹⁶ years'],modes:['Alpha (α) decay to ytterbium-170'],keys:['d5Hf174'],notes:['Named 2020 alpha-decay measurement; older compilations quote 2e15 years. This is a measured lifetime, not a search bound.'],uses:L('Hafnium-174 occurs naturally but changes very slowly.','Natural Hf-174 is radioactive. Scientists study its rare alpha decay.','Hf-174 is a naturally radioactive alpha emitter. This display cites the 2020 observed-decay measurement; other hafnium decay searches often report lower limits instead.')},
  'Ta-180m':{isomer:true,observational:true,keys:['d5Ta180m','d5TaEnergy'],notes:['No decay has been observed. Searches constrain several possible channels; their lower limits are not a measured half-life. The short-lived Ta-180 ground state is not the naturally occurring isomer.'],uses:L('The m means the nucleus has extra energy. This rare natural form has lasted for a very long time.','Ta-180m is a nuclear isomer, a long-lived excited version of the nucleus. No decay has been observed, so no measured half-life is shown.','Ta-180m is a naturally occurring, observationally stable nuclear isomer. It has 73 protons and 107 neutrons, just like the Ta-180 ground state, but different nuclear energy. Experiments report decay limits, not a measured lifetime.')},
  'W-180':{half:[1.8e18,'years','About 1.8 × 10¹⁸ years'],modes:['Alpha (α) decay to hafnium-176'],keys:['d5W180'],uses:L('Tungsten-180 is natural and changes extremely slowly.','W-180 is radioactive even though its lifetime is extremely long.','W-180 has observed alpha decay. The named CRESST measurement distinguishes its radioactivity from unobserved decay searches in other tungsten isotopes.')},
  'Re-187':{half:[4.12e10,'years','About 41 billion years'],modes:['Beta-minus (β−) to osmium-187'],uses:L('Rhenium-187 changes very slowly into osmium.','Most natural rhenium is Re-187. It is radioactive despite its extremely long lifetime.','Natural Re-187 undergoes very slow beta-minus decay to Os-187. It remains the default isotope here because it is the most abundant natural rhenium isotope.')},
  'Re-188':{half:[17.003,'hours','About 17 hours'],modes:['Beta-minus (β−) to osmium-188'],keys:['d5Re188'],uses:L('Rhenium-188 is made for specialized medical and research work.','Produced Re-188 is used in specialized radiation-treatment work and research. It requires professional radiation controls.','Re-188 can be obtained from W-188/Re-188 generators for specialized therapy applications and research. Treatment depends on the attached compound and clinical setting, not bare rhenium metal.')},
  'Os-184':{observational:true,keys:['d5OsLimits'],notes:['No established observed decay is assigned here. Published search bounds are not measured half-lives.'],uses:L('Osmium-184 is a rare part of natural osmium.','Scientists search for very rare Os-184 decay. No measured lifetime is assigned here.','Os-184 is observationally stable in this dataset. Rare-decay searches report lower bounds, which must not be shown as measured half-lives.')},
  'Os-186':{half:[2e15,'years','About 2 × 10¹⁵ years'],modes:['Alpha (α) decay to tungsten-182'],uses:L('Osmium-186 is natural and changes extremely slowly.','Natural Os-186 is a very long-lived radioactive isotope.','Os-186 alpha decay to W-182 is listed in the named NNDC nuclear snapshot. Natural occurrence and radioactive stability are different ideas.')},
  'Ir-192':{half:[73.827,'days','About 74 days'],modes:['Mainly beta-minus (β−) to platinum-192','Electron capture to osmium-192'],keys:['d5Radiography'],uses:L('Specialists use iridium-192 to inspect materials and treat some cancers. It is radioactive.','Ir-192 sources are used in industrial radiography and brachytherapy. Both require professionally controlled radioactive sources.','Ir-192 supports imaging inside welds and brachytherapy, which places radiation near a tumor. These established source applications require specialist controls. Useful sources are produced artificially.')},
  'Pt-190':{half:[4.97e11,'years','About 500 billion years'],modes:['Alpha (α) decay to osmium-186'],keys:['d5Pt190'],uses:L('Platinum-190 is a rare natural isotope that changes very slowly.','Pt-190 is naturally radioactive, with an extremely long alpha-decay lifetime.','Natural Pt-190 decays by alpha emission. The named 2017 measurement gives 4.97 × 10¹¹ years, rather than the older 6.5 × 10¹¹-year snapshot value.')},
  'Au-197':{uses:L('Gold-197 is the stable form found in natural gold.','Au-197 is gold’s only stable naturally occurring isotope.','Ordinary natural gold consists of stable Au-197. It is the isotope in most gold jewelry, contact coatings and other material uses.')},
  'Au-198':{half:[2.6956,'days','About 2.70 days'],modes:['Beta-minus (β−) to mercury-198'],keys:['d5Radiography'],uses:L('Gold-198 is radioactive and made for specialized work.','Produced Au-198 is used in research and has specialized or historical radiation-treatment uses.','Au-198 has research uses and a history in specialized brachytherapy sources. These are controlled radioactive-source applications, distinct from stable gold jewelry or electrical contacts.')}
 };
 source('d5TaEnergy','Nesterenko et al.','Direct determination of the excitation energy of quasi-stable isomer 180mTa','https://arxiv.org/abs/2205.10534','2022 direct measurement: 76.79(55) keV excitation energy; not a half-life.');
 const core=C.elements[71].neutralSubshells.filter(s=>!['5d','6s'].includes(s.id)); // [Xe] plus filled 4f = 68.
 for(const row of rows){
  const {z,name,symbol,d,s,mass}=row,slug=name.toLowerCase(),subs=[...core,{id:'5d',n:5,l:'d',occupancy:d},{id:'6s',n:6,l:'s',occupancy:s}],shells=[2,8,18,32,8+d,s],masses=[...row.natural.map(a=>a[0]),...row.extra],keys=['d5Abundance','d5Decay','d5'+symbol+'Atomic','d5'+symbol+'Uses',...new Set(masses.flatMap(m=>detail[symbol+'-'+m]?.keys||[])),...(symbol==='Pt'?['d5PlatinumMedicine']:symbol==='Au'?['d5GoldColor','d5Conductivity']:[])];
  source('d5'+symbol+'Atomic','NIST','Atomic Data for '+name,'https://physics.nist.gov/PhysRefData/Handbook/Tables/'+slug+'table1'+(symbol==='Pt'?'_a':'')+'.htm','Measured neutral configuration '+C.fullConfiguration(subs)+'. Abundances use CIAAW, not older handbook values.');
  source('d5'+symbol+'Uses','Royal Society of Chemistry',name+': properties and uses','https://periodic-table.rsc.org/element/'+z+'/'+slug,'Material, alloy, compound and engineering applications. Decay classifications use separate nuclear references.');
  const outer=L('This is the outside electron group. Nearby inside electrons also affect bonding.',s+' electron'+(s===1?' is':'s are')+' in the outer 6s group. The nearby 5d group also helps determine chemical behavior.','The highest numbered shell holds '+s+' electron'+(s===1?'':'s')+' in 6s. Nearby 5d states also influence bonding; only counting the outer shell is not enough.'),inner=L('This electron is in an inside group around the nucleus.','Inner electrons occupy lower-numbered shells. The nearby 5d group also matters for bonding.','This electron occupies an inner quantum state, an allowed electron state around the nucleus. The filled 4f core differs from nearby 5d states that also influence bonding.');
  elements[z]={atomicNumber:z,name,symbol,defaultIsotope:slug+'-'+mass,availableIsotopes:masses.map(m=>slug+'-'+m),neutralElectronCount:z,neutralShells:shells,neutralSubshells:subs,neutralConfiguration:C.fullConfiguration(subs),fullConfiguration:C.fullConfiguration(subs),shorthandConfiguration:'[Xe] 4f¹⁴ '+C.fullConfiguration(subs.slice(-2)),heavyDExplorer:true,exactHeavyParticles:true,groupedCoreElectronCount:68,fullDetail:false,waveResolution:'subshell',conciseOverview:true,filledCoreSubshells:['4f'],descriptions:row.descriptions,context:{title:'Science and Electrical Engineering',descriptions:row.engineering},valence:{shells:[6],importantSubshells:['5d','6s'],descriptions:outer,studentNote:outer.high},sources:keys,isotopeSourceKeys:keys,periodProgressionTitle:'Across the 5d Metals',periodProgression:progression,
   configurationNote:symbol==='Au'?L('Gold has a filled inside group and one outside electron. Its yellow color comes from how the metal handles light.','Gold has ten 5d electrons and one 6s electron. The electronic structure of solid gold changes how it absorbs and reflects light.','Gold’s large positive nucleus strongly attracts inner electrons. Their speeds are high enough for relativistic physics to affect electronic energies. These energy changes influence how solid gold absorbs and reflects light, helping explain its yellow color. Relativity is one important contribution, not the only factor in all gold chemistry.'):symbol==='Pt'?L('Platinum has one outside electron in this model.','Platinum has nine 5d electrons and one 6s electron. This differs from a simple filling prediction.','The observed lowest-energy state is 5d⁹ 6s¹, not the simple 5d⁸ 6s² prediction. This is a measured arrangement, not electrons choosing to become stable.'):null,
   isotopeGuideKeys:['isotope','stable','radioactive','abundance','halfLife','decay','weighted','cosmic'],isotopeEducation:{isotope:L('Isotopes have different numbers of neutrons.','Every '+slug+' nucleus has '+z+' protons. Changing its neutron count changes its isotope.','Neutral isotopes share this electron arrangement. Nuclear isomers have the same particle counts as their ground state but extra nuclear energy.'),abundance:L('The percentages describe natural material on Earth.','Terrestrial abundance means the mixture found in natural Earth materials, not everywhere in space.','CIAAW percentages describe representative terrestrial compositions with uncertainty. Rounded measurements need not total exactly 100%; they are preserved as published.'),weighted:L('Atomic weight averages the natural isotope mixture.','An isotope’s mass number counts its protons and neutrons. Atomic weight is an average over isotope masses.','Atomic weight uses measured isotope masses and their proportions. It is not the integer mass number of one nucleus.')},
   education:{concepts:{'valence-electron':outer,'inner-electron':inner},regions:{waveValence:outer,orbitalValence:outer,waveInner:inner,orbitalInner:inner},models:{
    bohr:L(name+' has '+z+' electrons around its nucleus. Six circles help count them; they are not real tracks.','The six shells count '+shells.join(', ')+' electrons. Circular paths are a learning model rather than real electron tracks.','Every electron and nucleon remains represented. The shells contain '+shells.join(', ')+' electrons, with '+s+' in outer 6s. This drawing simplifies a complex atom; the counts are exact but paths and distances are not literal or to scale.'),
    wave:L(name+' electrons behave like waves. These bands show a simplified set of allowed patterns.','Electrons occupy only certain allowed states. The bands summarize many occupied states in '+slug+' rather than showing electron balls on paths.','All fourteen occupied subshells can be inspected. The 5d and 6s regions stand out against the filled inner core, including 4f. These are conceptual wave patterns, not an exact reconstruction of interacting electrons or a physical-scale picture.'),
    quantum:L('The cloud shows where '+slug+' electrons may be found. It is a simplified picture, not a solid object.','Overview combines 68 inner electrons and highlights 5d and 6s. Explore Subshells lets you inspect any occupied group, including the filled 4f group.','This cloud summarizes the chances of finding electrons in many occupied states. Overview groups 68 inner electrons and highlights 5d'+d+' and 6s'+s+'. The cloud has no solid boundary and is not an atomic photograph. Focus mode shows one representative shape with the correct subshell occupancy.')
   }}};
  for(const m of masses){const a=parseInt(m,10),id=slug+'-'+m,v=detail[symbol+'-'+m]||{},natural=row.natural.find(n=>n[0]===m),stable=!v.half,halfLife=v.half?{value:v.half[0],unit:v.half[1],display:v.half[2]}:null,displayName=name+'-'+m;
   const status=v.isomer?'This naturally occurring excited nucleus has no observed decay.':v.observational?'No decay has been observed.':stable?'No radioactive decay has been observed.':natural?'It is naturally radioactive.':'It is produced and radioactive.';
   const descriptions=L(displayName+' has '+z+' protons and '+(a-z)+' neutrons. '+status,displayName+' contains '+(a-z)+' neutrons. '+status,displayName+' contains '+z+' protons and '+(a-z)+' neutrons. '+status),uses=v.uses||L('This isotope is part of natural '+slug+'.','Most ordinary '+slug+' applications use the natural isotope mixture.','This isotope contributes to the terrestrial mixture. No separate industrial use is implied for every isotope.');
   isotopes[id]={id,element:name,symbol,elementSymbol:symbol,atomicNumber:z,massNumber:a,protons:z,neutrons:a-z,neutralElectronCount:z,stable,observationallyStable:!!v.observational,stabilityClassification:v.isomer?'Observationally stable · nuclear isomer':v.observational?'Observationally stable':stable?'Stable':natural?'Radioactive · extremely long-lived':'Radioactive · produced',common:!!natural,displayName,halfLife,decayModes:v.modes||[],primaryDecay:v.modes?.[0]||null,naturalComponent:!!natural,naturalAbundance:natural?{percent:natural[1],uncertaintyPercentagePoints:natural[2],scope:'CIAAW representative terrestrial composition'}:null,abundanceText:natural?'Representative terrestrial abundance: '+natural[1]+'%.'+(v.isomer?' This percentage belongs to the long-lived nuclear isomer.':!stable?' Natural and radioactive.':''):'Produced artificially for specialized work. No ordinary natural terrestrial abundance is assigned.',origin:natural?'Natural terrestrial '+(v.isomer?'nuclear isomer':'isotope'):'Produced for specialized work',metastableStateLabel:v.isomer?'m':null,excitationStateId:v.isomer?'m':'ground',excitationEnergyKeV:v.isomer?76.79:0,groundState:v.isomer?{id:'tantalum-180',atomicNumber:z,massNumber:a,excitationStateId:'ground',selectable:false}:null,nuclearStateDescriptions:v.isomer?L('The m marks extra energy in the nucleus. It does not add a neutron.','Ta-180m is a nuclear isomer: an excited version of the same nucleus. It has the same 73 protons and 107 neutrons as Ta-180.','Ta-180m is a very long-lived excited nucleus, unlike the short-lived Ta-180 ground state. No decay is observed, so experimental lower limits are not displayed as a half-life. The neutral electron arrangement is unchanged.'):null,descriptions,note:descriptions.high,uses:uses.high,usesByLevel:uses,advancedDecayNotes:v.notes||[],sources:['d5Abundance','d5Decay','d5'+symbol+'Uses',...(v.keys||[])]};
  }
 }
 C.isotopeSources=C.deepFreeze({...C.isotopeSources,...sources});C.isotopes=C.deepFreeze({...C.isotopes,...isotopes});C.elements=C.deepFreeze({...C.elements,...elements});
 C.validateHeavyDData=(catalog=elements,nuclides=C.isotopes)=>{const r=C.validatePeriod4Data(catalog,nuclides),expected={72:['Hafnium','Hf',180,2,2],73:['Tantalum','Ta',181,3,2],74:['Tungsten','W',184,4,2],75:['Rhenium','Re',187,5,2],76:['Osmium','Os',192,6,2],77:['Iridium','Ir',193,7,2],78:['Platinum','Pt',195,9,1],79:['Gold','Au',197,10,1]};for(const e of Object.values(catalog)){const x=expected[e.atomicNumber];if(!x){r.errors.push('Unsupported 5d element');continue;}const [name,symbol,m,d,s]=x,sub=[...core,{id:'5d',n:5,l:'d',occupancy:d},{id:'6s',n:6,l:'s',occupancy:s}];if(e.name!==name||e.symbol!==symbol)r.errors.push('5d identity mismatch');if(JSON.stringify(sub)!==JSON.stringify(e.neutralSubshells)||JSON.stringify(e.neutralShells)!==JSON.stringify([2,8,18,32,8+d,s]))r.errors.push(symbol+': measured configuration required');if(nuclides[e.defaultIsotope]?.massNumber!==m)r.errors.push(symbol+': incorrect default isotope');for(const id of e.availableIsotopes){const i=nuclides[id];if(!i)continue;if(['hafnium-174','tungsten-180','rhenium-187','osmium-186','platinum-190'].includes(id)&&i.stable)r.errors.push(id+': observed radioactivity required');if(id==='tantalum-180m'&&(!i.stable||!i.observationallyStable||i.halfLife!==null||i.metastableStateLabel!=='m'||i.excitationStateId!=='m'||i.excitationEnergyKeV!==76.79||i.groundState?.id!=='tantalum-180'||i.groundState?.selectable!==false||!i.nuclearStateDescriptions?.high||!i.naturalComponent))r.errors.push('Ta-180m must retain its natural observationally stable nuclear-isomer identity');}}r.ok=!r.errors.length;return r;};
 C.heavyDValidation=C.validateHeavyDData();C.enabledValidation=C.validateEnabledData();if(!C.heavyDValidation.ok||!C.enabledValidation.ok)throw Error([...C.heavyDValidation.errors,...C.enabledValidation.errors].join('; '));
})(window.Copper);
