/* Verified classroom record, shared by the student explorer and development harness. */
(function(C){
 'use strict';
 const levels=(elementary,middle,high)=>({elementary,middle,high});
 const sources={
  hydrogenOrbitals:{organization:'MIT OpenCourseWare',title:'Hydrogen atom wavefunctions (orbitals), Principles of Chemical Science',url:'https://ocw.mit.edu/courses/5-111-principles-of-chemical-science-fall-2008/resources/lecnotes06/',supports:'Spherical s orbitals and radial probability. The 1s display samples a scaled, truncated exponential density; it is not a physical-size calculation.'},
  hydrogenIAEA:{organization:'International Atomic Energy Agency',title:'Introduction to Body Composition Assessment Using the Deuterium Dilution Technique',url:'https://www-pub.iaea.org/MTCD/Publications/PDF/Pub1450_web.pdf',supports:'Stable deuterium as a tracer in labelled water and body-water research.'},
  hydrogenHeavyWater:{organization:'International Atomic Energy Agency',title:'Introduction to Body Composition Assessment Using the Deuterium Dilution Technique: Analysis of Urine Samples',url:'https://www-pub.iaea.org/MTCD/Publications/PDF/Pub1451_web.pdf',supports:'Deuterium-labelled water and heavy-water terminology.'},
  hydrogenCIAAW:{organization:'CIAAW / IUPAC',title:'Atomic Weight of Hydrogen',url:'https://ciaaw.org/hydrogen.htm',supports:'Stable isotope identities, terrestrial abundance intervals, natural variability, tritium beta-minus decay and 12.3-year half-life, natural and artificial production and environmental tracing.'},
  hydrogenNIST:{organization:'NIST',title:'Atomic Data for Hydrogen',url:'https://physics.nist.gov/PhysRefData/Handbook/Tables/hydrogentable1.htm',supports:'Atomic number 1 and neutral ground state 1s. Historical fixed abundances on this page are not used.'},
  hydrogenRSC:{organization:'Royal Society of Chemistry',title:'Hydrogen: element information, properties and uses',url:'https://periodic-table.rsc.org/element/1/hydrogen',supports:'Group 1, period 1, s-block, 1s¹ configuration, cosmic abundance, stars, ammonia production and biological molecules.'},
  hydrogenNASA:{organization:'NASA / LAMBDA',title:'Baryonic Density',url:'https://lambda.gsfc.nasa.gov/education/graphic_history/baryonicd.html',supports:'Deuterium abundance as evidence about nucleosynthesis and matter content in the early universe.'},
  hydrogenFusion:{organization:'U.S. Department of Energy',title:'DOE Explains: Fusion Reactions',url:'https://www.energy.gov/science/doe-explainsfusion-reactions',supports:'Deuterium and tritium in fusion research.'},
  hydrogenEnergy:{organization:'U.S. Department of Energy',title:'Hydrogen: A Flexible Energy Carrier',url:'https://www.energy.gov/cmei/fuels/articles/hydrogen-flexible-energy-carrier',supports:'Fuel cells, production from other materials using energy, and the distinction between an energy carrier and a primary energy source.'},
  hydrogenLighting:{organization:'U.S. Nuclear Regulatory Commission',title:'Backgrounder on Tritium EXIT Signs',url:'https://www.nrc.gov/reading-rm/doc-collections/fact-sheets/fs-tritium.html',supports:'Tritium in some self-powered lighting applications.'}
 };
 C.isotopeSources=C.deepFreeze({...C.isotopeSources,...Object.fromEntries(Object.entries(sources).map(([key,s])=>[key,{...s,accessed:'2026-09-09'}]))});
 const descriptions=[
  levels('Hydrogen-1 has one proton and one electron. It has no neutron.','Hydrogen-1 is the most common hydrogen isotope. Its nucleus contains one proton and no neutron.','Hydrogen-1, or protium, contains one proton and no neutron. It makes up the overwhelming majority of naturally occurring hydrogen.'),
  levels('Deuterium is hydrogen with one proton and one neutron.','Deuterium is a stable hydrogen isotope. Its nucleus contains one proton and one neutron.','Deuterium is a stable isotope with one proton and one neutron. Its distinct mass helps scientists trace water and other substances.'),
  levels('Tritium is hydrogen with one proton and two neutrons. It slowly changes because it is radioactive.','Tritium is a radioactive hydrogen isotope with one proton and two neutrons. About half of a large sample decays in approximately 12.3 years.','Tritium contains one proton and two neutrons. It undergoes beta-minus decay with a half-life of approximately 12.3 years.')
 ];
 const isotopes=Object.fromEntries([1,2,3].map((massNumber,index)=>{const id='hydrogen-'+massNumber;return [id,{id,atomicNumber:1,massNumber,protons:1,neutrons:massNumber-1,stable:massNumber!==3,common:true,displayName:'Hydrogen-'+massNumber+' ('+['Protium','Deuterium','Tritium'][index]+')',origin:massNumber===3?'natural-trace-and-produced':'natural',naturalAbundance:massNumber===3?null:{rangePercent:massNumber===1?[99.972,99.999]:[.001,.028],scope:'CIAAW normal terrestrial materials; varies by sample'},abundanceText:massNumber===3?'Only trace amounts occur naturally. Tritium is also produced artificially.':'CIAAW normal terrestrial range: '+(massNumber===1?'99.972–99.999%':'0.001–0.028%')+'. The proportion varies among materials and environments.',halfLife:massNumber===3?{value:12.3,unit:'years',display:'Approximately 12.3 years'}:null,decayModes:massNumber===3?['Beta-minus decay (β−) to helium-3']:[],descriptions:descriptions[index],note:descriptions[index].high,uses:['Most ordinary hydrogen is hydrogen-1. Its simple atom is a useful starting point for learning atomic models.','Deuterium is used in scientific tracing and fusion research. Heavy water has deuterium in place of ordinary hydrogen.','Tritium is used in fusion research, environmental tracing and some self-powered lights.'][index],sources:['hydrogenCIAAW','hydrogenNIST',...(massNumber>1?['hydrogenFusion']:[]),...(massNumber===3?['hydrogenLighting']:[])]}];}));
 C.isotopes=C.deepFreeze({...C.isotopes,...isotopes});
 const electron=levels('Hydrogen has just one electron. It is also the outer electron.','Hydrogen’s only electron is in its first shell. It is also its valence electron, which helps the atom interact.','The same single electron occupies the 1s state and is hydrogen’s valence electron. These labels do not refer to two different electrons.');
 C.elements=C.deepFreeze({...C.elements,1:{atomicNumber:1,name:'Hydrogen',symbol:'H',conciseOverview:true,category:'Reactive nonmetal',period:1,group:1,block:'s',neutralElectronCount:1,defaultIsotope:'hydrogen-1',availableIsotopes:Object.keys(isotopes),neutralShells:[1],neutralConfiguration:'1s¹',fullConfiguration:'1s¹',neutralSubshells:[{id:'1s',n:1,l:'s',occupancy:1}],valence:{shells:[1],importantSubshells:['1s'],studentNote:'Hydrogen has one electron. It is both the first-shell electron and the valence electron.'},warnings:[],sources:Object.keys(sources),
  descriptions:levels('Hydrogen is the simplest element. Most hydrogen atoms have one proton and one electron.','Hydrogen has atomic number 1 because every hydrogen atom contains one proton. A neutral hydrogen atom also has one electron.','Hydrogen is the simplest element, with one proton and one electron in its neutral ground state. Its simple structure makes it especially useful for studying atomic and quantum physics.'),
  context:{title:'Why Hydrogen Matters',descriptions:levels('Hydrogen is the most common element in the universe. Stars contain a great deal of it. It is also part of water.','Hydrogen is the most abundant element in the universe. It is part of water and many molecules in living things. Industry uses it to make ammonia for fertilizers.','Hydrogen is the most abundant element in the universe and a major part of stars. It is used to make ammonia and can supply fuel cells. As a fuel, it carries energy used to produce it; its environmental impact depends on how it is made.')},
  placementNote:'Hydrogen sits above group 1 because it has one electron. It is a nonmetal with properties very different from the alkali metals.',
  isotopeSourceKeys:Object.keys(sources),isotopeGuideKeys:['isotope','stable','radioactive','abundance','halfLife','decay','weighted','cosmic'],
  isotopeEducation:{
   isotope:levels('Hydrogen isotopes have one proton but different numbers of neutrons.','All hydrogen isotopes have one proton. Changing the neutron count changes the isotope.','Hydrogen isotopes share one proton. Their neutron counts are zero, one or two in this explorer. Neutral atoms of all three have one electron.'),
   abundance:levels('Almost all natural hydrogen is hydrogen-1. A small amount is deuterium. The mixture varies.','Natural hydrogen is mostly hydrogen-1 with a small, variable amount of deuterium. Tritium is radioactive and occurs only in traces.','CIAAW gives ranges for normal terrestrial materials, not one universal mixture: hydrogen-1 99.972–99.999%; deuterium 0.001–0.028%. Radioactive tritium is present only in traces and is not part of a stable-isotope chart.'),
   weighted:levels('The periodic-table mass describes a mixture of isotopes. It is different from one atom’s mass number.','Hydrogen’s average atomic mass depends on its isotope mixture. Most natural samples contain almost entirely hydrogen-1.','Hydrogen’s standard atomic-weight interval is [1.00784, 1.00811]. It reflects variation among normal terrestrial materials. Mass numbers count particles; atomic weights use measured isotope masses.'),
   cosmic:levels('Hydrogen is the most common element in the universe. Deuterium helps scientists learn about its early history. Mixtures on Earth and in space can differ.','Most ordinary hydrogen is hydrogen-1. Deuterium gives clues about the early universe. Tritium is radioactive and rare in nature. Earth’s isotope mixture is not a rule for all of space.','Deuterium measurements help test how light nuclei formed in the early universe. Terrestrial and cosmic isotope ratios need not match. Tritium is rare in nature and is also made artificially.')
  },
  education:{concepts:{'valence-electron':electron},models:{
   wave:levels('One closed wave represents hydrogen’s electron state. The electron is not a ball riding on it.','Hydrogen’s electron has wave properties. A whole-number wave pattern fits around this closed loop and represents an allowed state.','Hydrogen’s electron can be associated with a matter wave. Only particular standing-wave states are allowed, helping explain its specific energies. This loop is a conceptual bridge to the modern model.'),
   quantum:levels('The round cloud shows where hydrogen’s one electron might be found. It has no fixed track.','Hydrogen’s occupied 1s orbital is spherical. Denser parts of the cloud show places where the electron is more likely to be detected.','The neutral ground state occupies 1s¹. Its spherical cloud shows where the electron is more likely to be detected. Dots sample this region; they are not separate electrons.')
  },regions:{waveValence:levels('This closed wave represents hydrogen’s one electron state.','The standing pattern represents hydrogen’s only occupied energy level. It contains one electron, not a ball traveling along the wave.','A whole-number wave pattern closes on itself. This represents an allowed state for hydrogen’s single electron, not its physical path.'),orbitalValence:levels('This round cloud shows where hydrogen’s one electron might be.','The 1s cloud shows chances of detecting hydrogen’s single electron. It is also the valence electron.','This occupied 1s¹ cloud represents hydrogen’s single electron. It shows detection likelihood, not a known path or a physical mist.')}}
 }});
 C.hydrogenValidation={ok:true,errors:[]};
 for(const isotope of Object.values(isotopes)){const r=C.validateRecord(C.elements[1],isotope);if(!r.ok||r.atom?.protons!==1||r.atom?.neutrons!==isotope.massNumber-1||r.atom?.electrons!==1||r.atom?.shells.join()!=='1'||C.fullConfiguration(r.atom?.subshells||[])!=='1s¹'||isotope.stable!==(isotope.massNumber<3)||(!isotope.stable&&(!(isotope.halfLife?.value>0)||!isotope.decayModes.length)))C.hydrogenValidation.errors.push(isotope.id+': invalid hydrogen record');}
 C.hydrogenValidation.ok=!C.hydrogenValidation.errors.length;if(!C.hydrogenValidation.ok)throw Error(C.hydrogenValidation.errors.join('; '));
})(window.Copper);
