(function(C){
 'use strict';
 const freeze=o=>{Object.values(o).forEach(v=>{if(v&&typeof v==='object')freeze(v);});return Object.freeze(o);};
 C.isotopeSources=freeze({
  ciaaw:{organization:'CIAAW / IUPAC',title:'Atomic Weight of Copper',url:'https://ciaaw.org/copper.htm',accessed:'2026-09-08',supports:'Stable isotope masses, terrestrial fractions, standard atomic weight and natural variation.'},
  iaea:{organization:'International Atomic Energy Agency',title:'Cyclotron Produced Radionuclides: Physical Characteristics and Production Methods, TRS 468 (2009), sections 2.16–2.17',url:'https://pub.iaea.org/mtcd/publications/pdf/trs468_web.pdf',accessed:'2026-09-08',supports:'Cu-64 half-life 12.7 h, three decay modes, PET/tracer and therapeutic research; Cu-67 rounded half-life 62 h, beta-minus decay, therapy and imaging.'},
  euramet:{organization:'EURAMET / LNE-LNHB',title:'Standardization, decay data measurements and evaluation of 64Cu (project 1085)',url:'https://www.euramet.org/research-innovation/search-research-projects/details/project/standardization-decay-data-measurements-and-evaluation-of-64cu',accessed:'2026-09-08',supports:'Cu-64 12.7-hour half-life and PET use; copper isotope diagnostic/therapy pairing.'},
  nasa:{organization:'NASA Goddard / Imagine the Universe',title:'Ask an Astrophysicist: Physics of Stars — chemical composition',url:'https://imagine.gsfc.nasa.gov/ask_astro/stars.html',accessed:'2026-09-08',supports:'Hydrogen/helium dominate cosmic matter; heavier-element content varies between environments.'},
  copperStars:{organization:'Romano et al., Monthly Notices of the Royal Astronomical Society 378, L59–L63 (2007)',title:'Contrasting copper evolution in Omega Centauri and the Milky Way',url:'https://arxiv.org/abs/astro-ph/0703760',accessed:'2026-09-08',supports:'Copper production associated with stellar nucleosynthesis and supernova processes; no universal copper-isotope prevalence is established here.'}
 });
 C.isotopes=freeze({
  'copper-63':{id:'copper-63',atomicNumber:29,massNumber:63,stable:true,common:true,origin:'natural',naturalAbundance:{percent:69.15,scope:'typical terrestrial copper',uncertaintyPercentagePoints:.15},isotopicMass:62.929597,halfLife:null,decayModes:[],sources:['ciaaw'],note:'The most abundant naturally occurring copper isotope.',uses:'Ordinary copper contains a natural mixture dominated by copper-63. Industrial copper is not normally separated by isotope.',why:'It is the main isotope in naturally occurring copper.'},
  'copper-65':{id:'copper-65',atomicNumber:29,massNumber:65,stable:true,common:true,origin:'natural',naturalAbundance:{percent:30.85,scope:'typical terrestrial copper',uncertaintyPercentagePoints:.15},isotopicMass:64.927790,halfLife:null,decayModes:[],sources:['ciaaw'],note:'The second stable naturally occurring copper isotope.',uses:'Together with copper-63, it makes up ordinary natural copper and contributes to its weighted average atomic mass.',why:'It helps explain why the periodic table lists about 63.546, rather than one whole-number mass number.'},
  'copper-64':{id:'copper-64',atomicNumber:29,massNumber:64,stable:false,common:true,origin:'produced',naturalAbundance:null,halfLife:{value:12.7,unit:'hours',display:'Approximately 12.7 hours'},decayModes:['Positron emission (β+)','Beta-minus decay (β−)','Electron capture'],sources:['iaea','euramet'],note:'A radioactive isotope produced for medical and research uses.',uses:'Used in PET imaging and radiotracer research. Combined diagnostic and therapeutic applications are investigated.',why:'Its radiation can help researchers track where a labeled substance goes in the body.'},
  'copper-67':{id:'copper-67',atomicNumber:29,massNumber:67,stable:false,common:true,origin:'produced',naturalAbundance:null,halfLife:{value:62,unit:'hours',display:'Approximately 2.58 days (about 62 hours)',precisionNote:'IAEA TRS 468 rounds the half-life to 62 h. Days are a classroom-level conversion.'},decayModes:['Beta-minus decay (β−)'],sources:['iaea'],note:'A radioactive isotope produced for therapy research.',uses:'Investigated for targeted radionuclide therapy. Accompanying gamma radiation can support imaging.',why:'It can deliver radiation through a molecule chosen to target a tissue. This is a specialized medical application, not a property of ordinary copper products.'}
 });
 for(const iso of Object.values(C.isotopes)){if(iso.massNumber<iso.atomicNumber||!Number.isInteger(iso.massNumber))throw Error('Invalid isotope mass number');if(iso.stable&&(iso.halfLife!==null||iso.decayModes.length))throw Error('Stable isotope cannot have configured decay');if(!iso.stable&&(!iso.halfLife||iso.halfLife.value<=0||!iso.decayModes.length))throw Error('Radioisotope requires half-life and decay modes');if(iso.naturalAbundance&&(iso.naturalAbundance.percent<0||iso.naturalAbundance.percent>100))throw Error('Invalid natural abundance');}
 C.isotopeText={
  isotope:{elementary:'Isotopes are versions of one element with different numbers of neutrons.',middle:'Isotopes share a proton count but have different neutron counts. Their mass numbers count protons and neutrons together.',high:'Changing a copper isotope changes the neutron count. The 29 protons still identify copper, and a neutral atom still has 29 electrons.'},
  stable:{elementary:'A stable isotope has not been seen changing through radioactive decay.',middle:'No radioactive decay has been observed for a stable isotope. Its nucleus stays the same during ordinary use.',high:'Stable means no radioactive decay has been observed. It does not mean an infinite half-life has been measured.'},
  radioactive:{elementary:'A radioactive isotope can change into another nucleus and release radiation.',middle:'A radioactive nucleus can change by releasing particles or energy. The picture stays visible here so you can explore it.',high:'A radioactive isotope has an unstable nucleus. Decay changes nuclear identity and releases particles or energy. This explorer does not simulate an individual decay event.'},
  abundance:{elementary:'Natural abundance tells us how common an isotope is in a natural sample.',middle:'The bar describes typical natural copper on Earth. Different natural samples can have slightly different mixtures.',high:'These percentages are typical terrestrial isotope fractions, not percentages for the entire universe. Natural samples vary slightly, and other environments can have different ratios.'},
  halfLife:{elementary:'A half-life is the time for about half of a large group of radioactive atoms to change.',middle:'After one half-life, about half of a large group of radioactive nuclei remain unchanged. We cannot predict exactly when one nucleus will decay.',high:'Half-life predicts the statistical behavior of a large group. After each half-life, about half of the remaining radioactive nuclei survive. Individual nuclei do not all decay on a shared schedule.'},
  decay:{elementary:'Decay mode names the way a radioactive nucleus changes.',middle:'Beta-minus decay releases an electron; positron emission releases its positively charged counterpart. Electron capture takes an electron into the nucleus.',high:'Decay mode describes how a radioactive nucleus changes. Beta-minus decay emits an electron; beta-plus decay emits a positron, its positive counterpart. Electron capture absorbs an atomic electron into the nucleus.'},
  weighted:{elementary:'The periodic-table mass is an average for a mixture. It is not the mass number of one atom.',middle:'An average gives more weight to the more common isotope. Actual isotope masses and their proportions give copper a periodic-table atomic mass near 63.546.',high:'Using measured isotope masses: 0.6915 × 62.929597 + 0.3085 × 64.927790 ≈ 63.546. Mass numbers 63 and 65 are counts, not the measured masses used in this calculation.'},
  medical:{elementary:'Some isotopes help doctors make pictures or study treatments.',middle:'A medical isotope may be attached to a substance that goes to a chosen tissue. Its radiation can help with imaging or treatment research.',high:'Specially prepared radioactive compounds can trace biological processes or deliver radiation to chosen tissues. Uses depend on the compound and application; research potential is not a blanket treatment approval.'},
  cosmic:{elementary:'Copper is far rarer in space than hydrogen and helium. Stars helped make its nuclei.',middle:'Copper nuclei are made in nuclear processes in stars and stellar explosions. Earth’s isotope mixture is not a rule for every place in space.',high:'Copper is much less abundant cosmically than hydrogen and helium. Its nuclei are made through processes associated with stars and stellar explosions. Isotope ratios can differ between environments; no reliable universal copper-isotope percentage was established from the sources used here.'}
 };
})(window.Copper);
