/* Phases 6H and 6I: measured neutral configurations, not an Aufbau prediction. */
(function(C){
 'use strict';
 const L=(elementary,middle,high)=>({elementary,middle,high}),sources={},elements={},isotopes={};
 const source=(key,organization,title,url,supports)=>{sources[key]={organization,title,url,supports,accessed:'2026-09-12'};};
 source('lnAbundance','CIAAW / IUPAC','Isotopic compositions 2024','https://www.ciaaw.org/isotopic-abundances.htm','Representative La–Lu terrestrial percentages and uncertainties. No ordinary promethium composition.');
 source('lnDecay','NNDC / Brookhaven','Nuclear Wallet Cards, April 2005','https://www.lnl.infn.it/wp-content/uploads/Nuclear_Wallet_Cards.pdf','Named nuclear snapshot: La-138 1.02e11 y EC/beta-minus; Pr-144 17.28 min beta-minus; Nd-144 2.29e15 y alpha; Pm-145 17.7 y mainly EC; Pm-147 2.6234 y beta-minus; Sm-147 1.06e11 y and Sm-148 7e15 y alpha; Eu-152 decay branches; the half-life uses the newer NIST SRM certificate; Gd-152 1.08e14 y alpha; Gd-153 240.4 d EC; Tb-161 6.906 d beta-minus; Ho-166 26.83 h beta-minus; Tm-170 128.6 d beta-minus and minor EC. Lu-176/177 use separately named sources. Search limits are not measured half-lives.');
 source('lnCeLimits','Danevich et al. / Institute for Nuclear Research','Quest for double beta decay of 160Gd and Ce isotopes','https://lpd.kinr.kyiv.ua/publications/2001/npa-2001-694-375.pdf','Primary experiment reports lower bounds, not observed decay, for Ce-136/138/142 and Gd-160. These remain observationally stable here.');
 source('lnEu151','Casali et al. / INFN collaboration','Discovery of the 151Eu alpha decay','https://arxiv.org/abs/1311.2834','Observed Eu-151 alpha decay to Pm-147: 4.62e18 years, 2014 publication. Supersedes older stable classifications.');
 source('lnNd150','NEMO-3 Collaboration','Measurement of the 150Nd two-neutrino double-beta decay half-life','https://arxiv.org/abs/1606.08494','2016 full-exposure result: 9.34e18 years to the Sm-150 ground state. Distinct from limits on neutrinoless modes.');
 source('lnDating','US Geological Survey','Using Radioactive Decay to Determine Geologic Age','https://www.usgs.gov/educational-resources/geologic-age-using-radioactive-decay-determine-geologic-age','Sm-147 alpha decay to Nd-143 and its geological dating use.');
 source('lnCapture','NIST Center for Neutron Research','Neutron scattering lengths and cross sections','https://www.ncnr.nist.gov/resources/n-lengths/list.html','Strong thermal-neutron absorption by Sm-149 and exceptionally large Gd-157 absorption. Cross sections depend on neutron energy.');
 source('lnPmUse','Oak Ridge National Laboratory','Changing process leads to purer Pm-147 — and more of it','https://www.ornl.gov/news/changing-process-leads-purer-pm-147-and-more-it','2023 report: Pm-147 production for research and plastic-film thickness instruments.');
 source('lnPmBattery','Oak Ridge National Laboratory','Reactor production of promethium-147','https://impact.ornl.gov/en/publications/reactor-production-of-promethium-147/','Research on Pm-147 production for specialized betavoltaic batteries.');
 source('lnEuCalibration','NIST','SRM 4370d Europium-152 Solution','https://tsapps.nist.gov/srmext/certificates/4370d.pdf','Eu-152 instrument calibration; certificate uses a 13.517-year half-life.');
 source('lnGd153','US DOE / National Isotope Development Center','DOE and MURR Secure Critical Radioisotope Supply Chain for Medical Imaging','https://www.isotopes.gov/node/1546','Gd-153 radiation sources for medical imaging instrument calibration. Distinct from non-radioactive MRI contrast compounds.');
 source('lnMRI','US Food and Drug Administration','MRI (Magnetic Resonance Imaging)','https://www.fda.gov/radiation-emitting-products/medical-imaging/mri-magnetic-resonance-imaging','Some MRI exams use gadolinium-based contrast drugs, not elemental gadolinium metal.');
 source('lnMagnets','US Department of Energy','Scientists Stick to a New Efficient Magnet','https://www.energy.gov/cmei/ammto/articles/scientists-stick-new-efficient-magnet','Samarium-cobalt magnets and high-temperature magnetic performance.');
 source('lnMotor','US Department of Energy','Electric Motors Research and Development','https://www.energy.gov/cmei/vehicles/electric-motors-research-and-development','Permanent-magnet motor operation and energy conversion; magnets alone do not generate electrical energy.');
 source('lnCeAlpha','DAMA collaboration / INFN','Search for alpha decay of naturally occurring cerium isotopes','https://web.sites.lngs.infn.it/lngs_infn/contents/lngs_en/research/experiments_scientific_info/library_publications/preprint_reports/preprint/preprint78.pdf','Cerium alpha-decay search lower bounds are not observed lifetimes.');
 source('lnEuLED','Jia et al.','First-principles Study of the Luminescence of Eu2+-doped Phosphors','https://arxiv.org/abs/1709.00311','Europium-doped phosphors studied for white LEDs and scintillation.');
 source('lnGdSensor','Faltinath et al.','Simulating Gadolinium-Induced Magnetic Field Variations for Temperature Sensing with Magneto-Mechanical Resonators','https://arxiv.org/abs/2508.21794','Simulation research on gadolinium temperature sensing; not a claim of commercial deployment.');
 source('lnSmSensor','National Bureau of Standards / NIST','Publications of the National Bureau of Standards 1987 Catalog','https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication305supp20.pdf','Catalog includes research on heat-resistant samarium-cobalt magnets in electromagnetic acoustic transducers.');
 source("lnTbTrial","Paul Scherrer Institute","Using terbium against lymphoma","https://www.psi.ch/en/news/media-releases/using-terbium-against-lymphoma","Tb-161 clinical-trial research and roughly 6.9-day half-life.");
 source("lnHoResearch","IAEA","Release of Patients After Radionuclide Therapy","https://www-pub.iaea.org/MTCD/Publications/PDF/pub1417_web.pdf","Historical Ho-166 compounds and microsphere treatment studies. Its printed days unit is erroneous; Ho-166 half-life uses NNDC hours.");
 source("lnHoLaser","US FDA","Holmium laser system K201455","https://www.accessdata.fda.gov/cdrh_docs/pdf20/K201455.pdf","Holmium surgical laser and kidney-stone fragmentation applications.");
 source("lnLu176","CIAAW / IUPAC","Atomic Weight of Lutetium","https://ciaaw.org/lutetium.htm","Lu-176 naturally radioactive; cited 3.57(14)e10-year half-life and Lu-Hf geological dating.");
 source("lnLuTherapy","US FDA","Lutathera prescribing information, 2024","https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/208700s031lbl.pdf","Approved Lu-177 dotatate therapy; 6.647-day physical half-life; beta-minus to Hf-177.");
 source("lnYbClock","NIST","Yb Optical Lattice Clock","https://www.nist.gov/programs-projects/yb-optical-lattice-clock","Yb-171 atoms used in optical lattice clock research.");
 source("lnLateUses","US Geological Survey","Potential Uses of Rare Earth Elements Found in Marine Minerals","https://www.usgs.gov/media/images/potential-uses-rare-earth-elements-found-marine-minerals","Terbium green phosphors and lutetium PET detector materials.");
 source("lnErFiber","NIST","Symposium on Optical Fiber Measurements, 1990","https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication792.pdf","Erbium-doped fiber amplification around 1.55 micrometers.");
 const progression=L(
  'These atoms belong in the sixth row, between barium and hafnium. The separate row saves space. Lanthanum starts with a 5d electron; cerium adds 4f too. More 4f electrons appear through europium; gadolinium also has 5d.',
  'Lanthanides belong in Period 6 between barium and hafnium. The detached row saves space in the same table. Added electrons mainly fill inner 4f: La has 5d; Ce has 4f and 5d; Pr through Eu build up 4f; Gd keeps seven 4f electrons and adds 5d. Similar outer arrangements give related chemistry, while inner electrons affect magnets and light.',
  'The detached lanthanides belong in Period 6 between Ba and Hf; the layout saves space. Their differentiating electrons mainly enter inner 4f, close in energy to 5d and 6s: La 5d¹; Ce 4f¹5d¹; Pr–Eu 4f³–⁷; Gd 4f⁷5d¹, all with 6s². Eu reaches half-filled 4f⁷, which Gd retains. Similar outer arrangements help explain related chemistry, but differing 4f occupancy gives distinct magnetic, optical and electronic properties.');
 const lateProgression=L('From terbium to ytterbium, an inner electron group fills from nine to fourteen. Lutetium keeps that group full and adds an electron to another nearby group.','The 4f subshell is an inner group with room for fourteen electrons. Tb, Dy, Ho, Er and Tm have nine through thirteen; Yb reaches fourteen. Lu keeps 4f full and adds one 5d electron.','Across Tb–Yb, 4f fills in order: Tb 4f⁹, Dy 4f¹⁰, Ho 4f¹¹, Er 4f¹², Tm 4f¹³ and Yb 4f¹⁴. Lu retains 4f¹⁴ and adds 5d¹; all have outer 6s². The outermost pair is not the whole bonding picture. These elements finish the detached Period 6 row between Ba and Hf.');
 const rows=[
  {z:57,name:'Lanthanum',symbol:'La',f:0,d:1,mass:139,natural:[[138,.08881,.00071],[139,99.91119,.00071]],extra:[],
   descriptions:L('Lanthanum is a silvery metal. It is the first element in this lanthanide row. Its selected atom has no 4f electrons.','Lanthanum begins this lanthanide series. Its atom has one 5d electron and two outer 6s electrons. It has no occupied 4f subshell in this model.','Lanthanum uses the measured [Xe] 5d¹ 6s² ground state. Its 5d and 6s electrons help explain bonding. It belongs to the lanthanide series even though this neutral atom has no 4f electron.'),
   engineering:L('Lanthanum materials help make camera glass and rechargeable batteries. Some help chemical reactions.','Lanthanum oxide improves optical glass. Lanthanum alloys are used in battery electrodes, and compounds help oil-refining catalysts.','Lanthanum-containing optical glass, catalysts and metal-hydride battery electrodes have distinct material roles. These applications use compounds or alloys, rather than pure lanthanum alone.')},
  {z:58,name:'Cerium',symbol:'Ce',f:1,d:1,mass:140,natural:[[136,.185,.002],[138,.251,.002],[140,88.450,.051],[142,11.114,.051]],extra:[],
   descriptions:L('Cerium is a silvery metal. Its atom has an electron in both 4f and 5d. Cerium compounds help polish glass and clean exhaust gases.','Cerium starts 4f filling while keeping one 5d electron. Cerium oxide can take up and release oxygen. This helps catalytic converters work.','Cerium uses [Xe] 4f¹ 5d¹ 6s². Cerium compounds can switch between +3 and +4 oxidation states, which describe electron loss in bonding. This helps explain oxygen exchange in cerium oxide.'),
   engineering:L('Cerium oxide polishes glass. Cerium alloys make sparks in lighter flints.','Cerium oxide supports glass polishing and catalytic converters. Cerium-containing alloys are used in lighter flints.','Cerium oxide can store and release oxygen in catalytic converters. It is also used to polish glass. Cerium alloys provide the sparks in lighter flints.')},
  {z:59,name:'Praseodymium',symbol:'Pr',f:3,d:0,mass:141,natural:[[141,100,0]],extra:[144],
   descriptions:L('Praseodymium is a metal used in magnets and colored glass. Its atom has three 4f electrons.','Praseodymium has three 4f electrons and two outer 6s electrons. Its compounds can color glass and ceramics.','Praseodymium uses [Xe] 4f³ 6s². Its 4f electrons contribute to magnetic and optical behavior. No 5d subshell is occupied in this neutral configuration.'),
   engineering:L('Praseodymium helps make strong magnets. It also colors glass and strengthens some aircraft alloys.','Praseodymium alloys support permanent magnets and lightweight aircraft-engine parts. Its compounds color glass and ceramics.','Praseodymium contributes to permanent magnets and magnesium aircraft alloys. Its compounds provide glass and ceramic colors and help specialized optical glass filter light.')},
  {z:60,name:'Neodymium',symbol:'Nd',f:4,d:0,mass:142,natural:[[142,27.152,.040],[143,12.174,.026],[144,23.798,.019],[145,8.293,.012],[146,17.189,.032],[148,5.756,.021],[150,5.638,.028]],extra:[],
   descriptions:L('Neodymium helps make powerful magnets. Its atom has four 4f electrons. These materials are useful in motors and speakers.','Neodymium has four 4f electrons and two outer 6s electrons. Neodymium-iron-boron alloys make strong permanent magnets.','Neodymium uses [Xe] 4f⁴ 6s². Its electrons contribute to magnetic behavior in neodymium-containing materials. A single atom is not a working permanent magnet.'),
   engineering:L('Neodymium magnets help motors turn and speakers make sound. They are also used in generators.','Neodymium-iron-boron magnets help motors turn electrical energy into motion. In generators, motion and magnetic fields help produce electric current. Neodymium materials also support speakers and lasers.','Strong neodymium-iron-boron magnets support compact motors, speakers and generators. Motors convert electrical energy into motion; generators convert motion into electrical energy. The magnet supplies a field, not free energy. Neodymium ions in suitable materials also produce laser light.')},
  {z:61,name:'Promethium',symbol:'Pm',f:5,d:0,mass:145,natural:[],extra:[145,147],
   descriptions:L('Promethium is a rare radioactive metal. It has no stable isotopes. Its atom has five 4f electrons.','Promethium has five 4f electrons and two outer 6s electrons. All its isotopes are radioactive. Only tiny natural traces occur.','Promethium uses [Xe] 4f⁵ 6s². All isotopes are radioactive, with only tiny natural traces supplied by nuclear processes. Useful quantities are produced for specialized work.'),
   engineering:L('Scientists study promethium. It has also been used in special measuring devices and small nuclear batteries.','Promethium-147 supports research and thickness gauges. Luminous paints are a historical use. Specialized nuclear batteries have used its radiation.','Pm-147 has been used in thickness gauges, research and specialized nuclear batteries. Luminous materials are mainly a historical or limited application. These radioactive devices are distinct from ordinary rechargeable batteries.')},
  {z:62,name:'Samarium',symbol:'Sm',f:6,d:0,mass:152,natural:[[144,3.08,.04],[147,15,.14],[148,11.25,.09],[149,13.82,.10],[150,7.37,.09],[152,26.74,.09],[154,22.74,.14]],extra:[],
   descriptions:L('Samarium is a metal used in strong magnets. Its atom has six 4f electrons. Some of its isotopes change extremely slowly.','Samarium has six 4f electrons and two outer 6s electrons. Samarium-cobalt magnets can remain useful at high temperatures.','Samarium uses [Xe] 4f⁶ 6s². Its magnetic properties support samarium-cobalt alloys. Its isotopes also matter in neutron absorption and geological dating.'),
   engineering:L('Samarium-cobalt magnets work well in hot equipment. Some samarium isotopes help scientists study rocks or capture neutrons.','Samarium-cobalt magnets support motors and sensors that must work in heat. Samarium isotopes also help with neutron absorption and dating rocks.','Samarium-cobalt magnets are useful in high-temperature motors and sensors. Sm-149 strongly absorbs thermal neutrons, while Sm-147 decay supports samarium-neodymium dating. These isotope roles differ from the alloy’s magnetic role.')},
  {z:63,name:'Europium',symbol:'Eu',f:7,d:0,mass:153,natural:[[151,47.81,.06],[153,52.19,.06]],extra:[152],
   descriptions:L('Europium materials help make red and blue light. Its atom has seven 4f electrons. That is half of the space available in 4f.','Europium reaches a half-filled 4f subshell with seven electrons. Its compounds can give off colored light in displays and lamps.','Europium uses [Xe] 4f⁷ 6s². Its half-filled 4f subshell contributes to magnetic and optical behavior. Europium compounds have different properties depending on how they are bonded.'),
   engineering:L('Europium helps glowing materials make colors. It also helps reveal counterfeit banknotes.','Europium phosphors are materials that give off light. They provide red or blue colors in displays, LEDs and other lighting. Some security marks also use europium.','Europium-containing phosphors support displays, LEDs and optical materials. Different compounds and europium charge states produce different colors. Their light emission also supports anti-counterfeiting features.')},
  {z:64,name:'Gadolinium',symbol:'Gd',f:7,d:1,mass:158,natural:[[152,.204,.002],[154,2.187,.009],[155,14.828,.060],[156,20.493,.022],[157,15.657,.017],[158,24.820,.020],[160,21.811,.028]],extra:[153],
   descriptions:L('Gadolinium is a metal with useful magnetic properties. Its atom has seven 4f electrons and one 5d electron. Some gadolinium compounds help medical scans.','Gadolinium keeps seven 4f electrons and also has one 5d electron. Its outer 6s subshell holds two electrons. Gadolinium-containing compounds can improve some MRI images.','Gadolinium uses [Xe] 4f⁷ 5d¹ 6s². Its magnetic behavior supports specialized materials. MRI contrast agents contain chemically bound gadolinium, not pieces of gadolinium metal.'),
   engineering:L('Gadolinium compounds help some MRI scans show more detail. Its materials also help researchers study magnets and neutrons.','Gadolinium-containing contrast drugs are used in some MRI exams. Gadolinium also supports neutron capture, magnetic materials, and data-storage and sensor research.','Gadolinium contrast compounds alter the response of nearby water in MRI. This is distinct from Gd-153 radiation-source applications. Gadolinium materials also support neutron capture and research on magnetic sensors and data storage.')}
,
  {z:65,name:'Terbium',symbol:'Tb',f:9,d:0,mass:159,natural:[[159,100,0]],extra:[161],
   descriptions:L('Terbium (Tb) is a silvery metal. Some terbium compounds help make green light.','Terbium is lanthanide number 65, with 65 electrons in six shells. Its compounds can emit green light, and natural terbium is almost entirely Tb-159.','Terbium has the neutral configuration [Xe] 4f⁹ 6s². Its 4f group holds nine electrons as this inner group fills. The two 6s electrons are outermost, but 4f also affects its properties. Terbium-containing solids can emit green light or respond to magnetic fields. These atomic pictures are simplified models.'),
   engineering:L('Some terbium compounds glow green. Special metal mixtures containing terbium change shape in a magnetic field.','Terbium phosphors are materials that give off light. Terbium also helps specialized magnets and alloys that change length in a magnetic field.','Green-emitting terbium compounds are used in lighting materials. Terbium can also help specialized permanent magnets. Terbium-dysprosium-iron alloys change length in a magnetic field, an effect called magnetostriction. These are properties of engineered materials, not a lone atom.')},
  {z:66,name:'Dysprosium',symbol:'Dy',f:10,d:0,mass:164,natural:[[156,.056,.003],[158,.095,.003],[160,2.329,.018],[161,18.889,.042],[162,25.475,.036],[163,24.896,.042],[164,28.260,.054]],extra:[],
   descriptions:L('Dysprosium (Dy) is a silvery metal. It helps some strong magnets keep working when hot.','Dysprosium is lanthanide number 66, with 66 electrons in six shells. It is added to some magnets used in motors and generators.','Dysprosium has the neutral configuration [Xe] 4f¹⁰ 6s². Ten electrons occupy its inner 4f group. The outermost 6s pair is only part of the picture; 4f electrons also affect magnetic behavior. Adding dysprosium can help some magnet alloys resist losing their magnetism in heat. The atom shown is a simplified model.'),
   engineering:L('Dysprosium helps some magnets work in hot motors. Those magnets are made from mixtures of metals.','Some neodymium-based magnets include dysprosium. It helps them resist losing magnetism at high temperatures in motors or generators.','Dysprosium additions help some neodymium-based magnets resist demagnetization, or loss of magnetism, at high temperatures. This is useful in certain motor and generator designs. The effect depends on the alloy and its structure.')},
  {z:67,name:'Holmium',symbol:'Ho',f:11,d:0,mass:165,natural:[[165,100,0]],extra:[166],
   descriptions:L('Holmium (Ho) is a silvery metal. Holmium-containing crystals help make special lasers.','Holmium is lanthanide number 67, with 67 electrons in six shells. Its materials have strong magnetic behavior and are used in specialized lasers. Natural holmium is almost entirely Ho-165.','Holmium has the neutral configuration [Xe] 4f¹¹ 6s². Eleven electrons occupy 4f, contributing to strong magnetic behavior. Its two outermost 6s electrons do not tell the whole bonding story. Holmium-containing laser materials have specialized medical uses. These pictures simplify the atom and do not simulate a laser.'),
   engineering:L('Holmium helps special lasers make light. Some doctors use these laser devices to break up kidney stones.','Holmium is added to certain laser crystals. Engineered medical lasers can use this light to break kidney stones; holmium alloys also have magnetic uses.','Holmium-containing laser crystals support surgical laser devices, including those used to break kidney stones. This use is separate from radioactive Ho-166 treatment research. Strong magnetic behavior also makes holmium useful in specialized magnetic materials.')},
  {z:68,name:'Erbium',symbol:'Er',f:12,d:0,mass:166,natural:[[162,.139,.005],[164,1.601,.003],[166,33.503,.036],[167,22.869,.009],[168,26.978,.018],[170,14.910,.036]],extra:[],
   descriptions:L('Erbium (Er) is a silvery metal. Erbium in glass helps light signals travel through communication cables.','Erbium is lanthanide number 68, with 68 electrons in six shells. Adding it to glass fibers helps boost the light signals that carry information.','Erbium has the neutral configuration [Xe] 4f¹² 6s². Its inner 4f group now holds twelve electrons. The 6s pair is outermost, while inner states also matter for light emission and chemical behavior. Erbium in engineered glass can amplify communication signals. This display is a simplified atom, not a working optical amplifier.'),
   engineering:L('Erbium-containing glass can strengthen light signals. This helps carry messages through glass fibers.','Erbium added to optical fibers helps amplify infrared light, which is invisible to our eyes. Erbium-containing materials also support specialized lasers.','Erbium-containing fiber amplifiers strengthen light near 1.55 micrometers, a wavelength useful for communication. A micrometer is one millionth of a meter. Erbium also supports specialized lasers. These effects require suitable host materials and an energy supply.')},
  {z:69,name:'Thulium',symbol:'Tm',f:13,d:0,mass:169,natural:[[169,100,0]],extra:[170],
   descriptions:L('Thulium (Tm) is an uncommon silvery metal. It helps make specialized lasers.','Thulium is lanthanide number 69, with 69 electrons in six shells. Thulium-containing materials are used in specialized lasers. Natural thulium is almost entirely Tm-169.','Thulium has the neutral configuration [Xe] 4f¹³ 6s². Its 4f group is one electron short of full. The two outermost 6s electrons are not the only states relevant to its properties. Thulium-containing materials support specialized lasers, while produced Tm-170 has radiation-source uses. All three views simplify the atom.'),
   engineering:L('Thulium-containing materials help lasers make light. A radioactive kind of thulium has been used in special imaging equipment.','Thulium-containing laser materials have surgical uses. Produced Tm-170 has been used in compact radiation sources for imaging.','Thulium-containing materials support specialized surgical lasers. Separately, radioactive Tm-170 has been used in portable radiography sources, which use radiation to form images. These controlled source applications are not properties of stable Tm-169 or ordinary metal.')},
  {z:70,name:'Ytterbium',symbol:'Yb',f:14,d:0,mass:174,natural:[[168,.126,.001],[170,3.023,.002],[171,14.216,.007],[172,21.754,.010],[173,16.098,.009],[174,31.896,.026],[176,12.887,.030]],extra:[],
   descriptions:L('Ytterbium (Yb) is a silvery metal. Scientists use ytterbium atoms in extremely precise clocks.','Ytterbium is lanthanide number 70, with 70 electrons in six shells. It fills the inner electron group called 4f. Ytterbium is used in precision clocks and laser materials.','Ytterbium has the neutral configuration [Xe] 4f¹⁴ 6s². Its 4f group is full with fourteen electrons. The outermost 6s pair helps with bonding, while the filled inner group also shapes its properties. Ytterbium is useful in precision clocks and engineered laser materials. The displayed clouds are simplified summaries.'),
   engineering:L('Scientists use ytterbium atoms to keep very precise time. Ytterbium-containing materials also help lasers work.','Precision clocks compare very steady light frequencies with transitions in ytterbium atoms. Ytterbium-containing materials are also used in lasers.','NIST studies Yb-171 atoms in optical lattice clocks, where light holds atoms for precise frequency measurements. Ytterbium-containing host materials also support lasers. The clock uses controlled atoms; the laser needs an engineered material and supplied energy.')},
  {z:71,name:'Lutetium',symbol:'Lu',f:14,d:1,mass:175,natural:[[175,97.414,.005],[176,2.586,.005]],extra:[177],
   descriptions:L('Lutetium (Lu) is a silvery metal at the end of the lanthanide row. Some lutetium compounds help medical scanners detect radiation.','Lutetium is lanthanide number 71, with 71 electrons in six shells. It keeps a full 4f group and adds an electron to the nearby 5d group. Its compounds have detector and specialized medical uses.','Lutetium has the neutral configuration [Xe] 4f¹⁴ 5d¹ 6s². Its 4f group stays full, and the added electron occupies 5d. The two 6s electrons are outermost, but 5d also matters for bonding. Lutetium compounds are used in radiation detectors, and Lu-177 is used in targeted cancer medicines. The model does not simulate these devices or treatments.'),
   engineering:L('Some lutetium crystals help medical scanners detect radiation. Special medicines use radioactive Lu-177 to treat certain cancers.','Lutetium-containing detector crystals give off light when radiation deposits energy in them. Medicines containing Lu-177 deliver radiation to selected cancer cells under specialist care.','Lutetium-containing crystals are used in PET scanners to convert deposited radiation energy into light. Approved Lu-177 medicines attach the isotope to molecules that target certain tumors. This is controlled medical use of a radioactive compound, not safe handling of loose lutetium.')}
 ];
 const detail={
  'Tb-161':{half:[6.906,'days','About 6.9 days'],modes:['Beta-minus (β−) to dysprosium-161'],keys:['lnTbTrial'],uses:L('Scientists study terbium-161 in cancer-treatment research.','Produced Tb-161 is being studied in targeted cancer medicines and clinical trials. It requires specialist radiation handling.','Tb-161 is under study in targeted cancer treatments, including clinical trials. This experimental use is distinct from established Lu-177 medicines. Useful quantities are produced artificially.')},
  'Ho-166':{half:[26.83,'hours','About 26.8 hours'],modes:['Beta-minus (β−) to erbium-166'],keys:['lnHoResearch'],uses:L('Holmium-166 is radioactive. Scientists use it in specialized medical studies.','Produced Ho-166 is used in specialized radiation-treatment work. It is different from stable holmium used in laser materials.','Ho-166 has been studied in radioactive compounds and microspheres for targeted treatment. Handling requires specialist controls. This ground state is different from the long-lived nuclear isomer Ho-166m.')},
  'Tm-170':{half:[128.6,'days','About 129 days'],modes:['Mainly beta-minus (β−) to ytterbium-170','Rare electron capture to erbium-170'],uses:L('Thulium-170 is radioactive. It has been used in special radiation sources.','Produced Tm-170 has been used in compact sources for radiography, which makes images using radiation.','Tm-170 has specialized radiation-source uses, distinct from stable Tm-169 laser materials. Its main decay is beta-minus; a small electron-capture branch also occurs. These sources require radiation controls.')},
  'Lu-176':{half:[3.57e10,'years','About 36 billion years'],modes:['Beta-minus (β−) to hafnium-176'],keys:['lnLu176'],minor:['This display uses the CIAAW lutetium page value of 3.57(14) × 10¹⁰ years. Published evaluations differ; this is a named reference value, not a claim of universal agreement.'],uses:L('Lutetium-176 occurs naturally and changes very slowly. It helps scientists study old rocks.','Natural Lu-176 is radioactive even though it lasts billions of years. Its change to hafnium-176 helps scientists date rocks.','Lu-176 is a naturally radioactive part of terrestrial lutetium. Comparing lutetium and hafnium isotope amounts helps date geological materials. Natural occurrence does not mean stability.')},
  'Lu-177':{half:[6.647,'days','About 6.65 days'],modes:['Beta-minus (β−) to hafnium-177'],keys:['lnLuTherapy'],uses:L('Special medicines use lutetium-177 to treat certain cancers. Only trained medical teams handle these radioactive medicines.','Produced Lu-177 is attached to molecules that target certain tumors. Its radiation is used in approved treatments under specialist care.','Lu-177 is used in approved targeted radioactive medicines, including lutetium-177 dotatate. The targeting molecule and medical controls matter; this is not treatment with bare metal. No ordinary natural-abundance percentage is assigned.')},
  'Yb-171':{keys:['lnYbClock'],uses:L('Scientists use ytterbium-171 atoms in very precise clocks.','Yb-171 is studied in optical clocks that compare atomic transitions with light frequencies.','NIST optical lattice clocks use controlled Yb-171 atoms for precision frequency measurements. This use depends on a laboratory apparatus, not an ordinary piece of ytterbium.')},
  'La-138':{half:[1.02e11,'years','About 102 billion years'],modes:['Electron capture to barium-138','Beta-minus (β−) to cerium-138'],uses:L('This natural isotope changes extremely slowly.','Lanthanum-138 is a rare natural radioactive isotope. Its decay helps scientists study old materials.','Lanthanum-138 decays by electron capture and beta-minus emission. It contributes to isotope and geochemical research.')},
  'Ce-142':{keys:['lnCeLimits','lnCeAlpha'],uses:L('No radioactive decay has been observed for cerium-142.','Scientists search for very rare cerium-142 decay. A search limit is not a measured half-life.','Cerium-142 is observationally stable here. Double-beta and alpha-decay searches report lower limits, not a confirmed decay lifetime.'),limits:['Possible double-beta and alpha decay have not established an observed lifetime. Stable here means no observed decay.']},
  'Pr-144':{half:[17.28,'minutes','About 17.3 minutes'],modes:['Beta-minus (β−) to neodymium-144'],uses:L('Praseodymium-144 changes quickly. Scientists study its decay.','Praseodymium-144 is studied in nuclear and fission-product decay chains.','Praseodymium-144 forms in the cerium-144 decay chain. It is useful in beta-decay and fission-product research.')},
  'Nd-144':{half:[2.29e15,'years','About 2.29 × 10¹⁵ years'],modes:['Alpha (α) decay to cerium-140'],keys:['lnDating'],uses:L('Neodymium-144 changes extremely slowly. It is part of natural neodymium.','Neodymium-144 is a very long-lived alpha emitter. Its isotope ratios help scientists study rocks.','Natural Nd-144 is radioactive. Ratios involving Nd-143 and Nd-144 help trace geological histories and the samarium-neodymium system.')},
  'Nd-150':{half:[9.34e18,'years','About 9.34 × 10¹⁸ years'],modes:['Two-neutrino double-beta (β−β−) decay to samarium-150'],keys:['lnNd150'],uses:L('Neodymium-150 changes very slowly. Scientists study this rare decay.','Neodymium-150 undergoes double-beta decay. It is important in neutrino research.','The NEMO-3 result measures two-neutrino double-beta decay. Searches for decay without neutrinos are separate and do not supply this measured half-life.')},
  'Pm-145':{half:[17.7,'years','About 17.7 years'],modes:['Mainly electron capture to neodymium-145'],minor:['Very weak alpha decay to praseodymium-141 is listed in the named snapshot.'],uses:L('Promethium-145 lasts longer than many other promethium isotopes. It is still radioactive.','Promethium-145 is a comparatively long-lived promethium isotope. It is used as the reference isotope here.','Promethium-145 is the longest-lived isotope in this set. Its roughly 18-year half-life does not make it stable or give it an ordinary natural abundance.')},
  'Pm-147':{half:[2.6234,'years','About 2.62 years'],modes:['Beta-minus (β−) to samarium-147'],keys:['lnPmUse','lnPmBattery'],uses:L('Promethium-147 has helped power special small batteries and measuring devices.','Promethium-147 is used in research and thickness measurement. Nuclear batteries are a specialized application; glowing paints are mainly historical.','Pm-147 beta sources support research, thickness gauges and specialized battery work. These limited applications require radiation controls and should not be confused with ordinary consumer batteries.')},
  'Sm-147':{half:[1.06e11,'years','About 106 billion years'],modes:['Alpha (α) decay to neodymium-143'],keys:['lnDating'],uses:L('Samarium-147 helps scientists find the ages of rocks.','Samarium-147 changes slowly into neodymium-143. Comparing isotope amounts helps date rocks.','Sm-147 alpha decay to Nd-143 provides the samarium-neodymium geological clock. Isotope ratios help reconstruct rock histories.')},
  'Sm-148':{half:[7e15,'years','About 7 × 10¹⁵ years'],modes:['Alpha (α) decay to neodymium-144'],uses:L('Samarium-148 is naturally radioactive but changes extremely slowly.','Samarium-148 is an extremely long-lived alpha emitter in natural samarium.','Natural Sm-148 undergoes alpha decay. Its very long lifetime is distinct from observational stability.')},
  'Sm-149':{keys:['lnCapture'],uses:L('Samarium-149 is good at capturing neutrons.','Samarium-149 strongly absorbs slow neutrons. It matters in nuclear reactors.','Stable Sm-149 has a large thermal-neutron absorption cross section. Its buildup can affect reactor neutron balance. Capturing a neutron is different from spontaneous decay.')},
  'Eu-151':{half:[4.62e18,'years','About 4.62 × 10¹⁸ years'],modes:['Alpha (α) decay to promethium-147'],keys:['lnEu151'],uses:L('Europium-151 occurs naturally. It changes incredibly slowly.','Europium-151 has observed alpha decay and is radioactive. Older tables may call it stable.','A 2014 measurement established Eu-151 alpha decay to Pm-147. Its natural abundance does not make it stable.')},
  'Eu-152':{half:[13.517,'years','About 13.5 years'],modes:['Electron capture to samarium-152','Beta-minus (β−) to gadolinium-152'],minor:['The electron-capture branch includes a small positron-emission contribution in detailed evaluations.'],keys:['lnEuCalibration'],uses:L('Europium-152 helps scientists check radiation instruments.','Europium-152 sources are used in calibration and research.','Eu-152 provides several useful radiation energies for detector calibration. The ground state here is distinct from europium nuclear isomers.')},
  'Gd-152':{half:[1.08e14,'years','About 108 trillion years'],modes:['Alpha (α) decay to samarium-148'],uses:L('Gadolinium-152 occurs naturally and changes extremely slowly.','Gadolinium-152 is a rare, very long-lived alpha emitter in natural gadolinium.','Natural Gd-152 is radioactive despite its very long lifetime. Its alpha decay produces Sm-148.')},
  'Gd-153':{half:[240.4,'days','About 240 days'],modes:['Electron capture to europium-153'],keys:['lnGd153'],uses:L('Gadolinium-153 helps check some medical imaging equipment.','Gadolinium-153 radiation sources support medical imaging calibration and research.','Gd-153 sources support calibration of medical imaging instruments. This radioactive-source use is different from gadolinium-containing MRI contrast drugs.')},
  'Gd-157':{keys:['lnCapture'],uses:L('Gadolinium-157 captures slow neutrons very effectively.','Gadolinium-157 has exceptionally strong thermal-neutron absorption. This helps neutron-control applications.','Gd-157 has an exceptionally large thermal-neutron capture cross section. The value depends on neutron energy. This property is not radioactive decay.')},
  'Gd-160':{keys:['lnCeLimits'],limits:['Double-beta searches set lower bounds, not an observed half-life.']}
 };
 const core=[['1s',1,'s',2],['2s',2,'s',2],['2p',2,'p',6],['3s',3,'s',2],['3p',3,'p',6],['3d',3,'d',10],['4s',4,'s',2],['4p',4,'p',6],['4d',4,'d',10],['5s',5,'s',2],['5p',5,'p',6]];
 for(const row of rows){
  const {z,name,symbol,f,d,mass}=row,slug=name.toLowerCase(),subs=[...core,...(f?[['4f',4,'f',f]]:[]),...(d?[['5d',5,'d',d]]:[]),['6s',6,'s',2]].map(([id,n,l,occupancy])=>({id,n,l,occupancy})),shells=[2,8,18,18+f,8+d,2],important=subs.filter(s=>['4f','5d','6s'].includes(s.id)).map(s=>s.id),masses=[...row.natural.map(a=>a[0]),...row.extra];
  source('ln'+symbol+'Atomic','NIST','Atomic Data for '+name,'https://physics.nist.gov/PhysRefData/Handbook/Tables/'+slug+'table1.htm','Neutral ground-state '+C.fullConfiguration(subs.slice(11))+'. Only configurations are taken from this older page; abundances use CIAAW 2024.');
  source('ln'+symbol+'Uses','Royal Society of Chemistry',name+': properties and uses','https://periodic-table.rsc.org/element/'+z+'/'+slug,'Element, compound and alloy applications. Nuclear classifications use the separately named sources.');
  const keys=[...(z>=65?['lnLateUses']:[]),...(symbol==='Ho'?['lnHoLaser']:symbol==='Er'?['lnErFiber']:symbol==='Yb'?['lnYbClock']:[]),'lnAbundance','lnDecay','ln'+symbol+'Atomic','ln'+symbol+'Uses',...(symbol==='Nd'?['lnDating','lnMotor']:symbol==='Sm'?['lnDating','lnMagnets','lnSmSensor']:symbol==='Gd'?['lnMRI','lnGdSensor']:symbol==='Eu'?['lnEuLED']:[]),...new Set(masses.flatMap(m=>detail[symbol+'-'+m]?.keys||[]))];
  const outer=L('These two electrons are in the outside 6s group. Other nearby electron groups also affect what this element does.','The two outer 6s electrons help the atom form bonds. '+(f?'Its inner 4f electrons also affect its properties.':'Its 5d electron also matters for bonding.'),'The outer 6s² shell is only part of the bonding picture. '+(f?'Occupied 4f'+(d?' and 5d':'')+' states also affect chemistry, magnetism and light.':'The occupied 5d state also matters; 4f is empty in this configuration.'));
  const inner=L('This electron is inside the outside shell. Some inner groups help explain magnets and colored light.','Inner electrons occupy lower-numbered shells. '+(f?'The developing 4f group can affect magnets and light.':'The occupied 5d group also matters for bonding.'),'An inner electron is below the outer 6s shell. Filled xenon-core states differ from the '+(f?'developing 4f'+(d?' and occupied 5d':''):'occupied 5d')+' states. These inner groups can affect bonding and other properties.');
  const placement=L('The lanthanides belong in row six, between barium and hafnium. Their separate row saves space. Many new electrons enter an inside group called 4f.','The lanthanide row is part of Period 6 between barium and hafnium, placed below to save space. Added electrons mainly fill inner 4f. This is why the series is called inner-transition metals.','Lanthanides occupy Period 6 between barium and hafnium. Their detached row is a space-saving layout. Inner-transition metal refers to developing inner f occupancy; 4f, 5d and 6s have close energies.');
  elements[z]={atomicNumber:z,name,symbol,defaultIsotope:slug+'-'+mass,availableIsotopes:masses.map(m=>slug+'-'+m),neutralElectronCount:z,neutralShells:shells,neutralSubshells:subs,neutralConfiguration:C.fullConfiguration(subs),fullConfiguration:C.fullConfiguration(subs),shorthandConfiguration:'[Xe] '+C.fullConfiguration(subs.slice(11)),lanthanideExplorer:true,exactHeavyParticles:true,groupedCoreElectronCount:54,fullDetail:false,waveResolution:'subshell',conciseOverview:true,descriptions:row.descriptions,context:{title:'Science and Engineering',descriptions:row.engineering},valence:{shells:[6],importantSubshells:important,descriptions:outer,studentNote:outer.high},sources:keys,isotopeSourceKeys:keys,periodProgressionTitle:'Across the Lanthanides',periodProgression:z>=65?lateProgression:progression,configurationNote:placement,lanthanidePlacement:placement,isotopeGuideKeys:['isotope',...(symbol==='Pm'?[]:['stable']),'radioactive','abundance','halfLife','decay','weighted','cosmic'],
   isotopeEducation:{isotope:L('Isotopes have different numbers of neutrons.','All '+slug+' isotopes have '+z+' protons. Their neutron counts can differ.','Neutral isotopes share this electron configuration. Their nuclei differ in neutron count.'),abundance:symbol==='Pm'?L('Promethium has no ordinary natural isotope mixture.','Only tiny, changing natural traces occur. Useful amounts are produced.','Promethium has no stable isotope or ordinary terrestrial abundance percentages. Natural traces depend on nuclear production and decay.'):L('These percentages describe natural material on Earth.','Natural mixtures can include very slowly decaying radioactive isotopes.','CIAAW percentages describe representative terrestrial compositions, with uncertainty. Natural occurrence and stability are different properties.'),weighted:symbol==='Pm'?L('The mass number counts particles in one nucleus.','The displayed 145 names a reference isotope, not an ordinary natural average.','Promethium has a reference isotope mass number rather than a standard weighted terrestrial atomic weight.'):L('Atomic weight averages a natural isotope mixture.','The average gives more weight to common isotopes. It differs from one nucleus’s mass number.','Measured isotope masses and terrestrial proportions determine atomic weight. Integer mass numbers count nucleons, not measured atomic masses.'),decay:L('Radioactive nuclei change by giving off particles or capturing an electron.','Alpha decay gives off two protons and two neutrons together. Beta-minus decay gives off an electron. Electron capture takes an atomic electron into the nucleus.','Alpha decay releases a helium nucleus. Beta-minus decay converts a neutron to a proton; electron capture converts a proton to a neutron. Double-beta decay makes two such beta changes.'),cosmic:L('Nuclear processes make these elements.','Stars and nuclear reactions help make these elements. Earth mixtures are not the same everywhere in space.','Stellar and other nuclear processes produce these nuclei. Isotope ratios vary between environments; terrestrial percentages are not universal cosmic abundances.')},
   education:{concepts:{'valence-electron':outer,'inner-electron':inner},regions:{waveValence:outer,orbitalValence:outer,waveInner:inner,orbitalInner:inner},models:{bohr:L('Six rings show all '+z+' electrons. The rings are a simplified picture, not real tracks.','All '+z+' electrons and all nucleons remain represented. The two outer 6s electrons are highlighted; nearby 4f or 5d groups also matter.','Bohr mode preserves all particles and the shell counts '+shells.join(', ')+'. Outer 6s electrons are highlighted, but the bonding picture also involves nearby states. Fixed tracks and distances are simplified.'),wave:L('Bands show electron groups. The inside core is faint so '+important.join(', ')+' stand out.','Every occupied subshell is available, with exact electron counts. The closed xenon core is faint; '+important.join(', ')+' are emphasized. No electron balls ride these waves.','This conceptual overview preserves all '+subs.length+' occupied subshells. It subdues the closed xenon core and emphasizes '+important.join(', ')+'. The bands are teaching patterns, not calculated wavefunctions.'),quantum:L('The faint inside cloud combines 54 core electrons. The other groups stand out. Choose a subshell to see one example shape.','Overview combines the closed xenon core and emphasizes '+important.join(', ')+'. Explore Subshells shows any occupied state. Cloud dots are not electrons.','The 54-electron xenon core is grouped; '+important.join(', ')+' remain separate. Explore Subshells reports exact occupancy and capacity with one representative orbital shape. These qualitative clouds are not rigid objects or calculated total density.')}}};
  if(z>=65){
   elements[z].education.models={
    bohr:L(name+' has '+z+' electrons around its nucleus. The six circles help us count them; real electrons do not follow fixed tracks.','The six rings count '+name.toLowerCase()+' electrons by shell: '+shells.join(', ')+'. These paths are bookkeeping guides, not real tracks.','All '+z+' electrons and every nucleon are shown. The six shells contain '+shells.join(', ')+' electrons. Highlighted 6s electrons are outermost, while inner groups also matter. Circular paths and distances are simplified.'),
    wave:L(name+' electrons behave like waves. These bands are a simple picture of their allowed patterns.','Electrons in '+name.toLowerCase()+' can occupy only certain allowed states. The bands summarize many occupied states; they are not tiny balls on paths.','These bands summarize the '+subs.length+' occupied states in '+name.toLowerCase()+'. The important '+important.join(', ')+' groups stand out against the inner core. Electron behavior is wave-like, but these patterns are conceptual and not drawn to scale.'),
    quantum:L('The '+name.toLowerCase()+' cloud shows where electrons may be found. It is a simplified picture, not a solid object.','A faint inner cloud summarizes 54 core electrons. Brighter groups highlight '+important.join(' and ')+', and the controls let you inspect each occupied group.','This overview groups 54 inner electrons and emphasizes '+important.join(', ')+'. The cloud summarizes where electrons are more likely to be found, not a fuzzy solid surface. Explore Subshells shows one example shape with the exact group count. It is not a photograph or an exact calculation of this atom.')};
   elements[z].valence.descriptions.elementary='These two electrons are in the outside shell. Other nearby electron groups can also affect bonding.';
   if(f===14)elements[z].education.concepts['inner-electron']=L('This electron belongs to an inside group. The group called 4f is now full.','The inner 4f group is full with fourteen electrons. '+(d?'Lutetium also has one 5d electron.':'The outermost pair is in 6s.'),'The 4f subshell is full with fourteen electrons. '+(d?'The occupied 5d state also matters for bonding.':'The highest occupied shell is 6s, with two electrons.')+' Inner and outer labels describe shell position.');
   if(f===14){elements[z].education.regions.waveInner=elements[z].education.concepts['inner-electron'];elements[z].education.regions.orbitalInner=elements[z].education.concepts['inner-electron'];}
  }
  for(const m of masses){const id=slug+'-'+m,v=detail[symbol+'-'+m]||{},natural=row.natural.find(a=>a[0]===m),stable=!v.half,halfLife=v.half?{value:v.half[0],unit:v.half[1],display:v.half[2]}:null,dominant=natural&&natural[1]===Math.max(...row.natural.map(a=>a[1]));
   const descriptions=L(name+'-'+m+' has '+z+' protons and '+(m-z)+' neutrons. '+(stable?'No radioactive decay has been observed.':'It is radioactive.'),name+'-'+m+' has '+(m-z)+' neutrons. '+(stable?'It is stable in the sense that no decay has been observed.':'Its half-life is '+halfLife.display.toLowerCase()+'.'),name+'-'+m+' contains '+z+' protons and '+(m-z)+' neutrons. '+(stable?'No radioactive decay has been observed.':'Its half-life is '+halfLife.display.toLowerCase()+'.'));
   const uses=v.uses||L((dominant?'This is the most common natural '+slug+' isotope.':'This isotope is part of natural '+slug+'.'),symbol==='Nd'?'Neodymium isotope ratios help scientists study rocks and planetary history.':symbol==='Ce'?'Cerium isotopes support nuclear and geochemical research.':'Ordinary '+slug+' applications usually use its natural isotope mixture.',symbol==='Nd'?'Ratios among neodymium isotopes help trace geological and planetary histories.':symbol==='Ce'?'Cerium isotope ratios support nuclear and geochemical studies. No separate industrial application is assigned to every isotope.':'This isotope contributes to the natural mixture. Most material applications do not separate individual isotopes.');
   isotopes[id]={id,element:name,symbol,elementSymbol:symbol,atomicNumber:z,massNumber:m,protons:z,neutrons:m-z,neutralElectronCount:z,stable,stabilityClassification:stable?'Stable':natural?'Radioactive · extremely long-lived':'Radioactive',common:!!natural,displayName:name+'-'+m,halfLife,decayModes:v.modes||[],primaryDecay:v.modes?.[0]||null,naturalComponent:!!natural,naturalAbundance:natural?{percent:natural[1],uncertaintyPercentagePoints:natural[2],scope:'CIAAW representative terrestrial composition'}:null,abundanceText:natural?'Representative terrestrial abundance: '+natural[1]+'%.'+(!stable?' Natural and radioactive.':''):symbol==='Pm'?'Only tiny natural promethium traces occur. No ordinary isotope percentage is assigned; useful quantities are produced.':'Produced radioactive isotope. No ordinary natural-abundance percentage is assigned.',origin:natural?'Natural terrestrial isotope':'Produced for specialized work',metastableStateLabel:null,excitationStateId:'ground',excitationEnergyKeV:0,groundState:null,nuclearStateDescriptions:null,descriptions,note:descriptions.high,uses:uses.high,usesByLevel:uses,advancedDecayNotes:v.minor||v.limits||[],sources:['lnAbundance','lnDecay','ln'+symbol+'Uses',...(symbol==='Nd'?['lnDating']:[]),...(v.keys||[])]};
  }
 }
 C.isotopeSources=C.deepFreeze({...C.isotopeSources,...sources});C.isotopes=C.deepFreeze({...C.isotopes,...isotopes});C.elements=C.deepFreeze({...C.elements,...elements});
 C.validateLanthanideData=(catalog=elements,nuclides=C.isotopes)=>{const r=C.validatePeriod4Data(catalog,nuclides),expected={57:[139,0,1],58:[140,1,1],59:[141,3,0],60:[142,4,0],61:[145,5,0],62:[152,6,0],63:[153,7,0],64:[158,7,1],65:[159,9,0],66:[164,10,0],67:[165,11,0],68:[166,12,0],69:[169,13,0],70:[174,14,0],71:[175,14,1]};for(const e of Object.values(catalog)){const ex=expected[e.atomicNumber];if(!ex){r.errors.push('Unsupported lanthanide');continue;}const identity=rows.find(r=>r.z===e.atomicNumber);if(e.symbol!==identity.symbol||e.name!==identity.name)r.errors.push('Lanthanide identity mismatch');const [mass,f,d]=ex,sub=[...core,...(f?[['4f',4,'f',f]]:[]),...(d?[['5d',5,'d',d]]:[]),['6s',6,'s',2]].map(([id,n,l,occupancy])=>({id,n,l,occupancy}));if(JSON.stringify(sub)!==JSON.stringify(e.neutralSubshells))r.errors.push(e.symbol+': incorrect occupied configuration');if(nuclides[e.defaultIsotope]?.massNumber!==mass)r.errors.push(e.symbol+': default mismatch');for(const id of e.availableIsotopes){const i=nuclides[id];if(!i)continue;if(e.atomicNumber===61&&(i.stable||i.naturalAbundance))r.errors.push(id+': invalid promethium stability/abundance');if(['lanthanum-138','neodymium-144','neodymium-150','samarium-147','samarium-148','europium-151','gadolinium-152','lutetium-176'].includes(id)&&i.stable)r.errors.push(id+': observed radioactivity required');if(['cerium-142','gadolinium-160'].includes(id)&&!i.stable)r.errors.push(id+': search limit is not observed decay');}}r.ok=!r.errors.length;return r;};
 C.lanthanideValidation=C.validateLanthanideData();C.enabledValidation=C.validateEnabledData();if(!C.lanthanideValidation.ok||!C.enabledValidation.ok)throw Error([...C.lanthanideValidation.errors,...C.enabledValidation.errors].join('; '));
})(window.Copper);
