(function(C){
 'use strict';
 const freeze=o=>{Object.values(o).forEach(v=>{if(v&&typeof v==='object')freeze(v);});return Object.freeze(o);};
 C.quarks=freeze({up:{name:'Up quark',symbol:'u',charge:{numerator:2,denominator:3}},down:{name:'Down quark',symbol:'d',charge:{numerator:-1,denominator:3}}});
 C.nucleons=freeze({proton:{name:'Proton',composition:['up','up','down']},neutron:{name:'Neutron',composition:['up','down','down']}});
 C.nucleonCharge=type=>{const n=C.nucleons[type];if(!n)throw Error('Unknown nucleon type');const numerator=n.composition.reduce((sum,flavor)=>sum+C.quarks[flavor].charge.numerator,0);return {numerator,denominator:3,value:numerator/3};};
 for(const [type,expected] of [['proton',3],['neutron',0]])if(C.nucleonCharge(type).numerator!==expected||C.nucleons[type].composition.length!==3)throw Error('Invalid nucleon composition or charge');
 C.chargeEquation=type=>C.nucleons[type].composition.map((flavor,i)=>flavor==='up'?(i?' + +⅔':'+⅔'):' − ⅓').join('')+' = '+(C.nucleonCharge(type).numerator===0?'0':'+'+C.nucleonCharge(type).value);
 C.internalText={
  proton:{elementary:'A proton is a positive particle in the nucleus. Inside it are two up quarks and one down quark.',middle:'A proton contains two up quarks and one down quark. Their electric charges add to +1.',high:'A proton has two up valence quarks and one down valence quark. Their charges add to +1e. Gluons and the strong interaction bind its active interior together.'},
  neutron:{elementary:'A neutron has no overall electric charge. Inside it are one up quark and two down quarks.',middle:'A neutron contains one up quark and two down quarks. These charged parts add to zero; neutral does not mean empty.',high:'A neutron has one up valence quark and two down valence quarks. Their charges add to zero even though each quark is electrically charged. Neutral does not mean empty.'},
  up:{elementary:'An up quark is one of the tiny parts inside protons and neutrons.',middle:'An up quark is a fundamental particle: it has no known smaller parts. Its electric charge is +⅔.',high:'An up quark is a fundamental particle with charge +⅔e. Protons have two up valence quarks, while neutrons have one.'},
  down:{elementary:'A down quark is another tiny part inside protons and neutrons.',middle:'A down quark is a fundamental particle: it has no known smaller parts. Its electric charge is −⅓.',high:'A down quark is a fundamental particle with charge −⅓e. Protons have one down valence quark, while neutrons have two.'},
  gluon:{elementary:'Gluons help hold quarks together.',middle:'Gluons carry the strong interaction that binds quarks inside protons and neutrons. They also interact with other gluons.',high:'Gluons carry the strong interaction between quarks. They also interact with each other, helping create the changing field inside a proton or neutron.'},
  strong:{elementary:'The strong interaction holds the quarks together. Quarks do not simply come out on their own.',middle:'The strong interaction binds quarks together. Pulling them apart adds energy to the field rather than simply freeing one quark.',high:'Quarks are not normally found alone. As they are pulled apart, energy builds in the strong field instead of allowing a single quark to escape. This is called confinement.'},
  color:{elementary:'Color charge is a name for a special kind of charge. It is not a color we can see.',middle:'Color charge is involved in the strong interaction. It is not ordinary visible color, and this drawing does not assign color charges.',high:'Color charge is a physics name, unrelated to visible color. Gluon interactions can change a quark’s color charge while the nucleon stays color-neutral overall. The drawing’s colors are decorative, not color-charge assignments.'},
  sea:{elementary:'There is more inside than these three quarks. The picture shows only the main parts.',middle:'The three valence quarks identify a proton or neutron. Gluons and other brief activity make its full interior more complex.',high:'The three valence quarks determine whether this is a proton or neutron. The full interior also contains gluons and short-lived quark–antiquark activity. Paired flickers are symbols for this activity, not a literal movie.'},
  mass:{elementary:'Most of its mass comes from the energy holding its inside together.',middle:'Much of the particle’s mass comes from the energy inside it, not just from the quarks themselves.',high:'Most of a proton’s or neutron’s mass comes from the energy of moving quarks and the strong gluon field. The three valence quarks’ individual masses account for only a small part of the total.'},
  charge:{elementary:'Add the quarks’ charges to find the whole particle’s charge.',middle:'Each up quark contributes +⅔ and each down quark contributes −⅓. Add these fractions to find the total electric charge.',high:'The fractions are electric charges in units of e, the size of a proton’s charge. Add the three valence-quark charges to find the nucleon’s net charge.'},
  limits:{elementary:'This is a learning picture, not a photograph. The sizes, colors, and moving shapes are made easier to see.',middle:'The quarks and field are not shown to scale. The colored regions and moving curves are teaching symbols, not actual paths. More activity exists than the picture can show.',high:'Quarks and colored regions are not to scale, and quarks do not follow drawn paths. Gluon activity and paired flickers are simplified; visible colors are not color charge. This is not a numerical simulation of quantum chromodynamics, the theory of the strong interaction.'},
  compare:{elementary:'The proton has one more up quark and one fewer down quark than the neutron. That changes the total charge.',middle:'Comparing the compositions, an up quark in place of a down quark changes the total charge by +1. This table is a comparison, not a way to change a particle by dragging.',high:'Replacing one down entry with an up entry changes the charge sum by +1e. This compares valence compositions; it does not simulate a physical conversion or beta decay.'}
 };
 C.internalExplain=(key,level)=>C.internalText[key][level];
})(window.Copper);
