/* Phase 6G: explicit Xe/Rn cores and the first two columns of Periods 6/7. */
(function(C){
 'use strict';
 const L=(elementary,middle,high)=>({elementary,middle,high}),sources={},elements={},isotopes={};
 const source=(key,organization,title,url,supports)=>{sources[key]={organization,title,url,supports,accessed:'2026-09-12'};return key;};
 source('outerAbundance','CIAAW / IUPAC','Isotopic compositions 2024','https://www.ciaaw.org/isotopic-abundances.htm','Cs-133 100%; Ba-130/132/134/135/136/137/138 percentages and uncertainties. No ordinary Fr or Ra mixture.');
 source('outerDecay','NNDC / Brookhaven','Nuclear Wallet Cards, April 2005','https://www.lnl.infn.it/wp-content/uploads/Nuclear_Wallet_Cards.pdf','Named snapshot: Cs-134 2.0652 y, Cs-137 30.03 y; Ba-133 3841 d, Ba-140 12.752 d; Fr-221 4.9 min, Fr-223 22.00 min; Ra-223 11.43 d, Ra-224 3.6319 d, Ra-226 1600 y, Ra-228 5.75 y. Major and minor decay channels. Old Ba-130 limits and abundance values are not reused.');
 source('outerBa130','Meshik et al. / Washington University','Weak decay of Ba-130 and Ba-132: geochemical measurements','https://profiles.wustl.edu/en/publications/weak-decay-of-sup130supba-and-sup132supba-geochemical-measurement','Primary 2001 measurement of daughter Xe-130 in barite: 2.2(5) × 10^21 y for combined weak-decay modes. Double electron capture is the expected dominant channel. Geochemical evidence does not resolve the individual channels.');
 source('outerSecond','BIPM','The SI second','https://www.bipm.org/en/si-base-units/second','The unperturbed Cs-133 ground-state hyperfine transition frequency is exactly 9,192,631,770 Hz. This clock transition is not radioactive decay.');
 source('outerCs137','US EPA','Radionuclide Basics: Cesium-137','https://www.epa.gov/radiation/radionuclide-basics-cesium-137','Fission product, detector calibration, industrial measurement and environmental radiation context.');
 source('outerBaCalibration','NIST','Radioactivity Standard Reference Material Quality Procedures','https://www.nist.gov/system/files/documents/2022/06/21/Procedure15v600.pdf','Ba-133 reference sources calibrate radioactivity instruments and monitor radiochemical procedures.');
 source('outerRa223','NLM / DailyMed','Xofigo prescribing information','https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a398400e-bd31-41a9-9696-4f7c06569ede','Radium-223 dichloride is an approved treatment for specified prostate cancer with symptomatic bone metastases. Alpha emission; medical use requires specialist radiation protection.');
 source('outerRa224','US National Cancer Institute','Alpha Radiation Emitters Device trial','https://www.cancer.gov/research/participate/clinical-trials-search/v?id=NCI-2022-10859&r=1','Ra-224 implanted sources are investigated in a clinical trial. This example is investigational, not a claim of routine approved treatment.');
 source('outerRaSafety','US EPA','Radioactivity in Antiques','https://www.epa.gov/radtown/radioactivity-antiques','Historical luminous paint exposed workers to radium, which can enter bones and cause serious harm.');
 source('outerRaNature','US EPA','Radionuclide Basics: Radium','https://www.epa.gov/radiation/radionuclide-basics-radium','Natural radioactive radium, decay-series occurrence and environmental significance.');
 source('outerCs134','IAEA','Radiological Characterization of Shut Down Nuclear Reactors, TRS 389','https://www-pub.iaea.org/MTCD/Publications/PDF/TRS389_scr.pdf','Page 23: Cs-134 production by neutron capture on Cs-133.');
 source('outerPhotoelectric','Los Alamos / US DOE OSTI','Performance of cesium telluride photocathodes','https://www.osti.gov/servlets/purl/10180003','Primary measurements of cesium telluride light-sensitive electron sources.');
 source('outerFrResearch','NIST','Lifetime Measurements of the 7p levels of atomic francium','https://www.nist.gov/publications/lifetime-measurements-7p-levels-atomic-francium','Example of atomic francium research; excited-state lifetimes are distinct from nuclear half-lives.');
 const comparison=L('Cesium and francium have one outside electron. Barium and radium have two. Cesium starts Period 6, and francium starts Period 7. Every francium and radium isotope is radioactive.', 'Cesium and francium are Group 1 alkali metals with one outer s electron. Barium and radium are Group 2 alkaline-earth metals with two. Similar outer shells help explain similar group behavior. Cesium begins Period 6; francium begins Period 7. All francium and radium isotopes are radioactive.', 'Group 1 Cs and Fr have one outer s electron; Group 2 Ba and Ra have two. Cs begins Period 6 and Fr begins Period 7; all Fr and Ra isotopes are radioactive. Similar outer configurations contribute to similar chemical behavior. Heavy atoms also have effects from fast electrons and interacting electrons that this model does not calculate.');
 const rows=[
 {z:55,name:'Cesium',symbol:'Cs',n:6,s:1,mass:133,natural:[[133,100,0]],extra:[134,137],
 descriptions:L('Cesium is a soft metal that reacts easily. Its atoms help very accurate clocks keep time.', 'Cesium is a soft, reactive alkali metal. Cesium-133 atoms provide the reference used to define a second. Cesium is also spelled caesium.', 'Cesium is a reactive Group 1 metal with one outer 6s electron. Stable cesium-133 provides the SI time reference. Cesium compounds have different properties from the pure metal.'),
 engineering:L('Atomic clocks use cesium atoms as a steady timing reference. Some cesium materials help instruments detect light.', 'Cesium atomic clocks support time standards and scientific instruments. Cesium materials also help turn light into an electrical signal.', 'Cesium atomic clocks use a precisely defined atomic transition. Cesium compounds and surfaces support specialized electronics and photoelectric devices, which convert light into electrical signals.')},
 {z:56,name:'Barium',symbol:'Ba',n:6,s:2,mass:138,natural:[[130,.11,.01],[132,.10,.01],[134,2.42,.15],[135,6.59,.10],[136,7.85,.24],[137,11.23,.23],[138,71.70,.29]],extra:[133,140],
 descriptions:L('Barium is a metal that reacts easily. It is usually found joined to other elements. Different barium compounds can behave very differently.', 'Barium is a reactive alkaline-earth metal usually found in compounds. Barium sulfate helps some medical X-ray examinations. Many soluble barium compounds are poisonous.', 'Barium is a Group 2 metal with two outer 6s electrons. Barium sulfate is poorly soluble and is used as an X-ray contrast material. Toxicity depends strongly on chemical form and solubility.'),
 engineering:L('Barium compounds help make drilling fluids, glass and electronic parts. Barium sulfate is also used in some medical pictures.', 'Barium sulfate adds weight to drilling fluids and supports X-ray imaging. Other barium compounds help make ceramics, glass and electronics.', 'Barium compounds support drilling fluids, glass and electronic ceramics. Medical barium sulfate is a compound application, not a use of reactive barium metal. Soluble barium compounds present different toxicity risks.')},
 {z:87,name:'Francium',symbol:'Fr',n:7,s:1,mass:223,natural:[],extra:[223,221],
 descriptions:L('Francium is extremely rare. All its isotopes are radioactive and change quickly. Scientists study its atoms.', 'Francium is an extremely rare alkali metal. Tiny amounts form temporarily in natural radioactive decay chains. Short half-lives prevent meaningful industrial use.', 'Francium is a Group 1 metal with one outer 7s electron. All its isotopes are radioactive, and francium-223 has the longest half-life in the source used here. Its rarity and short lifetimes limit it mainly to atomic and nuclear research.'),
 engineering:L('Francium is too rare and short-lived for ordinary products. Scientists use tiny amounts to study atoms.', 'Francium has no significant commercial use. Researchers study its atoms to test ideas about atomic structure and nuclear behavior.', 'Francium is mainly a tool for atomic and nuclear physics research. Its short half-lives and tiny available quantities prevent meaningful industrial applications.')},
 {z:88,name:'Radium',symbol:'Ra',n:7,s:2,mass:226,natural:[],extra:[223,224,226,228],
 descriptions:L('Radium is a radioactive metal. Old glowing paints containing radium seriously harmed workers. Some radium isotopes now have carefully controlled medical uses.', 'Radium is a radioactive alkaline-earth metal. Marie and Pierre Curie discovered it while studying radioactive minerals. Its historical use in luminous paint caused severe radiation exposure.', 'Radium is a Group 2 metal with two outer 7s electrons. All its isotopes are radioactive. Historical luminous paint caused serious occupational harm; modern isotope uses require specialist radiation protection.'),
 engineering:L('Specialists use radium-223 in a treatment for some cancers in bone. Radioactive radium needs strict safety controls.', 'Radium-223 dichloride is used for a specific cancer treatment. Radium-224 is being studied in specialized treatments. These uses require trained teams and radiation protection.', 'Radium-223 dichloride treats specified prostate cancers that have spread to bone. Radium-224 sources are being investigated for localized treatment. These isotope applications differ from historical radium paint and require specialist safety controls.')}
 ];
 const detail={
 'Cs-133':{keys:['outerSecond'],uses:L('Cesium-133 helps define one second. This use does not depend on radioactivity.','Cesium-133 is the only stable natural cesium isotope. Its atomic transition defines the SI second.','The SI second fixes a cesium-133 atomic transition frequency at exactly 9,192,631,770 Hz. This is a transition within the atom, not radioactive decay.')},
 'Cs-134':{keys:['outerCs134'],half:[2.0652,'years','About 2.1 years'],modes:['Mainly beta-minus (β−) to barium-134','Very weak electron capture to xenon-134'],uses:L('Cesium-134 is studied in nuclear materials.','Cesium-134 is associated with nuclear reactors and environmental monitoring.','Cesium-134 in reactor material is produced mainly when cesium-133 captures a neutron. It is often discussed with fission products, but its production differs from direct fission products.')},
 'Cs-137':{half:[30.03,'years','About 30 years'],modes:['Beta-minus (β−) to barium-137, mainly through barium-137m'],keys:['outerCs137'],uses:L('Cesium-137 helps check radiation detectors. Scientists also track it in the environment.','Cesium-137 is a fission product used in calibration and industrial measurement. It also matters in environmental monitoring.','Cesium-137 sources support detector calibration, industrial gauges and research. Its persistence makes it important in environmental monitoring after nuclear releases.')},
 'Ba-130':{half:[2.2e21,'years','About 2.2 × 10²¹ years'],modes:['Double electron capture to xenon-130 (dominant interpretation of geochemical evidence)'],keys:['outerBa130'],uses:L('Barium-130 changes incredibly slowly. It is part of natural barium.','Barium-130 is naturally radioactive with an extremely long half-life. Evidence comes from xenon found in old minerals.','Barium-130 decay is inferred from accumulated xenon-130 in minerals. The named lifetime estimate combines possible weak-decay channels; double electron capture is expected to dominate.')},
 'Ba-133':{half:[3841,'days','About 10.5 years'],modes:['Electron capture to cesium-133'],keys:['outerBaCalibration'],uses:L('Barium-133 helps scientists check measuring equipment.','Barium-133 sources help calibrate radiation detectors.','Barium-133 is used in radiation calibration and research. A known source helps test an instrument’s response.')},
 'Ba-138':{uses:L('Barium-138 is the most common natural barium isotope.','Barium-138 makes up about 72% of natural barium.','Stable barium-138 is the dominant natural isotope, with a representative abundance of 71.70%.')},
 'Ba-140':{half:[12.752,'days','About 12.8 days'],modes:['Beta-minus (β−) to lanthanum-140'],uses:L('Barium-140 is studied in nuclear materials.','Barium-140 is a radioactive product of nuclear fission.','Barium-140 is a fission product studied in nuclear materials. It decays to radioactive lanthanum-140.')},
 'Fr-223':{half:[22,'minutes','About 22 minutes'],modes:['Mainly beta-minus (β−) to radium-223','Very weak alpha (α) decay to astatine-219'],uses:L('Francium-223 exists briefly in natural decay chains. Scientists study it.', 'Francium-223 forms in the actinium-227 decay chain. Its roughly 22-minute half-life is the longest among francium isotopes in the source used here.', 'Francium-223 occurs in tiny temporary amounts in the actinium decay series. It is a reference for atomic and nuclear research, not an industrial material.')},
 'Fr-221':{half:[4.9,'minutes','About 4.9 minutes'],modes:['Mainly alpha (α) decay to astatine-217'],minor:['Very weak beta-minus and carbon-14 cluster channels are listed in the source.'],uses:L('Francium-221 helps scientists study radioactive decay chains.','Francium-221 is a short-lived member of the actinium-225 decay chain.','Francium-221 is studied in actinium-225 decay-chain research. Its short lifetime prevents an ordinary natural abundance or commercial use.')},
 'Ra-223':{half:[11.43,'days','About 11.4 days'],modes:['Mainly alpha (α) decay to radon-219'],keys:['outerRa223'],uses:L('Radium-223 is used in a special treatment for some cancers in bone.','Radium-223 dichloride is used for certain prostate cancers that have spread to bone. Specialists control its radiation carefully.','Radium-223 dichloride is an approved treatment for specified prostate cancer with symptomatic bone metastases. Its alpha radiation is delivered under specialist medical supervision.')},
 'Ra-224':{half:[3.6319,'days','About 3.6 days'],modes:['Mainly alpha (α) decay to radon-220'],keys:['outerRa224'],uses:L('Scientists are studying radium-224 for specialized treatments.','Radium-224 sources are being studied for localized cancer treatment. This is an investigational use.','Radium-224 is investigated in implanted alpha-emitting treatment sources. This example is clinical research, not a claim of routine approved treatment.')},
 'Ra-226':{half:[1600,'years','About 1,600 years'],modes:['Mainly alpha (α) decay to radon-222'],keys:['outerRaSafety','outerRaNature'],uses:L('Radium-226 lasts much longer than francium. It was used in harmful old glowing paints.','Radium-226 occurs in the uranium-238 decay series. Its long lifetime explains its historical persistence and environmental importance.','Radium-226 is the longest-lived radium isotope in this set. Its historical luminous-paint use caused serious occupational exposure. Its decay produces radon-222.')},
 'Ra-228':{half:[5.75,'years','About 5.8 years'],modes:['Beta-minus (β−) to actinium-228'],keys:['outerRaNature'],uses:L('Radium-228 forms as thorium changes through a decay chain.','Radium-228 belongs to the thorium-232 decay series. Scientists study it in the environment.','Radium-228 occurs in the thorium-232 series. It is important in decay-chain and environmental studies.')}
 };
 const xeCore=[['1s',1,'s',2],['2s',2,'s',2],['2p',2,'p',6],['3s',3,'s',2],['3p',3,'p',6],['3d',3,'d',10],['4s',4,'s',2],['4p',4,'p',6],['4d',4,'d',10],['5s',5,'s',2],['5p',5,'p',6]];
 const rnCore=[...xeCore.slice(0,9),['4f',4,'f',14],...xeCore.slice(9),['5d',5,'d',10],['6s',6,'s',2],['6p',6,'p',6]];
 for(const row of rows){
  const {z,name,symbol,n,s}=row,slug=name.toLowerCase(),heavy=n===7,subs=[...(heavy?rnCore:xeCore),[n+'s',n,'s',s]].map(([id,n,l,occupancy])=>({id,n,l,occupancy})),shells=heavy?[2,8,18,32,18,8,s]:[2,8,18,18,8,s],masses=[...row.natural.map(a=>a[0]),...row.extra];
  const nist=source('outer'+symbol+'NIST','NIST','Atomic Data for '+name,'https://physics.nist.gov/PhysRefData/Handbook/Tables/'+slug+'table1.htm','Neutral ground state '+(heavy?'[Rn] 7s':'[Xe] 6s')+s+', including the complete occupied core.'),rsc=source('outer'+symbol+'RSC','Royal Society of Chemistry',name+': properties and uses','https://periodic-table.rsc.org/element/'+z+'/'+(symbol==='Cs'?'caesium':slug),'Element properties, natural occurrence and applications. Nuclear values use separately named snapshots.');
  const outer=L('This electron is in the outside shell. It helps determine how the atom joins other atoms.','The outer '+n+'s subshell contains '+s+' electron'+(s===1?'':'s')+'. These electrons help explain the element’s group behavior.','The outer '+n+'s'+(s===1?'¹':'²')+' configuration helps determine bonding. A single atom does not demonstrate the electrical behavior of a whole material.');
  const keys=['outerAbundance','outerDecay',nist,rsc,...(symbol==='Cs'?['outerPhotoelectric']:symbol==='Fr'?['outerFrResearch']:[]),...new Set(masses.flatMap(m=>detail[symbol+'-'+m]?.keys||[]))];
  elements[z]={atomicNumber:z,name,symbol,defaultIsotope:slug+'-'+row.mass,availableIsotopes:masses.map(m=>slug+'-'+m),neutralElectronCount:z,neutralShells:shells,neutralSubshells:subs,neutralConfiguration:C.fullConfiguration(subs),fullConfiguration:C.fullConfiguration(subs),shorthandConfiguration:(heavy?'[Rn] ':'[Xe] ')+C.fullConfiguration(subs.slice(-1)),outerSExplorer:true,exactHeavyParticles:heavy,fullDetail:!heavy,waveResolution:'subshell',conciseOverview:true,descriptions:row.descriptions,context:{title:'Science and Engineering',descriptions:row.engineering},valence:{shells:[n],importantSubshells:[n+'s'],descriptions:outer,studentNote:outer.high},sources:keys,isotopeSourceKeys:keys,periodProgressionTitle:'Compare Groups 1 and 2',periodProgression:comparison,isotopeGuideKeys:['isotope',...(!heavy?['stable']:[]),'radioactive','abundance','halfLife','decay','weighted','cosmic'],
  isotopeEducation:{decay:L('A radioactive nucleus can give off a particle or capture an electron. This changes the nucleus.','Alpha decay gives off two protons and two neutrons together. Beta-minus decay gives off an electron as a neutron changes into a proton. Electron capture takes an atomic electron into the nucleus.','Alpha decay releases a helium nucleus. Beta-minus decay converts a neutron into a proton and releases an electron. Electron capture converts a proton into a neutron; double electron capture does this twice.'),isotope:L('Isotopes have different numbers of neutrons.','Every isotope of '+slug+' has '+z+' protons. Neutron counts can differ.','Neutral isotopes share this electron configuration but differ in neutron count.'),abundance:heavy?L('Tiny amounts form as other radioactive atoms change. There is no ordinary isotope mixture to chart.','All '+slug+' isotopes are radioactive. Natural amounts depend on the decay chains that produce them.','Natural '+slug+' occurs through radioactive decay chains. Amounts depend on parent nuclei and time, so no ordinary abundance percentages are assigned.'):symbol==='Cs'?L('Natural cesium is made of stable cesium-133.','Cesium-133 accounts for the ordinary natural isotope composition. The produced radioactive isotopes have no ordinary percentage.','CIAAW lists cesium-133 at 100% in its representative terrestrial composition. No ordinary abundance is assigned to Cs-134 or Cs-137.'):L('These percentages describe natural mixtures on Earth.','Natural barium includes a very slowly decaying radioactive isotope. Produced isotopes have no ordinary percentage.','CIAAW terrestrial compositions include uncertainty. Barium-130 is naturally radioactive; no ordinary percentage is assigned to produced Cs-134/137 or Ba-133/140.'),radioactive:L('Radioactive nuclei change and release energy.','A radioactive isotope changes into another nuclear state or element over time.','Radioactivity describes spontaneous nuclear change. It is distinct from chemical reactivity.'),weighted:heavy?L('The number names one isotope, not an ordinary mixture.','The displayed mass number counts protons and neutrons in this isotope.','For these elements a reference mass number is not a weighted natural atomic-mass average.'):L('Atomic weight describes an isotope mixture.','Atomic weight averages the isotope masses using their proportions.','A weighted isotope-mass average differs from one nucleus’s integer mass number.'),cosmic:L('Nuclear processes make elements and change them into others.','Stars and radioactive decay help shape the elements found in nature.','Nuclear processes produce elements, and decay chains supply temporary radioactive daughters. Earth isotope proportions are not universal cosmic ratios.')},
  education:{concepts:{'valence-electron':outer},regions:{waveValence:outer,orbitalValence:outer},models:{bohr:L((heavy?'Seven':'Six')+' rings show the shells. All '+z+' electrons are shown. Real electrons do not follow fixed tracks.','Every electron and nucleon is represented. Shells contain '+shells.join(', ')+'. The fixed tracks are a simplified model.','All '+z+' electrons and all nucleons remain individually represented. Paths and distances are simplified.'),wave:L('Each band represents an electron group. Inner bands are faint, and the outside '+n+'s band is brighter.','All '+subs.length+' occupied subshells have conceptual wave bands. Select one to isolate it. No electron balls ride on the waves.','Every occupied subshell remains selectable. Inner bands are subdued, while '+n+'s is emphasized. These conceptual waves are not calculated atomic wavefunctions.'),quantum:heavy?L('The inner cloud combines many electron groups. The outside '+n+'s group is separate. No electrons are removed from the counts.','Overview combines '+(z-s)+' inner electrons into one faint core region and emphasizes '+n+'s. Explore Subshells shows any occupied group separately. Dots are not individual electrons.','The combined core represents '+(z-s)+' electrons across '+(subs.length-1)+' subshells. The outer '+n+'s state remains separate. Explore Subshells reports exact occupancies using representative shapes.'):L('Clouds show where electrons might be found. All occupied groups are represented.','Overview shows all twelve occupied subshells with a brighter 6s region. Explore Subshells isolates one shape.','All twelve occupied subshells remain in Overview. Inner regions are subdued and 6s is emphasized. These are qualitative detection patterns, not exact electron positions.')}}};
  for(const mass of masses){const id=slug+'-'+mass,v=detail[symbol+'-'+mass]||{},natural=row.natural.find(a=>a[0]===mass),stable=!v.half,halfLife=v.half?{value:v.half[0],unit:v.half[1],display:v.half[2]}:null;
   const descriptions=L(name+'-'+mass+' has '+z+' protons and '+(mass-z)+' neutrons. '+(stable?'No radioactive decay has been observed.':'It is radioactive.'),name+'-'+mass+' has '+(mass-z)+' neutrons. '+(stable?'It is stable.':'Its half-life is '+halfLife.display.toLowerCase()+'.'),name+'-'+mass+' contains '+z+' protons and '+(mass-z)+' neutrons. '+(stable?'No radioactive decay has been observed.':'Its half-life is '+halfLife.display.toLowerCase()+'.'));
   const uses=v.uses||L('This isotope is part of natural barium.','Most uses of barium involve its natural mixture, not one isolated isotope.','This isotope contributes to natural isotope-ratio and atomic-weight studies. No separate industrial use is assigned to every isotope.');
   isotopes[id]={id,element:name,symbol,elementSymbol:symbol,atomicNumber:z,massNumber:mass,protons:z,neutrons:mass-z,neutralElectronCount:z,stable,stabilityClassification:stable?'Stable':natural?'Radioactive · extremely long-lived':'Radioactive',common:!!natural,displayName:name+'-'+mass,halfLife,decayModes:v.modes||[],primaryDecay:v.modes?.[0]||null,naturalComponent:!!natural,naturalAbundance:natural?{percent:natural[1],uncertaintyPercentagePoints:natural[2],scope:'CIAAW representative terrestrial composition'}:null,abundanceText:natural?'Representative terrestrial abundance: '+natural[1]+'%.'+(!stable?' Natural and radioactive.':''):heavy?'Tiny, changing amounts occur in radioactive decay chains. No ordinary natural-abundance percentage is assigned.':'Produced radioactive isotope. No ordinary natural-abundance percentage is assigned.',origin:natural?'Natural terrestrial isotope':heavy?'Radioactive decay-chain product':'Produced radioactive isotope',metastableStateLabel:null,excitationStateId:'ground',excitationEnergyKeV:0,groundState:null,nuclearStateDescriptions:null,descriptions,note:descriptions.high,uses:uses.high,usesByLevel:uses,advancedDecayNotes:v.minor||(symbol==='Ra'&&mass!==228?['Extremely rare carbon-14 cluster decay is also listed in the source.']:[]),sources:['outerAbundance','outerDecay',rsc,...(v.keys||[])]};
  }
 }
 C.isotopeSources=C.deepFreeze({...C.isotopeSources,...sources});C.isotopes=C.deepFreeze({...C.isotopes,...isotopes});C.elements=C.deepFreeze({...C.elements,...elements});
 C.validateOuterSData=(catalog=elements,nuclides=C.isotopes)=>{const r=C.validatePeriod4Data(catalog,nuclides),expected={55:[133,6,1],56:[138,6,2],87:[223,7,1],88:[226,7,2]};for(const e of Object.values(catalog)){const [mass,n,s]=expected[e.atomicNumber]||[],core=n===7?rnCore:xeCore,subs=[...core,[n+'s',n,'s',s]].map(([id,n,l,occupancy])=>({id,n,l,occupancy}));if(JSON.stringify(subs)!==JSON.stringify(e.neutralSubshells))r.errors.push(e.symbol+': incomplete core or incorrect outer s configuration');if(nuclides[e.defaultIsotope]?.massNumber!==mass)r.errors.push(e.symbol+': default mismatch');for(const id of e.availableIsotopes){const i=nuclides[id];if(!i)continue;if(n===7&&(i.stable||i.naturalAbundance))r.errors.push(id+': no stable isotope or ordinary abundance allowed');}}r.ok=!r.errors.length;return r;};
 C.outerSValidation=C.validateOuterSData();C.enabledValidation=C.validateEnabledData();if(!C.outerSValidation.ok||!C.enabledValidation.ok)throw Error([...C.outerSValidation.errors,...C.enabledValidation.errors].join('; '));
})(window.Copper);
