/* Phase 6B: neutral Period 3 records. All numbers are data, never renderer state. */
(function(C){
 'use strict';
 const L=(elementary,middle,high)=>({elementary,middle,high}),sources={},elements={},isotopes={};
 const source=(key,organization,title,url,supports)=>{sources[key]={organization,title,url,supports,accessed:'2026-09-09'};return key;};
 source('p3NaHalf','NIST','Corrigendum: Update of NIST half-life results','https://pmc.ncbi.nlm.nih.gov/articles/PMC7668314/','Na-22: 950.4 +/- 0.4 days (rounded here to 2.60 years); Na-24: 14.951 +/- 0.003 hours (display 15 hours).');
 source('p3Na22','DOE / NIDC','Isotope Availability September 2020','https://isotopes.gov/node/728','Na-22 imaging-related applications. Educational copy describes equipment research, not routine patient injection.');
 source('p3Calibration','NIST / NBS','Radioactivity calibration standards','https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nbsspecialpublication331.pdf','Sodium-22 radioactivity calibration standards.');
 source('p3NaDecay','BIPM / DDEP','Monographie BIPM-5, volume 5: Sodium-22','https://www.bipm.org/utils/common/pdf/monographieRI/Monographie_BIPM-5_Tables_Vol5.pdf','Sodium-22 primary positron emission and minor electron capture.');
 source('p3Na24','University of Missouri EHS','Radionuclide data sheet: Sodium-24','https://ehs.missouri.edu/sites/ehs/files/pdf/isotopedata/na-24.pdf','Na-24 beta-minus decay, approximately 15-hour half-life.');
 source('p3Tracer','IAEA','Leak Detection in Heat Exchangers and Underground Pipelines, TCS 38','https://www-pub.iaea.org/MTCD/Publications/PDF/TCS-38_web.pdf','Na-24 compounds as aqueous tracers.');
 source('p3MgNMR','Hebrew University of Jerusalem','Magnesium-25 NMR','https://chem.ch.huji.ac.il/nmr/techniques/1d/row3/mg.html','Mg-25 nuclear spin 5/2 and magnetic resonance spectroscopy.');
 source('p3MgEarth','USGS','Investigation of magnesium isotope fractionation during basalt differentiation','https://www.usgs.gov/publications/investigation-magnesium-isotope-fractionation-during-basalt-differentiation','Magnesium isotope ratios in geological and planetary studies.');
 source('p3AlHalf','BIPM / Decay Data Evaluation Project','Aluminum-26 evaluation report','https://www.bipm.org/documents/d/guest/al-26_report','Recommended half-life 7.17(24) x 10^5 years; primary positron emission plus electron capture to Mg-26.');
 source('p3Early','NASA Astrobiology','Using Isotopes to Probe the Earliest History of the Solar Nebula','https://astrobiology.nasa.gov/news/using-isotopes-to-probe-the-earliest-history-of-the-solar-nebula/','Al-26 decay to Mg-26 in early solar-system meteorite studies.');
 source('p3Galaxy','NASA / GSFC','Aluminum-26 and the Galaxy','https://heasarc.gsfc.nasa.gov/docs/objects/heapow/archive/normal_galaxies/al26_integral_map.html','Galactic Al-26 from evolved and exploding massive stars.');
 source('p3SiEnriched','NIST','Spotlight: Silicon-28 in Quantum Computers','https://www.nist.gov/news-events/news/2020/01/spotlight-silicon-28-quantum-computers','Enriched Si-28 in quantum-device research; isotope enrichment differs from ordinary chemical purity.');
 source('p3SiNMR','NIST','Characterization of Flame Retarded Polymer Combustion Chars by Solid-State 13C and 29Si NMR and EPR','https://www.nist.gov/publications/characterization-flame-retarded-polymer-combustion-chars-solid-state-13c-and-29si-nmr','Si-29 nuclear magnetic resonance in materials research.');
 source('p3Doping','NIST','Atom-based Silicon Quantum Electronics','https://www.nist.gov/programs-projects/atom-based-silicon-quantum-electronics','Phosphorus donors in silicon electronic devices.');
 source('p3PHalf','Princeton University EHS','Phosphorus-32','https://ehs.princeton.edu/laboratory-research/radiation-safety/radioactive-materials/radioisotope-fact-sheets/phosphorus-32','P-32 approximately 14.3 days; beta emission.');
 source('p3Agriculture','IAEA / FAO','IAEA Bulletin 36, number 3, 1994','https://www.iaea.org/sites/default/files/vol36no3.pdf','P-32 tracer studies of fertilizer uptake.');
 source('p3Medicine','National Cancer Institute','Phosphorus P 32','https://www.cancer.gov/publications/dictionaries/cancer-terms/def/phosphorus-p-32','Specialized medical use of radioactive P-32; not a general treatment claim.');
 source('p3SHalf','Princeton University EHS','Sulfur-35','https://ehs.princeton.edu/laboratory-research/radiation-safety/radioactive-materials/radioisotope-fact-sheets/sulfur-35','S-35 approximately 87.6 days, beta emission, labelled biological amino acids.');
 source('p3ClDecay','KAERI / NNDC data','Chlorine-36 nuclear data','https://atom.kaeri.re.kr/cgi-bin/nuclide?nuc=Cl-36','Cl-36 approximately 301000 years; primary beta-minus decay with minor electron capture.');
 source('p3Water','IAEA','Isotope Methods for Dating Old Groundwater','https://www-pub.iaea.org/MTCD/Publications/PDF/Pub1587_web.pdf','Chlorine-36 groundwater dating.');
 source('p3ArDating','Heidelberg University / IAEA symposium','Dating with Atom Trap Trace Analysis of Argon-39','https://conferences.iaea.org/event/49/contributions/9111/','Ar-39 dating with groundwater and ice samples.');
 source('p3ArOcean','DEAP-3600 collaboration','Direct Measurement of the 39Ar Half-life from 3.4 Years of Data','https://arxiv.org/abs/2501.13196','Ar-39 beta decay. A recent measurement reports 302 +/- 8 statistical +/- 6 systematic years; catalog retains the conventional 269-year CIAAW/IAEA value, explicitly labelled conventional.');
 source('p3ArClimate','American Physical Society','What Was the Climate Like 1,000 Years Ago? Ask Argon-39','https://www.aps.org/apsnews/2022/07/argon-39','Ar-39 applications in ocean water, groundwater and ice.');
 source('p3Stars','NASA','Chandra Reveals the Elementary Nature of Cassiopeia A','https://www.nasa.gov/image-article/chandra-reveals-elementary-nature-of-cassiopeia/','Silicon and sulfur production and dispersal in stellar evolution and explosions.');
 source('p3Anode','U.S. Bureau of Reclamation','Corrosion Mitigation of Gates','https://www.usbr.gov/tsc/techreferences/mands/mands-pdfs/Webinar_2014-07_Corrosion%20Mitigation%20of%20Gates.pdf','Magnesium sacrificial anodes for corrosion protection.');
 source('p3Battery','DOE','Keeping Tabs on Polysulfides in Batteries','https://www.energy.gov/science/bes/articles/keeping-tabs-polysulfides-batteries','Sulfur battery research; not a claim of universal commercial adoption.');
 // Stable abundance arrays are percentage ranges from CIAAW, not a single recipe.
 // Radioactive rows: mass, null, relevance (three levels), source keys, half-life, modes.
 const rows=[
  {z:11,name:'Sodium',symbol:'Na',mass:23,
   overview:L('Sodium is a very reactive metal. It is found in salt and other compounds. Sodium metal is very different from table salt.','Sodium is an alkali metal found naturally in compounds such as sodium chloride. Sodium ions help nerves send signals. The pure metal is highly reactive.','Sodium is an alkali metal usually encountered in compounds. Sodium chloride and metallic sodium have very different properties. Sodium ions are important in nerve signals and fluid balance.'),
   engineering:L('Sodium vapor makes the yellow light in some street lamps.','Sodium-vapor lamps produce yellow light. Sodium compounds also supply raw materials for chemical manufacturing.','Sodium-vapor lighting uses excited sodium atoms to produce yellow light. Sodium compounds have separate chemical and biological uses.'),
   behavior:L('It often loses its one outer electron when making compounds.','Sodium often loses one electron to form a positive ion in compounds.','Sodium often loses its 3s electron in compounds, forming a +1 ion.'),
   isotopes:[[23,[100,100],L('This is the stable form in ordinary sodium.','Sodium-23 is the only stable sodium isotope found naturally.','Sodium-23 accounts for ordinary natural sodium. Its compounds are used without isotope separation.')],[22,null,L('Sodium-22 helps scientists test radiation detectors.','Sodium-22 is used in calibration and imaging-equipment research.','Sodium-22 is a positron source used in research, detector calibration and imaging-related work.'),['p3NaHalf','p3Na22','p3Calibration','p3NaDecay'],{value:2.60,unit:'years',display:'Approximately 2.60 years'},['Primarily positron emission (β+)','Minor electron capture']],[24,null,L('Sodium-24 helps scientists follow moving liquids.','Sodium-24 compounds have been used as tracers to follow fluid flow.','Sodium-24 has been used as a scientific tracer. Its short half-life limits how long it can be followed.'),['p3NaHalf','p3Na24','p3Tracer'],{value:15,unit:'hours',display:'Approximately 15 hours'},['Beta-minus (β−)']]]},
  {extra:['p3Anode'],z:12,name:'Magnesium',symbol:'Mg',mass:24,
   overview:L('Magnesium is a lightweight metal found in minerals and seawater compounds. Living things need magnesium. The metal gives a bright light when it burns.','Magnesium is an alkaline-earth metal found in minerals and seawater as compounds. It helps living cells work. The metal forms lightweight alloys and burns brightly.','Magnesium is an alkaline-earth metal found naturally in compounds. Its alloys reduce the weight of structures. Magnesium ions also support important biological processes.'),
   engineering:L('Magnesium parts can protect other metals from corrosion.','A magnesium sacrificial anode corrodes first, helping protect another metal. Magnesium alloys also make lightweight parts.','Magnesium sacrificial anodes corrode in place of protected metal. Lightweight magnesium alloys are useful in structural components.'),
   behavior:L('It commonly loses two outer electrons in compounds.','Magnesium commonly loses its two outer electrons, forming a +2 ion.','Magnesium commonly loses its two 3s electrons to form a +2 ion.'),
   isotopes:[[24,[78.88,79.05],L('Most natural magnesium is magnesium-24.','Magnesium-24 is the most abundant stable isotope.','Magnesium-24 dominates natural magnesium. Ordinary alloy applications use a mixture of isotopes.')],[25,[9.988,10.034],L('Magnesium-25 helps scientists study materials with magnets.','Magnesium-25 can be studied using nuclear magnetic resonance, a magnetic method for studying atoms in materials.','Magnesium-25 has nuclear spin, a magnetic property that makes it useful in nuclear magnetic resonance spectroscopy.'),['p3MgNMR']],[26,[10.96,11.09],L('Magnesium-26 helps scientists study rocks and meteorites.','Magnesium isotope ratios help reveal the history of rocks and planetary materials.','Magnesium isotope ratios are useful in geology. Some magnesium-26 in meteorites records earlier aluminum-26 decay.'),['p3MgEarth','p3Early']]]},
  {z:13,name:'Aluminium',slug:'aluminum',referenceSlug:'aluminium',symbol:'Al',mass:27,
   overview:L('Aluminum is a lightweight metal made from ores such as bauxite. It is used in cans, vehicles and buildings. It can be recycled.','Aluminum is a lightweight metal obtained from ores. It carries heat and electricity well. A thin oxide layer helps protect its surface.','Aluminum is a lightweight, conductive metal made from aluminum-bearing ores. Its protective oxide layer helps resist corrosion. Recycling supports its use in packaging and structures.'),
   engineering:L('Aluminum wires carry electricity over long distances.','Aluminum combines low weight with good electrical conductivity. This makes it useful in power lines.','Aluminum is used in power-transmission conductors because it combines conductivity with low weight. Its alloys also support structural and thermal applications.'),
   behavior:L('It commonly forms compounds in a +3 state.','Aluminum commonly forms a +3 state in compounds. Its neutral atom has three outer electrons.','Aluminum commonly has a +3 oxidation state in compounds. This describes its bonding; the atom shown here is neutral.'),
   isotopes:[[27,[100,100],L('This is the stable form in ordinary aluminum.','Aluminum-27 is the only stable naturally occurring aluminum isotope.','Aluminum-27 accounts for ordinary aluminum. Structural applications do not normally require isotope separation.')],[26,null,L('Aluminum-26 helps scientists learn about meteorites and stars.','Aluminum-26 is radioactive. It helps researchers study the early solar system and material made by stars.','Aluminum-26 decay leaves magnesium-26 in meteorites. Its radiation also traces recently produced material in our galaxy.'),['p3AlHalf','p3Early','p3Galaxy'],{value:717000,unit:'years',display:'Approximately 717,000 years'},['Primarily positron emission (β+)','Electron capture']]]},
  {z:14,name:'Silicon',symbol:'Si',mass:28,
   overview:L('Silicon is found in sand and many rocks as compounds. Pure silicon is used in computer chips. Glass contains silicon compounds, not just pure silicon.','Silicon is a metalloid common in silicate minerals. Pure silicon is a semiconductor used in chips and solar cells. Silicon compounds are important in glass.','Silicon is a metalloid found widely in silica and silicate minerals. Its semiconductor behavior supports integrated circuits and solar cells. Pure silicon and glass have different properties.'),
   engineering:L('Silicon helps tiny switches in computer chips control electricity.','Silicon transistors act as switches in integrated circuits. Small amounts of other elements help control how electricity moves through silicon.','Silicon is the foundation of many integrated circuits. Adding tiny amounts of dopants controls charge carriers for transistors. Solar cells use silicon to convert light into electrical energy.'),
   behavior:L('It often shares outer electrons with nearby atoms.','Silicon often shares its four outer electrons in covalent bonds.','Silicon commonly shares electrons in covalent structures. Four valence electrons help explain its network of bonds.'),
   isotopes:[[28,[92.191,92.318],L('Most natural silicon is silicon-28. Extra-pure isotope mixtures help some research devices.','Silicon-28 is naturally dominant. Isotopically enriched silicon-28 is used in specialized quantum-device research.','Enriched silicon-28 supports specialized semiconductor research. Ordinary semiconductor-grade purity does not mean isotope enrichment.'),['p3SiEnriched']],[29,[4.645,4.699],L('Silicon-29 helps scientists study how materials are built.','Silicon-29 is useful in nuclear magnetic resonance, a magnetic method for studying materials.','Silicon-29 nuclear magnetic resonance helps identify the local structure of silicon-containing materials.'),['p3SiNMR']],[30,[3.037,3.110],L('Silicon-30 is a less common stable form of silicon.','Silicon-30 is part of the natural mixture. Scientists compare isotope amounts in different materials.','Silicon-30 contributes to isotope-ratio studies and atomic-weight measurements. No ordinary isotope-specific industrial use is implied.')]]},
  {z:15,name:'Phosphorus',symbol:'P',mass:31,
   overview:L('Phosphorus is a reactive nonmetal. It is found in phosphate minerals and living things. Phosphorus compounds are used in fertilizers.','Phosphorus is a reactive nonmetal found naturally in compounds. Phosphates help cells store energy and build DNA. They are important in fertilizers.','Phosphorus is a reactive nonmetal obtained from phosphate minerals. Its compounds are essential in biology and fertilizers. These compounds differ from elemental phosphorus.'),
   engineering:L('Adding a little phosphorus to silicon helps it carry electricity.','Phosphorus is a dopant: a small addition used to change silicon. It can supply extra electrons that carry current.','Phosphorus dopants can donate electrons to silicon. These additional charge carriers help engineers control semiconductor conductivity.'),
   behavior:L('It can share electrons in several kinds of bonds.','Phosphorus has five outer electrons and can form several bonding arrangements.','Phosphorus can form several bonding arrangements. Its five outer electrons are not a rule requiring one fixed charge.'),extra:['p3Doping'],
   isotopes:[[31,[100,100],L('This is the stable form in ordinary phosphorus.','Phosphorus-31 is the only stable phosphorus isotope found naturally.','Phosphorus-31 accounts for ordinary natural phosphorus. Fertilizers contain phosphorus compounds.')],[32,null,L('Phosphorus-32 helps scientists follow phosphorus through plants and living cells.','Phosphorus-32 is a radioactive tracer used in biological and fertilizer research. It also has specialized medical uses.','Phosphorus-32 emits beta-minus radiation. Labelled compounds trace biological processes and fertilizer uptake; selected compounds also have specialized medical uses.'),['p3PHalf','p3Agriculture','p3Medicine'],{value:14.3,unit:'days',display:'Approximately 14.3 days'},['Beta-minus (β−)']]]},
  {extra:['p3Battery'],z:16,name:'Sulfur',symbol:'S',mass:32,
   overview:L('Sulfur is a yellow nonmetal found in deposits and many compounds. Plants and animals need sulfur. Its compounds help make fertilizers.','Sulfur is a nonmetal found in minerals and living things. Sulfuric acid is important in fertilizers and material processing. Elemental sulfur and its compounds have different properties.','Sulfur is a nonmetal found in deposits and sulfur-containing compounds. Sulfuric acid supports fertilizer production and material processing. Sulfur is also essential in biological molecules.'),
   engineering:L('Sulfur helps make rubber stronger and more useful.','Adding sulfur links rubber molecules in vulcanization. Sulfur-containing materials are also studied for batteries.','Vulcanization uses sulfur to link rubber molecules and improve their properties. Sulfur chemistry also supports batteries and industrial processing.'),
   behavior:L('It can make several kinds of bonds.','Sulfur has six outer electrons and several possible bonding arrangements.','Sulfur has six valence electrons. It can form several bonding arrangements, rather than one fixed ion in every compound.'),
   isotopes:[[32,[94.41,95.29],L('Most natural sulfur is sulfur-32.','Sulfur-32 is the dominant stable isotope.','Sulfur-32 dominates the stable natural mixture. Ordinary sulfur applications do not require separated sulfur-32.')],[33,[.729,.797],L('Sulfur-33 helps scientists compare materials.','Stable sulfur isotope ratios help scientists study rocks and natural cycles.','Sulfur-33 contributes to stable-isotope studies of geological, environmental and biological processes.')],[34,[3.96,4.77],L('Sulfur-34 helps scientists follow sulfur in nature.','Sulfur-34 ratios help track sulfur through rocks, water and living things.','Sulfur-34 ratios are useful in geology and environmental science. Biological processes can change sulfur isotope mixtures.')],[36,[.0129,.0187],L('Sulfur-36 is a rare stable form studied by scientists.','Sulfur-36 is rare. It contributes to scientific comparisons of stable isotope mixtures.','Sulfur-36 is useful as part of stable-isotope comparisons. Its role here is scientific, not a claimed industrial use.')],[35,null,L('Sulfur-35 helps scientists follow sulfur in living things.','Sulfur-35 can label amino acids to help researchers follow biological processes.','Sulfur-35 is a beta-minus-emitting tracer used in biological research. It also occurs in traces from cosmic-ray reactions.'),['p3SHalf'],{value:87.6,unit:'days',display:'Approximately 87.6 days'},['Beta-minus (β−)']]]},
  {z:17,name:'Chlorine',symbol:'Cl',mass:35,
   overview:L('Chlorine is found in salt and other compounds. Pure chlorine is a very reactive gas. Chloride in table salt is different from chlorine gas.','Chlorine is a halogen found naturally in chloride compounds. Elemental chlorine is a highly reactive gas. Chloride ions in salt have different properties.','Chlorine is a halogen commonly encountered as chloride in salts. Reactive chlorine gas is different from chloride ions. Chlorine chemistry supports water treatment and manufacturing.'),
   engineering:L('Chlorine compounds help treat water and make some plastics.','Chlorine-based treatment disinfects water. Chlorine is also used to make PVC and other chemicals.','Chlorine chemistry supports water disinfection and PVC manufacturing. The behavior depends on the chemical form, not just the element name.'),
   behavior:L('It often gains or shares one electron in compounds.','Chlorine often gains or shares one electron. It has seven outer electrons before bonding.','Chlorine often gains one electron or shares electrons in bonds. Its neutral atom has seven valence electrons.'),
   isotopes:[[35,[75.5,76.1],L('Most natural chlorine is chlorine-35.','Chlorine-35 is the more common stable isotope in natural chlorine.','Chlorine-35 and chlorine-37 form the stable mixture behind the familiar average atomic weight of about 35.45.')],[37,[23.9,24.5],L('Chlorine-37 is also part of ordinary chlorine.','Chlorine-37 is heavier than chlorine-35. Their mixture helps explain the average atomic weight.','Chlorine-37 contributes to chlorine’s average atomic weight. Natural isotope proportions vary by source.')],[36,null,L('Chlorine-36 helps scientists study old water and rocks.','Chlorine-36 is a radioactive tracer used in groundwater and geological dating.','Chlorine-36 decays mainly by beta-minus emission. Its long half-life makes it useful for studying old groundwater and geological histories.'),['p3ClDecay','p3Water'],{value:301000,unit:'years',display:'Approximately 301,000 years'},['Primarily beta-minus (β−)','Minor electron capture']]]},
  {z:18,name:'Argon',symbol:'Ar',mass:40,
   overview:L('Argon is a gas found in air. It rarely reacts with other materials. It helps protect hot metal during welding.','Argon is a noble gas obtained from air. It is usually chemically unreactive. It provides protective atmospheres in manufacturing.','Argon is a noble gas present in Earth’s atmosphere. Its filled outer shell contributes to low reactivity under ordinary conditions. It is useful in welding, lighting and plasma equipment.'),
   engineering:L('Argon keeps air away from hot metal during welding.','Argon shielding gas helps prevent unwanted reactions during welding. It is also used in lamps and plasma equipment.','Argon provides a protective atmosphere for welding and manufacturing. Electrical discharges in argon are useful in lighting and plasma applications.'),
   behavior:L('Its eight outer electrons help it react very little.','Argon has a filled outer shell in this model. This helps explain why it rarely reacts.','Argon’s 3s² 3p⁶ valence configuration is filled in this simplified model. This contributes to low reactivity.'),
   isotopes:[[36,[0,2.07],L('Argon-36 helps scientists compare gases from different places.','Argon-36 is stable. Its proportion compared with argon-40 varies greatly by source.','Argon-36 is part of stable-isotope comparisons used to study gas sources and geological history.')],[38,[0,4.3],L('Argon-38 is a stable form studied in natural gases.','Argon-38 contributes to scientific studies of isotope mixtures.','Argon-38 is a stable component of natural argon. Its importance here is scientific comparison of gas mixtures.')],[40,[93.6,100],L('Most argon in Earth’s air is argon-40.','Argon-40 dominates Earth’s atmosphere. Much of it was made when potassium-40 decayed.','Much terrestrial argon-40 comes from potassium-40 decay. Its accumulation supports potassium–argon dating; Earth’s atmospheric mixture is not universal.')],[39,null,L('Argon-39 helps scientists find out how old water and ice are.','Argon-39 is a radioactive tracer for groundwater, ocean water and ice.','Argon-39 emits beta-minus radiation. It is used to date or trace groundwater, ocean water and ice.'),['p3ArDating','p3ArOcean','p3ArClimate'],{value:269,unit:'years',display:'Approximately 269 years (conventional reference value)'},['Beta-minus (β−)']]]}
 ];
 for(const row of rows){
  const {z,name,symbol}=row,slug=row.slug||name.toLowerCase(),ref=row.referenceSlug||slug,outer=z-10;
  const ciaaw=source('p3'+symbol+'CIAAW','CIAAW / IUPAC','Atomic Weight of '+name,'https://ciaaw.org/'+ref+'.htm','Stable identities, terrestrial composition ranges and standard atomic weight; natural variation and isotope context.'),rsc=source('p3'+symbol+'RSC','Royal Society of Chemistry',name+': properties and uses','https://periodic-table.rsc.org/element/'+z+'/'+ref,'Ground-state configuration, identity, occurrence, chemistry and applications.');
  const subs=[{id:'1s',n:1,l:'s',occupancy:2},{id:'2s',n:2,l:'s',occupancy:2},{id:'2p',n:2,l:'p',occupancy:6},{id:'3s',n:3,l:'s',occupancy:Math.min(2,outer)},...(outer>2?[{id:'3p',n:3,l:'p',occupancy:outer-2}]:[])];
  const valence=L(...['elementary','middle','high'].map(level=>name+' has '+outer+' valence electron'+(outer===1?'':'s')+' in the third shell. '+row.behavior[level]));
  const cosmic=z===18?L('Earth’s argon mixture is not the same everywhere in space.','Much argon-40 on Earth came from potassium-40 decay. Other places can have different isotope mixtures.','Potassium-40 decay strongly affects terrestrial argon-40. Geological sources and other parts of the solar system need not match Earth’s air.'):z===13?L('Stars make aluminum. Scientists study aluminum-26 to learn about space.','Aluminum-26 helps scientists study meteorites and material made by stars. Earth’s isotope mixture is not universal.','Aluminum-26 links meteorite records to the early solar system. Its radiation also reveals material produced by massive stars in our galaxy.'):L('Stars helped make this element. Its isotope mixture can differ in space.','Nuclear processes in stars and stellar explosions help produce this element. Isotope mixtures on Earth are not universal.','This element is associated with stellar nuclear processes. Silicon and sulfur are important products seen in supernova remains. Earth’s isotope ratios are not a rule for all space.');
  const keySources=[ciaaw,rsc,'p3Stars',...(row.extra||[]),...new Set(row.isotopes.flatMap(i=>i[3]||[]))];
  const config=C.fullConfiguration(subs);
  elements[z]={atomicNumber:z,name,symbol,defaultIsotope:slug+'-'+row.mass,availableIsotopes:row.isotopes.map(i=>slug+'-'+i[0]),neutralElectronCount:z,neutralShells:[2,8,outer],neutralSubshells:subs,neutralConfiguration:config,fullConfiguration:config,shorthandConfiguration:'[Ne] '+C.fullConfiguration(subs.filter(s=>s.n===3)),valence:{shells:[3],importantSubshells:subs.filter(s=>s.n===3).map(s=>s.id),descriptions:valence,studentNote:valence.high},conciseOverview:true,descriptions:row.overview,context:{title:'Engineering Connection',descriptions:row.engineering},waveResolution:'subshell',fullDetail:true,sources:keySources,isotopeSourceKeys:keySources,isotopeGuideKeys:['isotope','stable','radioactive','abundance','halfLife','decay','weighted','cosmic'],
   periodProgression:L('As you move across this row, each atom adds one proton and one electron. The new electrons fill the third shell.','Across Period 3, atomic number increases by one and electrons progressively fill the third energy level. The number of valence electrons helps explain changing chemical behavior.','Across Period 3, electrons fill the 3s and then 3p subshells. This changing outer-electron arrangement helps explain trends in bonding, reactivity and material properties.'),
   isotopeEducation:{isotope:L('Isotopes are versions of '+slug+' with different neutron counts.','Every '+slug+' isotope has '+z+' protons. Its neutron count can change.','Changing isotope changes neutrons, not the element. Neutral '+slug+' retains '+z+' electrons.'),abundance:L('These numbers describe natural material on Earth. Different places can have different mixtures.','The ranges describe variations between natural Earth samples. They are not one fixed mixture. Radioactive traces are excluded.','CIAAW ranges describe normal terrestrial materials, not universal cosmic ratios. Each range varies independently across samples; the endpoints are not one mixture.'),weighted:L('Atomic weight describes a mixture. Mass number counts one atom’s protons and neutrons.','Atomic weight uses isotope masses and proportions. It differs from a single isotope’s mass number.','Standard atomic weight uses measured isotope masses and their proportions. A mass number is a nucleon count, not an average.'),cosmic},
   education:{concepts:{'valence-electron':valence},regions:{waveValence:valence,orbitalValence:valence},models:{bohr:L('Three rings show the occupied shells. Every electron is shown. Real electrons do not follow fixed tracks.','The three shells contain 2, 8 and '+outer+' electrons. The rings are a teaching model, not real electron tracks.','The shell populations are 2, 8 and '+outer+'. Every electron is shown individually. Fixed paths and distances are simplified.'),wave:L('Closed waves show occupied electron states. No electron balls ride on them.','Each occupied subshell has a standing-wave pattern. Outer 3s'+(outer>2?' and 3p':'')+' states are emphasized.','The occupied states are '+config+'. Each band represents a subshell, with its actual electron count shown in the panel. These are teaching patterns, not calculated electron paths.'),quantum:L('Clouds show places where electrons might be found. Dots are not individual electrons.','Overview shows all occupied subshells. Explore Subshells lets you isolate one. Denser cloud regions suggest a greater chance of finding electrons.','The occupied configuration is '+config+'. Each subshell has a qualitative probability region. Transparency keeps overlapping regions and the nucleus visible.')}}};
  for(const [mass,range,uses,extra=[],halfLife=null,decayModes=[]] of row.isotopes){
   const id=slug+'-'+mass,stable=!halfLife,single=range?.[0]===100&&range?.[1]===100,naturalAbundance=range?(single?{percent:100,uncertaintyPercentagePoints:0,scope:'Only stable natural isotope'}:{rangePercent:range,scope:'CIAAW normal terrestrial materials; ranges are not one mixture'}):null;
   const descriptions=L(name+'-'+mass+' has '+z+' protons and '+(mass-z)+' neutrons. '+(stable?'It is stable.':'It changes by radioactive decay.'),name+'-'+mass+' has '+(mass-z)+' neutrons. '+(stable?'No radioactive decay has been observed.':'Its half-life is '+halfLife.display.toLowerCase()+'.'),name+'-'+mass+' contains '+z+' protons and '+(mass-z)+' neutrons. '+(stable?'It is stable.':'Its half-life is '+halfLife.display.toLowerCase()+'.'));
   isotopes[id]={id,symbol,elementSymbol:symbol,atomicNumber:z,massNumber:mass,protons:z,neutrons:mass-z,stable,common:stable,displayName:name+'-'+mass,halfLife,decayModes,primaryDecay:decayModes[0]||null,naturalAbundance,origin:stable?'natural':'trace natural and/or produced',abundanceText:single?'The only stable naturally occurring isotope.':range?'CIAAW terrestrial range: '+range.join('–')+'%. Different samples have different mixtures.':'Occurs as a trace and/or is produced for research. No ordinary stable natural-abundance percentage is assigned.',descriptions,note:descriptions.high,uses:uses.high,usesByLevel:uses,sources:[ciaaw,rsc,...extra]};
  }
 }
 C.isotopeSources=C.deepFreeze({...C.isotopeSources,...sources});C.isotopes=C.deepFreeze({...C.isotopes,...isotopes});C.elements=C.deepFreeze({...C.elements,...elements});
 C.validatePeriod3Data=(catalog=elements,nuclides=C.isotopes)=>{
  const errors=[];
  for(const e of Object.values(catalog)){
   for(const level of ['elementary','middle','high']){
    for(const texts of [e.descriptions,e.context?.descriptions,e.valence?.descriptions,e.periodProgression,...Object.values(e.education?.models||{}),...Object.values(e.isotopeEducation||{})])if(typeof texts?.[level]!=='string'||!texts[level].trim())errors.push(e.symbol+': missing '+level+' explanation');
   }
   if(e.neutralConfiguration!==C.fullConfiguration(e.neutralSubshells))errors.push(e.symbol+': configuration text mismatch');
   for(const id of e.availableIsotopes){const i=nuclides[id],valid=C.validateRecord(e,i);if(!valid.ok){errors.push(valid.error);continue;}
    if(i.elementSymbol!==e.symbol||i.protons!==e.atomicNumber||i.neutrons!==i.massNumber-e.atomicNumber)errors.push(id+': identity mismatch');
    if(!i.stable&&(!(i.halfLife?.value>0)||!i.halfLife?.unit||!i.primaryDecay||i.primaryDecay!==i.decayModes[0]||i.naturalAbundance))errors.push(id+': radioactive fields');
    if(i.stable&&(i.halfLife!==null||!i.naturalAbundance))errors.push(id+': stable fields');
    for(const level of ['elementary','middle','high'])if(!i.descriptions?.[level]||!i.usesByLevel?.[level])errors.push(id+': missing isotope explanation');
    if(!i.abundanceText||!i.sources?.length||i.sources.some(key=>!C.isotopeSources[key]))errors.push(id+': missing abundance or source');
   }
  }
  return {ok:!errors.length,elements:Object.keys(catalog).length,isotopes:Object.values(catalog).reduce((n,e)=>n+e.availableIsotopes.length,0),errors};
 };
 C.period3Validation=C.validatePeriod3Data();C.enabledValidation=C.validateEnabledData();
 if(!C.period3Validation.ok||!C.enabledValidation.ok)throw Error([...C.period3Validation.errors,...C.enabledValidation.errors].join('; '));
})(window.Copper);
