(function(C){
 'use strict';
 const $=id=>document.getElementById(id),records=C.basicElements,tiles=new Map();
 // One navigation store, with the existing explorer state referenced, not copied.
 const state=C.applicationState={page:'table',selectedElement:null,query:'',filters:[],layout:'table',level:'high',color:true,tableScroll:0,pageScroll:0,explorerScroll:0,get explorer(){return C.app?.state||null;},get activeIsotope(){return C.app?.atom.isotope.id||'copper-63';}};
 C.explorerRegistry=Object.fromEntries(records.filter(e=>e.explorerAvailable&&C.elements[e.atomicNumber]).map(e=>[e.symbol,()=>{const app=C.startExplorer(),element=C.elements[e.atomicNumber];if(app.atom.element.symbol!==e.symbol){const result=app.loadAtom({element,isotope:C.isotopes[element.defaultIsotope]});if(!result.ok)throw Error(result.error);}return app;}]));
 const words={
  elementary:{intro:'A periodic table organizes all known elements. Elements in the same column often behave in similar ways.',groups:'Groups are the columns. Elements in one group often behave alike.',periods:'Periods are the rows. Read across a row to find larger atomic numbers.',families:'Families group elements with some similar properties. Colors and labels help you find them.',number:'Atomic number counts the protons in an atom.',weight:'Many elements are mixtures of isotopes. Atomic weight describes their average mass.',representative:'A number in brackets names one isotope. It counts its protons and neutrons, not an average.',available:'Explore this atom, then look inside a proton or an available neutron.',unavailable:'You can learn the basic facts here. This element’s atom model is coming in the next development phase.',description:e=>e.name+' is element '+e.atomicNumber+'. Its symbol is '+e.symbol+'.'},
  middle:{intro:'The periodic table arranges elements by atomic number. Elements in the same group often share chemical properties because of their outer electrons.',groups:'A group is a vertical column. Similar outer-electron arrangements often give its elements similar properties.',periods:'A period is a horizontal row. Atomic numbers increase as you move across it.',families:'Families collect elements with shared properties. Some boundaries depend on the convention used.',number:'Atomic number equals the proton count. It identifies an element.',weight:'A standard atomic weight describes natural terrestrial material. It often averages isotope masses, giving more weight to common isotopes.',representative:'A bracketed number is the mass number of a representative isotope. It is not a weighted average.',available:'The complete explorer includes shells, waves, probability regions and nucleon interiors.',unavailable:'The basic element record is available. Its interactive atom model will be added in the next development phase.',description:e=>e.name+' atoms have '+e.atomicNumber+' protons. The element belongs to period '+e.period+'.'},
  high:{intro:'The periodic table is ordered by increasing atomic number. Repeating electron configurations produce patterns in chemical behavior across periods and within groups.',groups:'Groups are columns numbered 1–18. Similar electron arrangements often produce related chemistry, with important exceptions.',periods:'Periods are rows numbered 1–7. The detached series belong to periods 6 and 7, not additional periods.',families:'Element families summarize chemical patterns. Classification boundaries are conventions; uncertain properties are labeled explicitly.',number:'Atomic number is the number of protons. It stays fixed across an element’s isotopes and ions.',weight:'Standard atomic weights describe normal terrestrial materials. Many are weighted averages of isotope masses. CIAAW’s abridged values retain uncertainty, including natural variation where relevant.',representative:'Where no standard atomic weight is defined, brackets identify a representative isotope mass number from the IUPAC 2022 table. It counts nucleons and is not an average atomic weight.',available:'Explore this element with all three atomic models, isotope selection and available proton/neutron interiors.',unavailable:'Explorer coming soon. The basic record is complete; the interactive model awaits validated atomic data and visualization checks in the next development phase.',description:e=>e.name+' is defined by atomic number '+e.atomicNumber+'. Its conventional placement is period '+e.period+(e.group?', group '+e.group: ', in the detached '+e.family.toLowerCase()+' series')+'.'}
 };
 const occurrence={natural:'Occurs naturally on Earth.', 'natural-trace':'Occurs naturally in small amounts, often in radioactive decay chains.', 'trace-produced':'Mainly produced artificially; minute natural traces also occur.', 'primarily-synthetic':'Primarily synthetic: made in nuclear reactions. This label describes the usual source, rather than ruling out every possible trace occurrence.'};
 const make=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const position=(el,row,column)=>{el.style.gridRow=String(row);el.style.gridColumn=String(column);};
 function tile(e,list=false){const b=make('button',undefined,'element-tile family-'+e.category+(e.explorerAvailable?' available':''));b.type='button';b.dataset.z=e.atomicNumber;b.dataset.symbol=e.symbol;b.id=(list?'list-':'tile-')+e.symbol;b.setAttribute('aria-pressed','false');b.setAttribute('aria-label',e.atomicNumber+', '+e.name+', '+e.symbol+', '+e.family+', '+(e.explorerAvailable?'interactive atom explorer available':'basic information; explorer coming soon'));b.append(make('span',e.atomicNumber,'element-number'),make('span',e.symbol,'element-symbol'),make('span',e.name,'element-name'));if(C.elements[e.atomicNumber]?.heavyPExplorer||(C.elements[e.atomicNumber]?.actinideExplorer||C.elements[e.atomicNumber]?.transactinideExplorer)){const mass=e.mass.kind==='standard'?e.mass.value:'['+e.mass.massNumber+']';b.append(make('span',mass,'element-mass'));b.setAttribute('aria-label',b.getAttribute('aria-label')+', '+(e.mass.kind==='standard'?'atomic weight ':'representative isotope mass number ')+mass);}if(!list)position(b,e.grid.row+1,e.grid.column+1);// Only two stationary primary-mouse clicks qualify. Touch keeps native scroll/zoom.
 let press=null,clicks=[];
 b.onpointerdown=event=>{press={id:event.pointerId,x:event.clientX,y:event.clientY,valid:event.pointerType==='mouse'&&event.button===0&&event.isPrimary};};
 b.onpointermove=event=>{if(press&&Math.hypot(event.clientX-press.x,event.clientY-press.y)>6)press.valid=false;};
 b.onpointercancel=()=>{press=null;clicks=[];};
 b.onpointerup=event=>{clicks.push({valid:!!press?.valid&&press.id===event.pointerId,time:performance.now()});clicks=clicks.slice(-2);press=null;};
 b.onclick=()=>navigate('element='+e.symbol);
 b.ondblclick=event=>{if(clicks.length===2&&clicks.every(c=>c.valid)&&clicks[1].time-clicks[0].time<900&&e.explorerAvailable&&C.explorerRegistry[e.symbol]){event.preventDefault();navigate('explore='+e.symbol);}};
 b.onkeydown=event=>arrow(event,e,list);return b;}
 function arrow(event,e,list){if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();let next;if(list){const offset=['ArrowLeft','ArrowUp'].includes(event.key)?-1:1;next=records.filter(matches).find(x=>offset>0?x.atomicNumber>e.atomicNumber:false);if(offset<0)next=records.filter(x=>matches(x)&&x.atomicNumber<e.atomicNumber).at(-1);}else{const horizontal=['ArrowLeft','ArrowRight'].includes(event.key),forward=['ArrowRight','ArrowDown'].includes(event.key),candidates=records.filter(x=>horizontal?x.grid.row===e.grid.row&&(forward?x.grid.column>e.grid.column:x.grid.column<e.grid.column):x.grid.column===e.grid.column&&(forward?x.grid.row>e.grid.row:x.grid.row<e.grid.row));candidates.sort((a,b)=>horizontal?a.grid.column-b.grid.column:a.grid.row-b.grid.row);next=forward?candidates[0]:candidates.at(-1);}if(next){const b=$(list?'list-'+next.symbol:'tile-'+next.symbol);b.focus({preventScroll:true});b.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'});}}
 function matches(e){const q=state.query.trim().toLowerCase(),search=!q||(/^\d+$/.test(q)?e.atomicNumber===Number(q):e.symbol.toLowerCase().includes(q)||e.name.toLowerCase().includes(q)||e.aliases.some(a=>a.includes(q)));return search&&(!state.filters.length||state.filters.includes(e.category));}
 function applyMatches(){const result=records.filter(matches),active=!!state.query.trim()||state.filters.length>0;for(const e of records){const yes=matches(e);for(const b of tiles.get(e.symbol)){b.classList.toggle('is-dim',!yes);b.classList.toggle('is-match',yes&&active);b.setAttribute('aria-pressed',String(state.selectedElement===e.symbol));if(b.id.startsWith('list-'))b.hidden=!yes;}}$('match-count').textContent=result.length+' of 118 elements match'+(state.filters.length?' · '+state.filters.length+' active '+(state.filters.length===1?'family':'families'):'');document.querySelectorAll('[data-family]').forEach(b=>b.setAttribute('aria-pressed',String(state.filters.includes(b.dataset.family))));return result;}
 function refreshCardJump(){const rect=$('element-card').getBoundingClientRect();$('card-jump').hidden=state.page!=='table'||!state.selectedElement||(rect.top<innerHeight&&rect.bottom>0);$('card-jump').textContent=(C.basicBySymbol[state.selectedElement]?.name||'Element')+' · View details';}
 function card(){const e=C.basicBySymbol[state.selectedElement],container=$('card-content'),w=words[state.level];container.replaceChildren();$('card-empty').hidden=!!e;container.hidden=!e;if(!e){refreshCardJump();return;}
  const top=make('div',undefined,'card-top'),details=make('div',undefined,'card-details'),close=make('button','Close','card-close');close.id='close-element';close.onclick=()=>{const selected=e.symbol;navigate('periodic-table');requestAnimationFrame(()=>$(state.layout==='list'?'list-'+selected:'tile-'+selected)?.focus({preventScroll:true}));};top.append(close,make('span','ELEMENT '+e.atomicNumber,'eyebrow'),make('strong',e.symbol,'card-symbol'));const h=make('h2',e.name);h.id='selected-element-title';h.tabIndex=-1;top.append(h,make('p',w.description(e)));
  const dl=make('dl');for(const [label,value] of [['Atomic number',e.atomicNumber],['Period',e.period],['Group',e.group||'Detached series'],['Family',e.family],['Block',e.block]]){const row=make('div');row.append(make('dt',label),make('dd',value));dl.append(row);}top.append(dl);
  details.append(make('p',e.mass.kind==='standard'?'Standard atomic weight (abridged)':'Representative isotope (mass number)','mass-label'));details.append(make('strong',e.mass.kind==='standard'?e.mass.value+' ± '+e.mass.uncertainty:'['+e.mass.massNumber+']','mass-value'));details.append(make('p',e.mass.kind==='standard'?w.weight:w.representative));details.append(make('p',occurrence[e.occurrence]));if(e.atomicNumber===1)details.append(make('p','Hydrogen sits above group 1 because it has one electron. It is a nonmetal with properties very different from the alkali metals.'));if(e.category==='unknown')details.append(make('p','The group is conventional. Many bulk properties have not been measured, so a predicted family is not treated as established here.'));
  if(e.explorerAvailable){const full=C.elements[e.atomicNumber];details.append(make('p','Default isotope: '+full.name+'-'+C.isotopes[full.defaultIsotope].massNumber+' · Shells: '+full.neutralShells.join('–')+' · '+full.neutralConfiguration));const a=make('a','Explore '+e.name+' Atom','explore-link');a.href='#explore='+e.symbol;a.id='explore-element';details.append(a);}else details.append(make('p','Explorer coming soon','availability'));details.append(make('p',e.explorerAvailable?w.available:w.unavailable));const source=make('a','Element reference · RSC');source.href=e.reference;source.target='_blank';source.rel='noopener noreferrer';details.append(source);container.append(top,details);$('element-card').setAttribute('aria-labelledby','selected-element-title');refreshCardJump();
 }
 function updateWords(){const w=words[state.level];$('table-introduction').textContent=w.intro+' Select an element to learn about it. Hydrogen through oganesson have atom explorers. Single-click for facts; double-click an available element to explore.';document.querySelectorAll('[data-home-level]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.homeLevel===state.level)));const dl=$('table-explanations');dl.replaceChildren();for(const [key,label] of Object.entries({groups:'Groups',periods:'Periods',families:'Families',number:'Atomic number',weight:'Atomic weight',representative:'Representative isotope'}))dl.append(make('dt',label),make('dd',w[key]));card();}
 function selectElement(symbol,focus=true){state.selectedElement=symbol;card();applyMatches();if(symbol){const b=$(state.layout==='list'?'list-'+symbol:'tile-'+symbol);if(state.layout==='table'){const scroll=$('table-scroll'),left=b.offsetLeft-scroll.offsetLeft;if(left<scroll.scrollLeft)scroll.scrollLeft=left-8;else if(left+b.offsetWidth>scroll.scrollLeft+scroll.clientWidth)scroll.scrollLeft=left+b.offsetWidth-scroll.clientWidth+8;}if(focus)$('selected-element-title')?.focus({preventScroll:true});}else $('element-card').setAttribute('aria-labelledby','element-card-title');}
 let routing=0;
 async function route(){const token=++routing;let hash=location.hash.slice(1),symbol=null,explore=false;try{hash=decodeURIComponent(hash);}catch(_){hash='invalid';}const m=hash.match(/^(element|explore)=([A-Za-z]{1,2})$/);if(m){symbol=records.find(e=>e.symbol.toLowerCase()===m[2].toLowerCase())?.symbol;explore=m[1]==='explore';}if(hash&&hash!=='periodic-table'&&(!m||!symbol)){history.replaceState(null,'','#periodic-table');symbol=null;explore=false;}if(explore&&(!C.basicBySymbol[symbol]?.explorerAvailable||!C.explorerRegistry[symbol])){history.replaceState(null,'','#element='+symbol);explore=false;}
  if(explore){if(state.page==='table'){state.tableScroll=$('table-scroll').scrollLeft;state.pageScroll=window.scrollY;}state.page='explorer';state.selectedElement=symbol;$('periodic-page').hidden=true;$('explorer-page').hidden=false;const app=C.explorerRegistry[symbol]();app.state.level=state.level;document.body.classList.toggle('inside',app.state.view==='nucleon');app.updateModelUI();app.select(app.state.selected);app.setActive(true);document.title=app.atom.element.name+' Atom Explorer';for(const [id,offset] of [['previous-element',-1],['next-element',1]]){const adjacent=records.find(e=>e.atomicNumber===app.atom.protons+offset),button=$(id);button.disabled=!adjacent?.explorerAvailable||!C.explorerRegistry[adjacent?.symbol];button.setAttribute('aria-label',(offset<0?'Previous Element':'Next Element')+(adjacent?': '+adjacent.name+(button.disabled?' (explorer unavailable)':''):': none'));}window.scrollTo(0,state.explorerScroll);$('back-table').focus({preventScroll:true});}
  else {const wasExplorer=state.page==='explorer';if(wasExplorer&&C.app){state.explorerScroll=window.scrollY;state.level=C.app.state.level;if(C.app.state.presentation)await C.app.exitPresentation();if(token!==routing)return;C.app.setActive(false);}state.page='table';document.body.classList.remove('inside','presenting');$('explorer-page').hidden=true;$('periodic-page').hidden=false;document.title='Interactive Periodic Table & Atom Explorer';updateWords();selectElement(symbol,!wasExplorer);if(wasExplorer){$('table-scroll').scrollLeft=state.tableScroll;window.scrollTo(0,state.pageScroll);$(state.layout==='list'?'list-'+(symbol||'Cu'):'tile-'+(symbol||'Cu'))?.focus({preventScroll:true});}}
 }
 function navigate(hash){if(location.hash==='#'+hash)route();else location.hash=hash;}
 if(!C.periodicValidation.ok){$('table-introduction').textContent='The element data could not be validated. Please use an intact copy of the application.';console.error(C.periodicValidation.errors);return;}
 const grid=$('periodic-grid');for(let group=1;group<=18;group++){const label=make('span',group,'axis-label');position(label,1,group+1);grid.append(label);}for(let period=1;period<=7;period++){const label=make('span',period,'axis-label');position(label,period+1,1);grid.append(label);}for(const [row,text] of [[6,'57–71'],[7,'89–103']]){const p=make('div',undefined,'series-placeholder');p.append(make('span',text),make('span','↓'));position(p,row+1,4);grid.append(p);}for(const [row,text] of [[10,'6 · Lanthanides'],[11,'7 · Actinides']]){const label=make('span',text,'series-row-label');position(label,row,1);label.style.gridColumn='1 / 4';grid.append(label);}
 for(const e of records){const a=tile(e),b=tile(e,true);grid.append(a);$('element-list').append(b);tiles.set(e.symbol,[a,b]);}
 for(const [id,name] of Object.entries(C.families)){const b=make('button',name,'family-button family-'+id);b.dataset.family=id;b.setAttribute('aria-pressed','false');b.onclick=()=>{state.filters=state.filters.includes(id)?state.filters.filter(f=>f!==id):[...state.filters,id];applyMatches();};$('family-buttons').append(b);}
 $('family-buttons').append($('clear-filters'));
 for(const source of C.periodicSources){const p=make('p',undefined,'source-entry'),a=make('a',source.title);a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';p.append(make('strong',source.organization+' · '),a,document.createTextNode(' — Accessed '+source.accessed+'. '+source.supports));$('periodic-sources').append(p);}
 $('element-search').oninput=()=>{state.query=$('element-search').value;applyMatches();};$('element-search').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();const hits=applyMatches(),q=state.query.trim().toLowerCase(),best=hits.find(x=>x.symbol.toLowerCase()===q||x.name.toLowerCase()===q||String(x.atomicNumber)===q||x.aliases.includes(q))||hits[0];if(best)navigate('element='+best.symbol);}};
 $('clear-search').onclick=()=>{state.query='';$('element-search').value='';applyMatches();$('element-search').focus();};$('clear-filters').onclick=()=>{state.filters=[];applyMatches();};$('category-color').onchange=()=>{state.color=$('category-color').checked;$('periodic-page').classList.toggle('no-category-color',!state.color);};
 document.querySelectorAll('[data-table-view]').forEach(b=>b.onclick=()=>{if(state.layout==='table')state.tableScroll=$('table-scroll').scrollLeft;state.layout=b.dataset.tableView;$('table-scroll').hidden=state.layout!=='table';$('element-list').hidden=state.layout!=='list';document.querySelectorAll('[data-table-view]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.tableView===state.layout)));if(state.layout==='table')$('table-scroll').scrollLeft=state.tableScroll;});
 document.querySelectorAll('[data-home-level]').forEach(b=>b.onclick=()=>{state.level=b.dataset.homeLevel;if(C.app){C.app.state.level=state.level;C.app.updateModelUI();C.app.select(C.app.state.selected);}updateWords();});
 document.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>{state.level=b.dataset.level;}));
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.page==='table'&&state.selectedElement){e.preventDefault();$('close-element')?.click();}});
 for(const [id,offset] of [['previous-element',-1],['next-element',1]])$(id).onclick=()=>{const adjacent=records.find(e=>e.atomicNumber===C.app?.atom.protons+offset);if(adjacent?.explorerAvailable&&C.explorerRegistry[adjacent.symbol])navigate('explore='+adjacent.symbol);};
 $('back-table').onclick=e=>{e.preventDefault();navigate('element='+state.selectedElement);};
 $('card-jump').onclick=()=>{$('element-card').scrollIntoView({block:'start',behavior:'instant'});$('selected-element-title')?.focus({preventScroll:true});refreshCardJump();};window.addEventListener('scroll',refreshCardJump,{passive:true});window.addEventListener('resize',refreshCardJump);
 window.addEventListener('hashchange',route);updateWords();applyMatches();route();
})(window.Copper);
