/* Phase 6C. Explicit neutral ground states, independently checked against NIST.
 * Display radii are elsewhere. Abundance and decay are independent properties. */
(function(C){
 'use strict';
 const L=(elementary,middle,high)=>({elementary,middle,high}),sources={},elements={},isotopes={};
 const source=(key,organization,title,url,supports)=>{sources[key]={organization,title,url,supports,accessed:'2026-09-10'};return key;};
 source('p4Decay','BIPM / DDEP','Table of Radionuclides, volume 1','https://www.bipm.org/utils/common/pdf/monographieRI/Monographie_BIPM-5_Tables_Vol1.pdf','Mn-54 electron capture and approximately 312-day half-life; Ti-44 electron capture.');
 source('p4KDecay','BIPM / DDEP','Table of Radionuclides, volume 5','https://www.bipm.org/utils/common/pdf/monographieRI/Monographie_BIPM-5_Tables_Vol5.pdf','K-40: 1.2504 billion years; beta-minus, electron capture and a tiny positron branch.');
 source('p4CaDecay','NEMO-3 collaboration','Measurement of calcium-48 double-beta decay','https://arxiv.org/abs/1604.01710','Observed two-neutrino double-beta decay; measured half-life 6.4 × 10^19 years, with statistical and systematic uncertainty. Selected measurement, not an exact constant.');
 source('p4ScHalf','De Felice et al.','Half-life measurement of 44Sc and 44mSc','https://www.iris.unina.it/handle/11588/966728','Sc-44 ground-state half-life 4.042(7) hours, confirming the newer measurement rather than the older 3.97-hour recommendation.');
 source('p4Sc','Scandium radionuclide researchers','Production of scandium radionuclides for theranostic applications','https://pmc.ncbi.nlm.nih.gov/articles/PMC8149571/','Sc-44 positron/EC imaging; Sc-47 beta-minus therapy/imaging research, about 3.35 days; Ti-44/Sc-44 generator research. Emerging applications are qualified.');
 source('p4TiHalf','DOE / NIDC','Titanium-44 product information','https://www.isotopes.gov/sites/default/files/2023-11/Ti-44.pdf','Approximately 60 years; daughter scandium-44.');
 source('p4TiSpace','NASA / NuSTAR','The Creation of Titanium in Stars','https://science.nasa.gov/photojournal/the-creation-of-titanium-in-stars/','Titanium-44 traces supernova explosions.');
 source('p4VDecay','Danevich et al.','Decay scheme of 50V','https://arxiv.org/abs/2008.02751','Observed electron capture: partial half-life 2.77 (+0.20/−0.19) × 10^17 years. Beta-minus branch not detected; limit 8.9 × 10^18 years.');
 source('p4MnUse','DOE / NIDC','Introducing to market: Manganese-54','https://isotopes.gov/new-domestic-supply-manganese-54','Manganese-54 radiotracers in biomedical research.');
 source('p4Geology','USGS','Iron, chromium and calcium isotope analysis','https://pubs.usgs.gov/publication/70032875','Natural-material isotope ratios for calcium, iron and chromium.');
 source('p4CrSpace','USGS','Chromium isotope geochemistry','https://wwwrcamnl.wr.usgs.gov/isoig/period/cr_iig.html','Chromium-53 and manganese–chromium studies of early solar-system history.');
 source('p4Fe57','NASA','Characterization Strategies and Requirements','https://www.nasa.gov/sites/default/files/atoms/files/carpenter.pdf','Iron-57 Mössbauer spectroscopy for identifying iron-bearing planetary minerals.');
 source('p4Fe60','NASA','Observation of the 60Fe Nucleosynthesis-Clock Isotope','https://ntrs.nasa.gov/citations/20170002656','Iron-60: approximately 2.6 million years; supernova-produced cosmic rays.');
 source('p4FeEarth','Wallner et al.','Recent near-Earth supernovae probed by global deposition of interstellar 60Fe','https://www.nature.com/articles/nature17196','Measured iron-60 deposits on Earth as evidence of past nearby stellar explosions.');
 source('p4Co60','CDC','Cobalt-60','https://www.cdc.gov/radiation-emergencies/hcp/isotopes/cobalt-60.html','5.27 years; beta particles and gamma rays; therapy, sterilization, industrial radiography and gauges; radiation protection.');
 source('p4NiHalf','NIST','Primary Radioactivity Standardization of Ni-63','https://www.nist.gov/programs-projects/basic-metrology-archive-primary-radioactivity-standardization-ni-63','Ni-63: measured 101.1 ± 1.4 years; radioactivity standards.');
 source('p4NiUse','DOE / NIDC','November 2024 isotope spotlights','https://www.isotopes.gov/November-2024-spotlights','Ni-63 beta emission; trace detectors and specialized betavoltaic batteries.');
 source('p4Binding','M. P. Fewell / American Journal of Physics','The atomic nuclide with the highest mean binding energy','https://www.physics.smu.edu/scalise/quarknet2008/FewellAJP000653.pdf','Ni-62 has exceptionally high binding energy per nucleon; mean binding energy is a specific measure, not a universal stability label.');
 source('p4Energy','DOE','Energy Storage Supply Chain Report','https://www.energy.gov/sites/default/files/2022-02/Energy%20Storage%20Supply%20Chain%20Report%20-%20final.pdf','Vanadium redox-flow storage, steel and catalysts.');
 source('p4Core','DOE','Distribution transformer technical discussion','https://www.energy.gov/sites/default/files/2024-04/dt_ecs_fr.pdf','Electrical steel is an iron alloy; thin laminations form magnetic transformer cores and reduce losses. Only material physics is used here.');
 source('p4MnCalibration','NIST / NBS','Standard Reference Materials catalog','https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nbsspecialpublication260e1981.pdf','Manganese-54 radioactivity calibration standards.');
 source('p4Planet','Simon and DePaolo','Calcium isotope composition of meteorites, Earth, and Mars','https://doi.org/10.1088/0004-637X/702/1/707','Calcium isotope ratios in planetary materials.');
 source('p4TiPlanet','Researchers / Earth and Planetary Science Letters','Calcium and titanium isotope fractionation in refractory inclusions','https://www.sciencedirect.com/science/article/pii/S0012821X17302558','Calcium and titanium isotope ratios as tracers of early solar-system processes.');
 source('p4KDating','USGS','Neutron Irradiations for Argon Isotopic Dating','https://www.usgs.gov/usgs-triga-reactor/neutron-irradiations-argon-isotopic-dating','Argon–argon dating is a variant of potassium–argon dating.');
 source('p4KNatural','EPA','Radiation Sources and Doses','https://www.epa.gov/radiation/radiation-sources-and-doses','Naturally occurring potassium-40 contributes to radioactivity within the body.');
 source('p4FeDecay','NNDC / ENSDF','Iron-60 beta-minus decay dataset','https://www.nndc.bnl.gov/nudat3/getdecaydataset.jsp?dsid=60fe+bM+decay&nucleus=60CO','Iron-60 beta-minus decay to cobalt-60. Half-life display follows the newer NASA-cited 2.6-million-year value.');
 const transition=L('Some outer electrons can be used in different ways when this atom joins other atoms. Both 4s and nearby 3d electrons matter.','Transition metals can use electrons from their outer 4s shell and nearby 3d subshell in bonding. This helps many of them form different ion charges.','In transition metals, outer 4s and nearby 3d electrons can take part in bonding and ion formation. Many transition metals form more than one ion charge. The outer-shell count alone does not describe their valence behavior.');
 const dText=L('This electron belongs to the 3d group in the third shell. It can help the atom join other atoms.','The 3d subshell lies in the third energy level. Its electrons can help form bonds, along with the outer 4s electrons.','The 3d subshell is a chemically important transition region in principal level 3. It contains five related orbitals. Its electrons can contribute to bonding along with the outer 4s electrons.');
 const crNote=L('Chromium’s electrons arrange themselves a little differently than the simplest pattern predicts.','A basic filling pattern might predict four electrons in 3d and two in 4s. Chromium instead has five in 3d and one in 4s.','Chromium is an exception to the simplest Aufbau filling order. Its measured ground state is [Ar] 3d⁵ 4s¹, with a half-filled 3d subshell. This is not a rule that half-filled subshells are always preferred.');
 // z, name, symbol, default mass, 3d occupancy, 4s occupancy, natural mass/percent pairs.
 const records=[
 [19,'Potassium','K',39,0,1,[[39,93.2581],[40,.0117],[41,6.7302]]],
 [20,'Calcium','Ca',40,0,2,[[40,96.941],[42,.647],[43,.135],[44,2.086],[46,.004],[48,.187]]],
 [21,'Scandium','Sc',45,1,2,[[45,100]]],
 [22,'Titanium','Ti',48,2,2,[[46,8.25],[47,7.44],[48,73.72],[49,5.41],[50,5.18]]],
 [23,'Vanadium','V',51,3,2,[[50,.250],[51,99.750]]],
 [24,'Chromium','Cr',52,5,1,[[50,4.345],[52,83.789],[53,9.501],[54,2.365]]],
 [25,'Manganese','Mn',55,5,2,[[55,100]]],
 [26,'Iron','Fe',56,6,2,[[54,5.845],[56,91.754],[57,2.119],[58,.282]]],
 [27,'Cobalt','Co',59,7,2,[[59,100]]],
 [28,'Nickel','Ni',58,8,2,[[58,68.0769],[60,26.2231],[61,1.1399],[62,3.6345],[64,.9256]]]
 ];
 const overviews=[
 L('Potassium is a very reactive metal. In nature it is found in compounds. Potassium in food helps our bodies work.','Potassium is an alkali metal usually found in compounds. Potassium ions support nerves and fluid balance. They behave very differently from potassium metal.','Potassium is a highly reactive alkali metal. It occurs naturally in compounds. Potassium ions are essential in biology; elemental potassium does not behave like potassium in food.'),
 L('Calcium compounds help build bones and buildings. Pure calcium is a reactive metal.','Calcium is an alkaline-earth metal found naturally in compounds. These compounds occur in bones and minerals. They also help make cement.','Calcium is a reactive alkaline-earth metal normally found in compounds. Calcium ions support bones and cell signals. Calcium minerals are important in cement and construction.'),
 L('Scandium is a metal used in small amounts with aluminum. This can help make strong, light parts.','Scandium is a transition metal with specialized uses. Small additions can strengthen aluminum alloys. It also has uses in special lamps.','Scandium is a transition metal used in aluminum alloys and specialized lighting. Its lightweight alloys support aerospace research. Large-scale use remains relatively limited.'),
 L('Titanium makes strong, light metal parts. Titanium compounds can make white paint.','Titanium is strong for its weight and resists corrosion. The metal is used in aircraft and medical materials. Titanium dioxide is a separate compound used in pigments.','Titanium combines strength, low weight and corrosion resistance. Its metal and alloys support aerospace and medical materials. Titanium dioxide pigments have different properties from the metal.'),
 L('Vanadium helps make strong steel. It can also help store electricity in special batteries.','Vanadium is a transition metal used to strengthen steel. Its compounds serve as catalysts and in flow batteries.','Vanadium strengthens steel and supports industrial catalysts. Vanadium redox-flow batteries store energy using dissolved vanadium compounds. This is different from a piece of vanadium metal.'),
 L('Chromium helps steel resist rust. Its compounds can have very different properties.','Chromium is a transition metal used in stainless steel, plating and pigments. Its metal and compounds are not interchangeable.','Chromium helps stainless steel resist corrosion. It is also used in plating and pigments. Hexavalent chromium compounds have different properties and hazards from chromium metal.'),
 L('Manganese helps make steel and batteries. Living things need small amounts of it.','Manganese is a transition metal important in steel production. Its compounds also support batteries. The body needs small amounts.','Manganese supports steel production and battery materials. It is also a biological nutrient in small amounts. Its role depends on its chemical form.'),
 L('Iron helps make strong buildings and machines. Our bodies also need iron.','Iron is a major structural metal used in steel. Iron-containing materials can also guide magnetic fields. Iron is essential in blood.','Iron is a major structural metal and the main ingredient of steel. Iron-based magnetic materials support electrical machines. Iron also plays essential biological roles.'),
 L('Cobalt helps make magnets, batteries and parts that stay strong when hot.','Cobalt is a transition metal used in high-temperature alloys, magnets and battery materials. Ordinary cobalt is mostly stable cobalt-59.','Cobalt supports high-temperature alloys, permanent magnets and battery materials. Ordinary cobalt uses are separate from controlled radioactive cobalt-60 applications.'),
 L('Nickel helps metals resist rust. It is also used in batteries and magnets.','Nickel is a transition metal used in stainless steel, plating and batteries. Some nickel alloys have useful magnetic properties.','Nickel supports corrosion-resistant alloys, stainless steel and plating. Nickel compounds are used in batteries. Selected nickel alloys are useful magnetic materials.')
 ];
 const engineering=[
 L('Potassium compounds help plants grow and help make glass.','Potassium compounds are important in fertilizers and glassmaking. The useful compound is different from the reactive metal.','Potassium-containing fertilizers supply a plant nutrient. Other potassium compounds support glass and chemical manufacturing. These applications use compounds, not reactive potassium metal.'),
 L('Calcium minerals help make cement for buildings.','Calcium compounds connect biology with construction. Calcium-rich minerals are raw materials for cement.','Calcium minerals support cement and construction materials. Calcium ions also support biological processes. The metal, mineral and ion have different properties.'),
 L('A little scandium can strengthen aluminum parts.','Aluminum–scandium alloys combine low weight with improved strength. Specialized lamps use scandium compounds.','Aluminum–scandium alloys are studied for lightweight aerospace parts. Scandium compounds also support specialized lighting. Cost and supply limit broad adoption.'),
 L('Titanium helps make aircraft parts and medical implants.','Titanium alloys are useful when low weight and corrosion resistance matter. Titanium dioxide makes bright white pigments.','Titanium alloys support aircraft and medical implants through strength and corrosion resistance. Titanium dioxide is used separately as a white pigment.'),
 L('Some batteries store energy in liquids containing vanadium.','Vanadium flow batteries store energy in liquid tanks. Pumps move the liquids through a cell to charge or release energy.','Vanadium redox-flow batteries store energy in dissolved vanadium ions with different charges. Tanks hold the liquids and a cell transfers charge. This supports stationary energy storage.'),
 L('Chromium helps protect stainless steel from rust.','Chromium helps form a thin protective surface layer on stainless steel. Chromium compounds are also used in pigments.','Chromium helps stainless steel form a protective oxide surface. Plating and pigment applications use different chemical forms. Hexavalent compounds require their own hazard controls.'),
 L('Manganese helps make useful steel and battery materials.','Steelmaking uses manganese to improve processing and properties. Manganese dioxide is used in batteries.','Manganese contributes to steelmaking and battery electrodes. Manganese dioxide and manganese-containing battery materials have different roles from the pure metal.'),
 L('Iron inside a coil can help guide a magnetic field. This helps motors and transformers work.','Iron-based cores guide magnetic fields in motors, transformers and inductors. Engineers choose the material and shape to reduce wasted energy.','Iron-based magnetic cores guide magnetic flux in electrical machines, transformers and inductors. Material choice and core construction affect energy losses. One isolated atom cannot predict a finished core’s behavior.'),
 L('Cobalt helps make strong magnets and heat-resistant parts.','Cobalt alloys resist high temperatures. Cobalt also supports magnets and battery materials. Radioactive cobalt-60 has separate, controlled uses.','Cobalt-containing alloys support hot engine parts, permanent magnets and batteries. Cobalt-60 radiation sources serve different applications and require radiation protection.'),
 L('Nickel helps make long-lasting metal parts and rechargeable batteries.','Nickel alloys resist corrosion. Nickel materials also support batteries and magnetic parts.','Nickel supports stainless steel, corrosion-resistant plating and battery electrodes. Selected alloys are used for magnetic components. Composition and processing determine the finished properties.')
 ];
 const special={
 'K-40':{half:[1.2504e9,'years','Approximately 1.25 billion years'],modes:['Beta-minus (β−) to calcium-40','Electron capture to argon-40','Tiny positron-emission (β+) branch'],keys:['p4KDecay'],uses:L('Potassium-40 helps scientists date old rocks. It is also naturally present in living things.','Potassium-40 supports potassium–argon and argon–argon dating. It contributes to natural radioactivity in rocks and living organisms.','Potassium-40 decay helps date rocks using potassium–argon and argon–argon methods. It also contributes to natural radioactivity in rocks and organisms.')},
 'Ca-48':{half:[6.4e19,'years','Approximately 6.4 × 10¹⁹ years (NEMO-3 measurement)'],modes:['Two-neutrino double-beta-minus decay'],keys:['p4CaDecay'],uses:L('Calcium-48 changes so slowly that scientists need special experiments to see it.','Calcium-48 is naturally radioactive, but its double-beta decay is extremely rare. It is studied in sensitive nuclear experiments.','Calcium-48 undergoes observed two-neutrino double-beta decay. Its enormous half-life explains why simplified tables sometimes treat it as stable. Here it is classified as radioactive.')},
 'Sc-44':{half:[4.042,'hours','Approximately 4.04 hours'],modes:['Primarily positron emission (β+)','Electron capture'],keys:['p4ScHalf','p4Sc'],uses:L('Scientists study scandium-44 to help make pictures inside the body.','Scandium-44 is studied for PET imaging. Its positrons help scanners locate a labelled substance.','Scandium-44 is used in PET imaging research and emerging radiopharmaceutical work. These applications depend on the labelled compound and are not all routine clinical treatments.')},
 'Sc-47':{half:[3.35,'days','Approximately 3.35 days'],modes:['Beta-minus (β−)'],keys:['p4Sc'],uses:L('Scientists study scandium-47 for medical pictures and treatments.','Scandium-47 is studied for targeted radiation therapy and imaging. These medical uses are still developing.','Scandium-47 is investigated for targeted radionuclide therapy and imaging. Its beta radiation can deliver energy to targeted tissue. These are emerging research applications.')},
 'Ti-44':{half:[60,'years','Approximately 60 years'],modes:['Electron capture to scandium-44'],keys:['p4Decay','p4TiHalf','p4TiSpace','p4Sc'],uses:L('Titanium-44 helps scientists study exploding stars.','Titanium-44 traces supernova explosions. Researchers also use its decay to obtain scandium-44.','Titanium-44 radiation traces supernova ejecta. Specialized titanium-44/scandium-44 generators support radionuclide research.')},
 'V-50':{half:[2.77e17,'years','Approximately 2.77 × 10¹⁷ years (electron-capture partial half-life)'],modes:['Observed electron capture to titanium-50'],keys:['p4VDecay'],uses:L('Vanadium-50 occurs naturally. It changes incredibly slowly.','Vanadium-50 is naturally radioactive and extremely long-lived. Sensitive experiments study its rare electron-capture decay.','Vanadium-50 undergoes observed electron capture. The selected experiment did not detect the possible beta-minus branch. The quoted value is the measured electron-capture partial half-life.')},
 'Cr-53':{keys:['p4CrSpace','p4Geology'],uses:L('Chromium-53 helps scientists study rocks and meteorites.','Chromium-53 ratios help researchers study geology and the early solar system.','Chromium-53 isotope geochemistry helps trace natural processes. Manganese–chromium isotope records also reveal early solar-system history.')},
 'Mn-54':{half:[312.13,'days','Approximately 312 days'],modes:['Primarily electron capture'],keys:['p4Decay','p4MnUse'],uses:L('Manganese-54 helps scientists follow small amounts of material.','Manganese-54 is a radioactive tracer in biomedical research. It is also used in radiation calibration work.','Manganese-54 supports research tracers and calibration of radiation measurements. These uses rely on its radioactivity, unlike ordinary manganese in steel.')},
 'Fe-57':{keys:['p4Fe57'],uses:L('Iron-57 helps scientists identify iron minerals.','Iron-57 is used in Mössbauer spectroscopy, a method that studies how nuclei absorb radiation. It helps identify iron-bearing materials.','Iron-57 Mössbauer spectroscopy probes iron’s local chemical and magnetic surroundings. It helps identify iron minerals. Ordinary steel does not require separated iron-57.')},
 'Fe-60':{half:[2.6e6,'years','Approximately 2.6 million years'],modes:['Beta-minus (β−) to cobalt-60'],keys:['p4Fe60','p4FeEarth'],uses:L('Iron-60 found on Earth gives clues about old exploding stars.','Iron-60 is radioactive. Deposits found on Earth provide evidence of past nearby stellar explosions.','Iron-60 in terrestrial deposits records past arrivals of stellar material. Its long half-life also makes it a useful tracer of supernova-produced cosmic rays.')},
 'Co-60':{half:[5.27,'years','Approximately 5.27 years'],modes:['Beta-minus (β−) to nickel-60, followed by gamma radiation'],keys:['p4Co60'],uses:L('Cobalt-60 radiation can help treat illness and sterilize supplies. Only trained people use these protected sources.','Cobalt-60 is used for radiation therapy, sterilization and industrial measurements. Its radiation requires shielding and trained handling.','Cobalt-60 sources support radiation therapy, sterilization, industrial radiography and gauges. They require radiation protection and trained handling. Ordinary cobalt metal is not equivalent to a cobalt-60 source.')},
 'Ni-62':{keys:['p4Binding'],uses:L('Nickel-62 has a very tightly bound nucleus.','Nickel-62 has an unusually large binding energy per proton or neutron. This compares how strongly nuclei are held together.','Nickel-62 has exceptionally high binding energy per nucleon. This is a specific nuclear comparison, not an automatic label of “most stable” in every sense.')},
 'Ni-63':{half:[101.1,'years','Approximately 101 years'],modes:['Beta-minus (β−) to copper-63'],keys:['p4NiHalf','p4NiUse'],uses:L('Nickel-63 helps special detectors and small research power sources work.','Nickel-63 is used in trace detectors and specialized betavoltaic batteries. These devices turn beta-radiation energy into electricity.','Nickel-63 supports trace detection, radioactivity measurement and specialized betavoltaic technology. Betavoltaic devices convert beta-particle energy into electricity. These are controlled radioactive sources.')}
 };
 for(const [index,row] of records.entries()){
  const [z,name,symbol,mass,d,s,natural]=row,slug=name.toLowerCase();
  const ciaaw=source('p4'+symbol+'CIAAW','CIAAW / IUPAC','Atomic Weight of '+name,'https://ciaaw.org/'+slug+'.htm','Natural isotope identities and representative terrestrial isotope percentages; not universal cosmic abundances.'),nist=source('p4'+symbol+'NIST','NIST','Atomic Data for '+name,'https://physics.nist.gov/PhysRefData/Handbook/Tables/'+slug+'table1.htm','Verified neutral ground-state configuration. Nickel uses 3d8 4s2; chromium uses 3d5 4s1.'),rsc=source('p4'+symbol+'RSC','Royal Society of Chemistry',name+': properties and uses','https://periodic-table.rsc.org/element/'+z+'/'+slug,'Element identity, chemistry, compounds and material applications.');
  const subs=[['1s',1,'s',2],['2s',2,'s',2],['2p',2,'p',6],['3s',3,'s',2],['3p',3,'p',6],...(d?[['3d',3,'d',d]]:[]),['4s',4,'s',s]].map(([id,n,l,occupancy])=>({id,n,l,occupancy}));
  const outer=L('This atom has '+s+' outer electron'+(s===1?'':'s')+' in the fourth shell. '+(d?'Nearby 3d electrons also help it join other atoms.':'These electrons help it join other atoms.'),'The outer 4s subshell contains '+s+' electron'+(s===1?'':'s')+'. '+(d?'Nearby 3d electrons can also help form bonds.':symbol==='K'?'Potassium commonly forms a +1 ion.':'Calcium commonly forms a +2 ion.'),'The outermost 4s subshell contains '+s+' electron'+(s===1?'':'s')+'. '+(d?'Both 4s and 3d electrons matter in bonding and ion formation.':symbol==='K'?'Potassium commonly loses this electron to form a +1 ion.':'Calcium commonly loses these electrons to form a +2 ion.'));
  const valence=d?transition:outer,extra=Object.entries(special).filter(([key])=>key.startsWith(symbol+'-')).flatMap(([,value])=>value.keys||[]),keys=[ciaaw,nist,rsc,'p3Stars',...new Set(extra),...(symbol==='V'?['p4Energy']:[])];
  const masses=[...natural.map(([m])=>m),...Object.keys(special).filter(k=>k.startsWith(symbol+'-')).map(k=>Number(k.split('-')[1])).filter(m=>!natural.some(([n])=>n===m))],config=C.fullConfiguration(subs);
  elements[z]={atomicNumber:z,name,symbol,defaultIsotope:slug+'-'+mass,availableIsotopes:masses.map(m=>slug+'-'+m),neutralElectronCount:z,neutralShells:[2,8,8+d,s],neutralSubshells:subs,neutralConfiguration:config,fullConfiguration:config,shorthandConfiguration:'[Ar] '+C.fullConfiguration(subs.filter(sub=>sub.id==='3d'||sub.id==='4s')),valence:{shells:[4],importantSubshells:d?['3d','4s']:['4s'],descriptions:valence,studentNote:valence.high},transitionRegion:d?'3d':null,period4Detail:true,conciseOverview:true,fullDetail:true,waveResolution:'subshell',descriptions:overviews[index],context:{title:'Engineering Connection',descriptions:engineering[index]},sources:keys,isotopeSourceKeys:keys,isotopeGuideKeys:['isotope','stable','radioactive','abundance','halfLife','decay','weighted','cosmic'],periodProgressionTitle:'Across Period 4',configurationNote:symbol==='Cr'?crNote:null,
   periodProgression:L('Potassium starts the 4s group. Calcium fills it. From scandium to nickel, electrons build up in 3d. Chromium is an exception to the simplest pattern. The arrangement helps shape electricity, magnets and bonds. Real materials also depend on how many atoms fit together.','Potassium begins 4s and calcium fills it. Scandium begins the transition series, with 3d filling through nickel. Chromium is an exception to the basic pattern. Electron arrangement influences conductivity, magnetism, bonds and ion charges. A solid’s behavior also depends on interactions between many atoms.','Across Period 4, potassium begins 4s, calcium fills 4s and scandium begins the 3d transition series. The 3d occupancy grows through nickel, with chromium’s 3d⁵ 4s¹ exception. These arrangements influence conductivity, magnetism, bonding and ion formation. Bulk properties also depend on atomic interactions and structure, not one isolated atom.'),
   isotopeEducation:{isotope:L('Isotopes are versions of '+slug+' with different neutron counts.','All '+slug+' isotopes have '+z+' protons. Their neutron counts differ.','Changing isotope changes neutrons. The neutral atom keeps '+z+' electrons and the same ground-state configuration.'),abundance:L('These percentages describe a natural mixture on Earth. A naturally radioactive isotope can be part of that mixture.','These are representative Earth abundances. Extremely long-lived radioactive isotopes are included when naturally present. Produced isotopes have no ordinary percentage.','CIAAW representative terrestrial abundances are shown as percentages. Natural variation and measurement uncertainty apply. Naturally occurring K-40, Ca-48 and V-50 remain in their mixtures despite being radioactive.'),weighted:L('Atomic weight describes a mixture of isotopes.','Atomic weight uses isotope masses and proportions. Mass number counts protons and neutrons in one atom.','Standard atomic weight averages isotope masses using their proportions. Mass number is a whole-number nucleon count, not an isotope’s measured mass.'),cosmic:symbol==='Fe'?L('Stars made iron. Iron-60 on Earth gives clues about past exploding stars.','Iron-group elements form in stellar nuclear reactions. Iron-60 deposits on Earth record past stellar material.','Stellar processes produce iron-group elements. Terrestrial iron-60 deposits provide evidence of past nearby supernovae. Earth’s ordinary isotope mixture is not a universal abundance.'):symbol==='Ti'?L('Exploding stars make titanium. Scientists can follow radioactive titanium-44.','Titanium isotope ratios help study planetary materials. Titanium-44 traces supernova debris.','Titanium isotopes inform geochemical and planetary research. Titanium-44 maps supernova ejecta. Terrestrial abundance percentages do not describe all space.'):L('Stars helped make this element. Isotope mixtures can be different in space.','Stellar nuclear reactions and explosions help make these elements. Earth’s isotope mixture does not apply everywhere in space.','Stellar nucleosynthesis produces these elements through nuclear reactions. Nickel produced in explosions also participates in radioactive decay chains. Terrestrial isotope abundances are not universal cosmic ratios.')},
   education:{concepts:{'valence-electron':outer,'transition-electron':dText},regions:{waveValence:outer,orbitalValence:outer,waveTransition:dText,orbitalTransition:dText},models:{bohr:L('Four rings show the occupied shells. Every electron is shown. Real electrons do not follow these tracks.','Four shells contain '+[2,8,8+d,s].join(', ')+' electrons. The rings show counts, not real tracks.','The shell populations are '+[2,8,8+d,s].join(', ')+'. All electrons are shown individually. Paths, sizes and distances are simplified.'),wave:L('Each wave stands for an occupied electron group. Electron balls do not ride on the waves.','All occupied subshells have a matter-wave pattern. '+(d?'The 3d and 4s states':'The 4s state')+' are emphasized. These are teaching patterns.','Each occupied subshell has a conceptual standing-wave band with its actual occupancy. This is not an exact many-electron wavefunction.'),quantum:L('Clouds show where electrons might be found. The dots are not separate electrons.','Overview shows all occupied subshells. Explore Subshells isolates one shape. Denser regions suggest a greater chance of finding electrons.','All occupied subshells appear as transparent qualitative probability regions. Explore Subshells isolates one subshell; 3d uses a representative orientation from five related orbitals. These are not fixed electron paths.')}}};
  if(symbol==='Fe'){keys.push('p4Core','p4Geology','p4FeDecay');special['Fe-60'].keys.push('p4FeDecay');}
  if(symbol==='K'){keys.push('p4KDating','p4KNatural');special['K-40'].keys.push('p4KDating','p4KNatural');}
  if(symbol==='Mn'){keys.push('p4MnCalibration');special['Mn-54'].keys.push('p4MnCalibration');}
  if(symbol==='Ca'){
   keys.push('p4Planet','p4Geology');
   elements[z].isotopeEducation.cosmic=L('Calcium isotope mixtures help scientists study rocks, living things and planets.','Calcium isotope ratios help researchers study geology, biology and planetary materials. Earth’s mixture is not universal.','Calcium isotope ratios trace geological and biological processes. Comparisons of meteorites, Earth and Mars also support planetary research. Terrestrial percentages are not universal cosmic abundances.');
  }
  if(symbol==='Ti')keys.push('p4TiPlanet');
  const uncertainty={K:[.0044,.0001,.0044],Ca:[.156,.023,.010,.110,.003,.021],Sc:[0],Ti:[.03,.02,.03,.02,.02],V:[.010,.010],Cr:[.013,.018,.017,.007],Mn:[0],Fe:[.105,.106,.029,.012],Co:[0],Ni:[.0190,.0150,.0013,.0040,.0019]}[symbol];
  for(const m of masses){const detail=special[symbol+'-'+m]||{},halfLife=detail.half?{value:detail.half[0],unit:detail.half[1],display:detail.half[2]}:null,stable=!halfLife,percent=natural.find(([n])=>n===m)?.[1],id=slug+'-'+m;
   const uses=detail.uses||L(name+'-'+m+' is part of the natural isotope mixture.','Scientists compare '+slug+' isotope amounts in natural materials. Ordinary uses do not usually separate this isotope.','This isotope contributes to natural isotope-ratio and atomic-weight studies. Ordinary '+slug+' applications generally use the natural mixture, not a separated isotope.');
   const stableText=percent===100?'It is the only stable naturally occurring isotope of '+slug+'.':percent>50?'It is stable and makes up most natural '+slug+'.':'It is stable.';
   const descriptions=L(name+'-'+m+' has '+z+' protons and '+(m-z)+' neutrons. '+(stable?stableText:'It is radioactive.'),name+'-'+m+' has '+(m-z)+' neutrons. '+(stable?stableText:'Its half-life is '+halfLife.display.toLowerCase()+'.'),name+'-'+m+' contains '+z+' protons and '+(m-z)+' neutrons. '+(stable?stableText:'It is radioactive. Its half-life is '+halfLife.display.toLowerCase()+'.'));
   isotopes[id]={id,element:name,symbol,elementSymbol:symbol,atomicNumber:z,massNumber:m,protons:z,neutrons:m-z,stable,stabilityClassification:stable?'Stable':(symbol==='Ca'&&m===48||symbol==='V'&&m===50)?'Radioactive · extremely long-lived':'Radioactive',common:percent!==undefined,displayName:name+'-'+m,halfLife,decayModes:detail.modes||[],primaryDecay:detail.modes?.[0]||null,naturalComponent:percent!==undefined,naturalAbundance:percent===undefined?null:{percent,scope:'CIAAW representative terrestrial composition'},origin:percent===undefined?'Produced for research; possible qualified natural traces':'Natural terrestrial isotope',abundanceText:percent===undefined?'No ordinary natural-abundance percentage is assigned. Produced for specialized work'+(symbol==='Fe'||symbol==='Ti'?'; also studied in stellar material.':'.'):'Representative natural terrestrial abundance: '+percent+'%'+(!stable?' (radioactive).':'.'),descriptions,note:descriptions.high,uses:uses.high,usesByLevel:uses,sources:[ciaaw,rsc,...(detail.keys||[])]};
   if(percent!==undefined)isotopes[id].naturalAbundance.uncertaintyPercentagePoints=uncertainty[natural.findIndex(([n])=>n===m)];
  }
 }
 C.isotopeSources=C.deepFreeze({...C.isotopeSources,...sources});C.isotopes=C.deepFreeze({...C.isotopes,...isotopes});C.elements=C.deepFreeze({...C.elements,...elements});
 C.validatePeriod4Data=(catalog=elements,nuclides=C.isotopes)=>{
  const errors=[];for(const e of Object.values(catalog)){
   if(e.neutralConfiguration!==C.fullConfiguration(e.neutralSubshells))errors.push(e.symbol+': configuration text mismatch');
   for(const level of ['elementary','middle','high'])for(const text of [e.descriptions,e.context?.descriptions,e.valence?.descriptions,e.periodProgression,...Object.values(e.education?.models||{}),...Object.values(e.isotopeEducation||{})])if(!text?.[level])errors.push(e.symbol+': missing '+level+' explanation');
   for(const id of e.availableIsotopes){const i=nuclides[id],valid=C.validateRecord(e,i);if(!valid.ok){errors.push(valid.error);continue;}if(i.protons!==e.atomicNumber||i.neutrons!==i.massNumber-e.atomicNumber||i.elementSymbol!==e.symbol)errors.push(id+': identity mismatch');if(!i.stable&&(!(i.halfLife?.value>0)||!i.primaryDecay||i.primaryDecay!==i.decayModes[0]))errors.push(id+': radioactive fields');if(i.stable&&i.halfLife!==null)errors.push(id+': stable half-life');if(i.naturalAbundance&&(!i.naturalComponent||!(i.naturalAbundance.rangePercent?i.naturalAbundance.rangePercent.length===2&&i.naturalAbundance.rangePercent[0]>=0&&i.naturalAbundance.rangePercent[1]<=100&&i.naturalAbundance.rangePercent[0]<=i.naturalAbundance.rangePercent[1]:i.naturalAbundance.percent>0&&i.naturalAbundance.percent<=100)))errors.push(id+': natural abundance');for(const level of ['elementary','middle','high'])if(!i.descriptions?.[level]||!i.usesByLevel?.[level])errors.push(id+': missing isotope explanation');if(!i.abundanceText||!i.sources?.length||i.sources.some(k=>!C.isotopeSources[k]))errors.push(id+': missing source or abundance');}
  }return {ok:!errors.length,elements:Object.keys(catalog).length,isotopes:Object.values(catalog).reduce((n,e)=>n+e.availableIsotopes.length,0),errors};
 };
 C.period4Validation=C.validatePeriod4Data();C.enabledValidation=C.validateEnabledData();if(!C.period4Validation.ok||!C.enabledValidation.ok)throw Error([...C.period4Validation.errors,...C.enabledValidation.errors].join('; '));
})(window.Copper);
