/* Curated first four Period 5 elements. Explicit neutral configurations; offline sources. */
(function(C){
 'use strict';
 const L=(elementary,middle,high)=>({elementary,middle,high}),sources={},elements={},isotopes={};
 const source=(key,organization,title,url,supports)=>{sources[key]={organization,title,url,supports,accessed:'2026-09-10'};return key;};
 source('p5Abundance','CIAAW / IUPAC','Isotopic compositions of the elements 2024','https://www.ciaaw.org/isotopic-abundances.htm','Rb, Sr, Y and updated 2024 Zr terrestrial fractions and uncertainties. Natural radioactive Rb-87 and Zr-96 remain in the mixture.');
 source('p5RbDecay','CIAAW / IUPAC','Atomic weight of rubidium','https://www.ciaaw.org/rubidium.htm','Rb-87 beta-minus decay; half-life 48.8(5) billion years. Learning value follows this named source, not a precision geochronology calibration.');
 source('p5Dating','USGS','Geologic Time: Radiometric Time Scale','https://pubs.usgs.gov/gip/geotime/radiometric.html','Rb-87 decays to stable Sr-87; rubidium-strontium rock dating.');
 source('p5Clock','NIST','Time and Frequency from A to Z: Re to Ru','https://www.nist.gov/pml/time-and-frequency-division/popular-links/time-frequency-z/time-and-frequency-z-re-ru','Rubidium clocks use an atomic transition in Rb-87 to stabilize an oscillator; they do not count radioactive decays.');
 source('p5SrYDecay','BIPM / DDEP','Table of Radionuclides, volume 3','https://www.bipm.org/utils/common/pdf/monographieRI/Monographie_BIPM-5_Tables_Vol3.pdf','Printed pages 43 and 47: Sr-90 28.80(7) years, beta-minus to Y-90; Y-90 2.6684(13) days, beta-minus to Zr-90.');
 source('p5SrUses','US EPA','Radionuclide Basics: Strontium-90','https://www.epa.gov/radiation/radionuclide-basics-strontium-90','Radioactive fission product, industrial uses and historical fallout; ordinary natural strontium isotopes are stable.');
 source('p5SrProvenance','British Geological Survey','Updated biosphere map for the UK','https://www.bgs.ac.uk/news/updated-biosphere-map-for-the-uk-released/','Sr-87/Sr-86 ratios in geographical provenance and archaeological studies.');
 source('p5YMedical','IAEA','Trends and Practices in Diagnosis and Treatment of Hepatocellular Carcinoma','https://www-pub.iaea.org/MTCD/Publications/PDF/Pub1446_web.pdf','Y-90 microspheres deliver localized radiation in selected liver-cancer treatments; chemical form and delivery matter.');
 source('p5Zr89Decay','BIPM / DDEP','Table of Radionuclides, volume 8','https://www.bipm.org/utils/common/pdf/monographieRI/Monographie_BIPM-5_Tables_Vol8.pdf','Printed page 79: Zr-89 half-life 78.42(13) hours; electron capture and positron emission to Y-89.');
 source('p5ZrPET','DOE / NIDC','PNNL researchers automate purification of zirconium-89','https://www.isotopes.gov/node/72','Zr-89-labelled antibodies and related compounds for immunoPET imaging and research.');
 source('p5Zr96','NEMO-3 collaboration / University of Manchester','Measurement of the two-neutrino double-beta half-life of Zr-96','https://research.manchester.ac.uk/en/publications/measurement-of-the-two-neutrino-double-beta-decay-half-life-of-zr-2/','Observed two-neutrino double-beta decay: 2.35 ±0.14 statistical ±0.16 systematic ×10^19 years. Searches for neutrinoless decay are not an observation.');
 const progression=L('Rubidium starts a new outside group called 5s. Strontium adds its second electron. Yttrium starts 4d, and zirconium adds a second 4d electron. Both groups help these last two metals join other atoms.','Period 5 begins with 5s¹ in rubidium and 5s² in strontium. Yttrium starts 4d¹; zirconium has 4d². Both keep 5s². The 4d and 5s electrons can both help form bonds.','The neutral configurations progress from [Kr] 5s¹ to 5s², then 4d¹ 5s² and 4d² 5s². Both 4d and 5s can matter in transition-metal chemistry. The outermost shell count alone does not define their valence behavior.');
 const outer=L('This electron is in the outside 5s group. Outer electrons help atoms join together.','The 5s electrons occupy the fifth energy level. They can be important when atoms form bonds or ions.','The outer 5s electrons help determine chemical behavior. For yttrium and zirconium, the 4d electrons can also contribute.');
 const transition=L('This electron is in the 4d group. It can help this metal join other atoms, even though it is not in the outside shell.','The developing 4d subshell is in the fourth energy level. Its electrons and the outer 5s electrons can both be important in bonding.','The 4d subshell contains five related orbitals. Its electrons can contribute to bonding alongside 5s electrons. Outermost-shell count alone does not describe transition-metal valence.');
 const rows=[
 {z:37,name:'Rubidium',symbol:'Rb',mass:85,s:1,d:0,shells:[2,8,18,8,1],natural:[[85,72.17,.02],[87,27.83,.02]],radio:[],
 overview:L('Rubidium is a soft metal that reacts very easily. In nature it is usually part of compounds. Scientists use it in clocks and research.','Rubidium is a soft, highly reactive alkali metal. It occurs in minerals as compounds. Its atoms are useful in atomic clocks and scientific research.','Rubidium is a soft alkali metal with one outer 5s electron. It is highly reactive and usually found in compounds. Rubidium-87 also supports rock dating.'),
 engineering:L('Rubidium atoms help some clocks keep steady time. Scientists also use rubidium to study atoms.','A rubidium clock uses a repeatable change in an atom’s energy to keep time. This is different from radioactive dating of rocks.','Rubidium clocks use a precise atomic transition to stabilize a timing signal. They do not count radioactive decays. Rubidium-strontium dating instead uses slow nuclear decay.'),
 behavior:L('Rubidium has one outer electron. It readily loses this electron when forming many compounds.','Rubidium has one 5s electron and commonly forms a +1 ion. This helps explain its high reactivity.','Rubidium’s 5s¹ arrangement supports a common +1 oxidation state. Its reactions depend on the other substances and conditions.')},
 {z:38,name:'Strontium',symbol:'Sr',mass:88,s:2,d:0,shells:[2,8,18,8,2],natural:[[84,.56,.02],[86,9.86,.20],[87,7,.20],[88,82.58,.35]],radio:[90],
 overview:L('Strontium is a metal whose compounds make red fireworks and flares. Its ordinary natural isotopes are stable. Strontium-90 is a different, radioactive isotope.','Strontium is an alkaline-earth metal. Its compounds give red colors to fireworks and signal flares. Stable strontium is different from radioactive strontium-90.','Strontium is an alkaline-earth metal with two outer 5s electrons. Its compounds are used in red flares, specialized ceramics and ferrite magnets. The four ordinary natural isotopes are stable.'),
 engineering:L('Strontium compounds help make red lights and some magnets. These materials use ordinary stable strontium.','Strontium salts produce red fireworks and flares. Strontium compounds also form useful ceramics and ferrite magnets.','Strontium compounds support red pyrotechnic colors, ceramic materials and ferrite magnets. These uses generally involve the stable natural mixture. The material’s properties depend on many atoms together.'),
 behavior:L('Strontium has two outer electrons. It often loses both when forming compounds.','Strontium’s 5s group holds two electrons. It commonly forms a +2 ion.','Strontium’s 5s² arrangement supports its common +2 oxidation state. A compound’s behavior also depends on its other atoms.')},
 {z:39,name:'Yttrium',symbol:'Y',mass:89,s:2,d:1,shells:[2,8,18,9,2],natural:[[89,100,0]],radio:[90],
 overview:L('Yttrium is a metal used in special lights, lasers and ceramics. Ordinary yttrium is stable. A radioactive version called yttrium-90 is used in some medical treatments.','Yttrium is a transition metal. Its compounds help make LEDs, phosphors, lasers and special ceramics. Yttrium-89 is its only stable natural isotope.','Yttrium is a transition metal with 4d¹ 5s² beyond the krypton core. Its compounds support light emitters, lasers, ceramics and superconducting materials. Ordinary yttrium-89 is stable.'),
 engineering:L('Yttrium compounds help some LEDs make white light. They also help make laser crystals.','Yttrium-containing crystals support lasers and LED phosphors, materials that give off light. Other yttrium compounds are used in ceramics.','Yttrium-aluminium garnet supports laser crystals and LED phosphors. Yttrium-containing ceramics also include superconductors, which carry current without electrical resistance under suitable conditions. These are properties of materials, not isolated atoms.'),
 behavior:transition},
 {z:40,name:'Zirconium',symbol:'Zr',mass:90,s:2,d:2,shells:[2,8,18,10,2],natural:[[90,51.47,.06],[91,11.23,.06],[92,17.16,.04],[94,17.36,.07],[96,2.78,.04]],radio:[89],
 overview:L('Zirconium is a metal that resists corrosion. Its compounds make strong ceramics. Zircon and zirconia contain zirconium but are different materials.','Zirconium is a corrosion-resistant transition metal. Its alloys protect nuclear fuel, and its compounds make heat-resistant ceramics. Cubic zirconia is a compound, not zirconium metal.','Zirconium is a transition metal with 4d² 5s² beyond the krypton core. Its alloys are used in reactor cladding, the tubes around nuclear fuel. Its compounds support ceramics and high-temperature materials.'),
 engineering:L('Zirconium alloys make protective tubes around nuclear fuel. Zirconia is a different material used in strong ceramics.','Zirconium alloys resist corrosion and absorb relatively few neutrons. This makes them useful as nuclear-fuel cladding. Zirconia is zirconium oxide; zircon is a silicate mineral.','Zirconium alloys combine corrosion resistance with low neutron absorption for reactor cladding. Zirconia is zirconium oxide, including synthetic cubic zirconia gemstones. Zircon is zirconium silicate, a different natural mineral.'),
 behavior:transition}
 ];
 const special={
 'Rb-87':{half:[4.88e10,'years','Approximately 48.8 billion years'],modes:['Beta-minus (β−) to strontium-87'],keys:['p5RbDecay','p5Dating','p5Clock'],uses:L('Rubidium-87 changes very slowly into strontium-87. This helps scientists find the ages of rocks.','Rubidium-87 is used in rubidium-strontium dating. Scientists compare parent and daughter isotopes to estimate rock ages.','Rubidium-87 decays to stable strontium-87. Their isotope ratios support rock dating. Atomic clocks also use Rb-87, but rely on an atomic transition rather than nuclear decay.')},
 'Sr-87':{keys:['p5Dating','p5SrProvenance'],uses:L('Strontium-87 helps scientists study rocks and where old materials came from.','Strontium-87 is stable. Comparing it with strontium-86 helps study rocks and the origins of archaeological materials.','The strontium-87/strontium-86 ratio helps trace geological and archaeological origins. Some Sr-87 formed from Rb-87 decay. Local isotope patterns and other evidence guide the interpretation.')},
 'Sr-90':{half:[28.80,'years','Approximately 29 years'],modes:['Beta-minus (β−) to yttrium-90'],keys:['p5SrYDecay','p5SrUses'],uses:L('Strontium-90 is radioactive. It is used in specialized measurements and studied in nuclear fallout.','Strontium-90 is a fission product, made when heavy nuclei split. It has industrial uses and is monitored in environmental research.','Strontium-90 is a radioactive fission product with industrial and scientific uses. Its historical fallout and reactor-waste role make it important in environmental monitoring. It is distinct from the four stable natural strontium isotopes.')},
 'Y-90':{half:[2.6684,'days','Approximately 64 hours'],modes:['Beta-minus (β−) to zirconium-90'],keys:['p5SrYDecay','p5YMedical'],uses:L('Yttrium-90 is radioactive. Doctors use it in some carefully targeted cancer treatments.','Yttrium-90 gives off beta radiation. Special carriers deliver it to treatment sites, including some liver tumors.','Yttrium-90 is used in selected targeted radiation treatments. Microspheres can deliver it to liver tumors. This medical use concerns a radioactive isotope and delivery system, not ordinary stable yttrium.')},
 'Zr-96':{half:[2.35e19,'years','Approximately 2.35 × 10¹⁹ years'],modes:['Two-neutrino double-beta-minus decay to molybdenum-96'],keys:['p5Zr96'],uses:L('Zirconium-96 changes incredibly slowly. Scientists study its rare nuclear decay.','Zirconium-96 is a natural radioactive isotope with an extremely long half-life. Its double-beta decay has been measured.','Zirconium-96 undergoes observed two-neutrino double-beta decay. Experiments also search for a different form without neutrinos, which has not been observed. It is not classified as stable here.')},
 'Zr-89':{half:[78.42,'hours','Approximately 78.4 hours'],modes:['Primarily electron capture to yttrium-89','Positron emission (β+)'],keys:['p5Zr89Decay','p5ZrPET'],uses:L('Zirconium-89 helps researchers make PET images inside the body.','Zirconium-89 can label antibodies for PET imaging. The attached antibody helps determine what is being followed.','Zirconium-89-labelled antibodies support PET imaging and research. Its relatively long imaging half-life allows researchers to follow slowly moving biological compounds. The carrier determines the biological target.')}
 };
 for(const row of rows){
  const {z,name,symbol,s,d}=row,slug=name.toLowerCase(),nist=source('p5'+symbol+'NIST','NIST','Atomic Data for '+name,'https://physics.nist.gov/PhysRefData/Handbook/Tables/'+slug+'table1.htm','Neutral ground state: [Kr] '+(d?'4d'+d+' ':'')+'5s'+s+'. Expanded krypton core contains 36 electrons.'),rsc=source('p5'+symbol+'RSC','Royal Society of Chemistry',name+': properties and uses','https://periodic-table.rsc.org/element/'+z+'/'+slug,'Element identity, compound/material applications, chemical family and natural stable isotope classifications.');
  const subs=[['1s',1,'s',2],['2s',2,'s',2],['2p',2,'p',6],['3s',3,'s',2],['3p',3,'p',6],['3d',3,'d',10],['4s',4,'s',2],['4p',4,'p',6],...(d?[['4d',4,'d',d]]:[]),['5s',5,'s',s]].map(([id,n,l,occupancy])=>({id,n,l,occupancy})),config=C.fullConfiguration(subs),masses=[...row.natural.map(([m])=>m),...row.radio],keys=['p5Abundance',nist,rsc,'p4dStars',...new Set(masses.flatMap(m=>special[symbol+'-'+m]?.keys||[]))];
  elements[z]={atomicNumber:z,name,symbol,defaultIsotope:slug+'-'+row.mass,availableIsotopes:masses.map(m=>slug+'-'+m),neutralElectronCount:z,neutralShells:row.shells,neutralSubshells:subs,neutralConfiguration:config,fullConfiguration:config,shorthandConfiguration:'[Kr] '+C.fullConfiguration(subs.slice(8)),fullDetail:true,period5Detail:true,waveResolution:'subshell',conciseOverview:true,transitionRegion:d?'4d':null,descriptions:row.overview,context:{title:'Engineering Connection',descriptions:row.engineering},valence:{shells:[5],importantSubshells:d?['4d','5s']:['5s'],descriptions:row.behavior,studentNote:row.behavior.high},sources:keys,isotopeSourceKeys:keys,isotopeGuideKeys:['isotope','stable','radioactive','abundance','halfLife','decay','weighted','cosmic'],periodProgressionTitle:'Across Period 5',periodProgression:progression,
   isotopeEducation:{isotope:L('Isotopes are versions of '+slug+' with different neutron counts.','All '+slug+' isotopes have '+z+' protons. Their neutron counts differ.','Changing isotope changes neutrons. The neutral atom keeps '+z+' electrons and its ground-state arrangement.'),abundance:L('These percentages describe mixtures found on Earth. They are not the same everywhere.','The numbers are representative Earth isotope percentages. Natural radioactive isotopes remain included and labelled.','CIAAW terrestrial fractions are representative values with uncertainty. Rock history can change isotope ratios, especially strontium-87 from rubidium decay. No produced isotope receives an invented natural percentage.'),weighted:L('Atomic weight describes a mixture of isotopes.','Atomic weight uses isotope masses and their proportions. It differs from the mass number of one atom.','Atomic weight averages measured isotope masses using their proportions. A mass number counts nucleons in one isotope.'),cosmic:L('Stars helped make this element. Earth’s isotope mixture does not describe all space.','Nuclear processes in stars help produce elements. Mixtures in space can differ from those in Earth materials.','Stellar nuclear processes contribute to these elements. Terrestrial isotope fractions are not universal cosmic abundances.')},
   education:{concepts:{'valence-electron':outer,'transition-electron':transition},regions:{waveValence:outer,orbitalValence:outer,waveTransition:transition,orbitalTransition:transition},models:{bohr:L('Five rings show the occupied shells. Every electron is shown. Real electrons do not follow fixed tracks.','Five shells contain '+row.shells.join(', ')+' electrons. All electrons are selectable. These tracks are a simplified teaching model.','Shell populations are '+row.shells.join(', ')+'. All electrons and nucleons are included. Paths, sizes and distances are simplified.'),wave:L('Each wave shows one occupied electron group. The important outside groups are brighter.','Every occupied subshell has a standing-wave band. The 5s'+(d?' and 4d states are':' state is')+' emphasized. The bands do not carry little electron balls.','All occupied subshells remain visible. The 5s'+(d?' and developing 4d states are':' state is')+' emphasized. These are conceptual standing waves, not exact many-electron wavefunctions.'),quantum:L('Clouds show where electrons might be found. Dots are not separate electrons.','Overview shows all occupied subshells. Explore Subshells isolates one representative shape. Denser regions mean a greater chance of detecting an electron.','Overview keeps every occupied subshell. Explore Subshells gives a representative shape and full occupancy. Clouds are qualitative and do not mark known electron positions.')}}};
  for(const mass of masses){const id=slug+'-'+mass,detail=special[symbol+'-'+mass]||{},natural=row.natural.find(([m])=>m===mass),halfLife=detail.half?{value:detail.half[0],unit:detail.half[1],display:detail.half[2]}:null,stable=!halfLife;
   const stableText=natural?.[1]===100?'It is the only stable natural isotope.':mass===row.mass?'It is the most common natural isotope.':'It is stable.';
   const descriptions=L(name+'-'+mass+' has '+z+' protons and '+(mass-z)+' neutrons. '+(stable?stableText:'It is radioactive.'),name+'-'+mass+' has '+(mass-z)+' neutrons. '+(stable?stableText:'Its half-life is '+halfLife.display.toLowerCase()+'.'),name+'-'+mass+' contains '+z+' protons and '+(mass-z)+' neutrons. '+(stable?stableText:'It is radioactive with a half-life of '+halfLife.display.toLowerCase()+'.'));
   const uses=detail.uses||L('This isotope is part of natural '+slug+'.','Ordinary '+slug+' materials usually contain a mixture of isotopes.','This isotope contributes to the natural mixture. No special isotope-specific industrial use is implied.');
   isotopes[id]={id,element:name,symbol,elementSymbol:symbol,atomicNumber:z,massNumber:mass,protons:z,neutrons:mass-z,stable,stabilityClassification:stable?'Stable':natural?'Radioactive · extremely long-lived':'Radioactive',common:!!natural,displayName:name+'-'+mass,halfLife,decayModes:detail.modes||[],primaryDecay:detail.modes?.[0]||null,naturalComponent:!!natural,naturalAbundance:natural?{percent:natural[1],uncertaintyPercentagePoints:natural[2],scope:'CIAAW representative terrestrial composition'}:null,origin:natural?'Natural terrestrial isotope':'Produced for specialized work; possible environmental traces',abundanceText:natural?'Representative terrestrial abundance: '+natural[1]+'%.'+(!stable?' Extremely long-lived radioactive isotope.':''):'No ordinary natural-abundance percentage is assigned. Produced for specialized work'+(id==='strontium-90'?'; environmental traces can reflect fission releases.':'.'),descriptions,note:descriptions.high,uses:uses.high,usesByLevel:uses,sources:['p5Abundance',rsc,...(detail.keys||[])]};
  }
 }
 C.isotopeSources=C.deepFreeze({...C.isotopeSources,...sources});C.isotopes=C.deepFreeze({...C.isotopes,...isotopes});C.elements=C.deepFreeze({...C.elements,...elements});
 C.validatePeriod5Data=(catalog=elements,nuclides=C.isotopes)=>{const result=C.validatePeriod4Data(catalog,nuclides);for(const e of Object.values(catalog)){const core=[['1s',2],['2s',2],['2p',6],['3s',2],['3p',6],['3d',10],['4s',2],['4p',6]],d=Math.max(0,e.atomicNumber-38),s=e.atomicNumber===37?1:2,expected=[...core,...(d?[['4d',d]]:[]),['5s',s]];if(JSON.stringify(e.neutralSubshells.map(x=>[x.id,x.occupancy]))!==JSON.stringify(expected))result.errors.push(e.symbol+': krypton core / 4d / 5s mismatch');if(JSON.stringify(e.neutralShells)!==JSON.stringify([2,8,18,8+d,s]))result.errors.push(e.symbol+': shell populations');}result.ok=!result.errors.length;return result;};
 C.period5Validation=C.validatePeriod5Data();C.enabledValidation=C.validateEnabledData();if(!C.period5Validation.ok||!C.enabledValidation.ok)throw Error([...C.period5Validation.errors,...C.enabledValidation.errors].join('; '));
})(window.Copper);
