/* Phase 6N: explicit Rf–Ds configurations and curated nuclear observations. */
(function(C){
 'use strict';
 const L=(elementary,middle,high)=>({elementary,middle,high}),elements={},isotopes={},sources={};
 const source=(key,organization,title,url,supports)=>sources[key]={organization,title,url,supports,accessed:'2026-09-14'};
 source('d6Nist','NIST','Atomic properties, June 2024','https://www.nist.gov/system/files/documents/2024/06/25/NIST_periodictable_June24_iupac.pdf','Rf configuration and representative masses. NIST does not supply neutral configurations for Db–Ds in this table; theoretical papers support those records.');
 source('d6Db','Dzuba et al.','Calculation of atomic spectra for dubnium, 2018','https://arxiv.org/abs/1804.08244','Theoretical neutral Db 5f14 6d3 7s2 configuration and relativistic effects.');
 source('d6Theory','Lackenby, Dzuba and Flambaum','Theoretical electronic structure of Sg, Bh, Hs and Mt, 2019','https://arxiv.org/abs/1902.06819','Calculated 6d4–6d7 7s2 ground states; these are predictions, not measured neutral spectra.');
 source('d6Ds','Lackenby, Dzuba and Flambaum','Theoretical atomic properties of elements 110–112, 2019','https://arxiv.org/abs/1910.01414','Predicted Ds 6d8 7s2 ground state; relativistic shifts distinguish it from platinum. Only Ds is implemented here.');
 source('d6Names','IUPAC','Names and symbols of transfermium elements, 1997','https://media.iupac.org/reports/1997/6912transfermium/index.html','Official names Rf–Mt, Rutherford and Dubna contributions, and adoption of seaborgium while Seaborg was living.');
 source('d6Gsi','GSI','New elements','https://www.gsi.de/en/researchaccelerators/research_an_overview/new_elements','Bh, Hs, Mt and Ds naming origins and discoveries; no production instructions are reproduced.');
 source('d6Chemistry','IUPAC','Critical evaluation of transactinide chemical properties','https://publications.iupac.org/projects/2001/2001-071-1-500.html','Atom-by-atom chemistry of Rf, Db and Sg; limited chemical identification of Bh and Hs.');
 source('d6Nubase','IAEA / AMDC','NUBASE2020 nuclear evaluation, published 2021','https://www-nds.iaea.org/amdc/ame2020/NUBASE2020.pdf','Sg-269 5±2 minutes; Bh-270 3.8±3.0 minutes; Bh-274 57±27 seconds. These are symmetrized evaluated lifetimes from sparse events. Other records use the separately cited ENSDF evaluations.');
 const rows=[
  {z:104,name:'Rutherfordium',symbol:'Rf',mass:267,ids:[261,267],relatives:'titanium, zirconium and hafnium',
   words:L('Rutherfordium (Rf) is human-made and radioactive. It is named after Ernest Rutherford.','Rutherfordium is element 104, a synthetic radioactive element in group 4. Scientists study its chemistry one atom at a time. Discovery credit recognizes contributions from Soviet and American teams.','Rutherfordium is represented by [Rn] 5f¹⁴ 6d² 7s², starting this 6d sequence. It sits below titanium, zirconium and hafnium. Rf-267 is longer-lived than many nearby superheavy isotopes, but its lifetime is uncertain. Limited chemistry experiments complement a largely calculated electron arrangement. This model is simplified.'),
   context:L('Scientists study rutherfordium atoms to learn how very heavy atoms behave.','Researchers have tested some of rutherfordium’s chemistry using tiny numbers of atoms. Its group-4 position helps guide comparisons.','Experiments with individual atoms support some similarities to zirconium and hafnium. This does not establish every property of a rutherfordium material. Its discovery involved work by teams in the Soviet Union and the United States.')},
  {z:105,name:'Dubnium',symbol:'Db',mass:268,ids:[262,268],relatives:'vanadium, niobium and tantalum',
   words:L('Dubnium (Db) is human-made and radioactive. Its name honors Dubna, Russia.','Dubnium is element 105, a synthetic radioactive element in group 5. Fast experiments have tested some of its chemistry before the atoms decay. Only tiny numbers of atoms are available.','Dubnium’s predicted configuration is [Rn] 5f¹⁴ 6d³ 7s², with three 6d electrons. It lies below vanadium, niobium and tantalum. Db-268 has a roughly day-long half-life, unlike the much shorter-lived Db-262. Limited chemistry experiments do not establish all of its properties. This model is simplified.'),
   context:L('Dubnium helps scientists compare very heavy atoms with lighter ones.','Dubnium was investigated by competing discovery teams. International evaluation later established its official name.','Dubna and Berkeley made important contributions to discovering element 105. Its atom-by-atom chemistry has been studied experimentally, but simple group-5 comparisons are incomplete. There is no ordinary commercial application.')},
  {z:106,name:'Seaborgium',symbol:'Sg',mass:269,ids:[265,269],relatives:'chromium, molybdenum and tungsten',
   words:L('Seaborgium (Sg) is human-made and radioactive. It was named after Glenn Seaborg while he was still alive.','Seaborgium is element 106, a synthetic radioactive element in group 6 below tungsten. Scientists have studied some of its chemistry one atom at a time. Its name honors Glenn T. Seaborg.','Seaborgium’s predicted configuration is [Rn] 5f¹⁴ 6d⁴ 7s². Its group-6 relatives are chromium, molybdenum and tungsten. Sg-269 has a half-life of a few minutes, with substantial uncertainty. Individual-atom experiments provide limited chemical evidence. This model is simplified.'),
   context:L('Seaborgium helps scientists test ideas about very heavy atoms.','Its position below tungsten helps researchers predict reactions. A few chemical experiments have tested these predictions.','Limited experiments support some group-6 behavior. The name seaborgium was officially adopted while Glenn Seaborg was living. Research on individual atoms cannot establish ordinary bulk properties.')},
  {z:107,name:'Bohrium',symbol:'Bh',mass:270,ids:[270,274],relatives:'manganese, technetium and rhenium',
   words:L('Bohrium (Bh) is human-made and radioactive. It is named after Niels Bohr.','Bohrium is element 107, a synthetic radioactive element in group 7 below rhenium. Scientists study only tiny numbers of atoms. Its name honors the physicist Niels Bohr.','Bohrium’s predicted configuration is [Rn] 5f¹⁴ 6d⁵ 7s², with five 6d electrons. Its group-7 relatives are manganese, technetium and rhenium. Bh-270 and Bh-274 have uncertain lifetimes measured from sparse decay events. Chemical evidence is limited, and relativistic effects can alter simple group trends. This model is simplified.'),
   context:L('Bohrium helps scientists learn whether familiar patterns still hold for very heavy atoms.','A small number of chemical experiments support comparisons with group 7. Bohrium has no everyday application.','Limited chemistry supports its place below rhenium, but many properties remain predictions. Its name honors Niels Bohr’s contributions to physics. No ordinary visible sample exists.')},
  {z:108,name:'Hassium',symbol:'Hs',mass:269,ids:[269,270],relatives:'iron, ruthenium and osmium',
   words:L('Hassium (Hs) is human-made and radioactive. It is named after Hesse, a German state.','Hassium is element 108, a synthetic radioactive element in group 8 below osmium. Scientists have tested some of its chemistry using only a few atoms. It was discovered in Hesse, Germany.','Hassium’s predicted configuration is [Rn] 5f¹⁴ 6d⁶ 7s². It lies below iron, ruthenium and osmium. Hs-269 and Hs-270 decay on a seconds-long timescale. Limited chemistry supports the group-8 placement, but bulk properties remain unmeasured. This model is simplified.'),
   context:L('Hassium helps scientists test predictions about the heaviest atoms.','Chemical experiments support some similarities between hassium and osmium. Scientists cannot collect ordinary samples to measure all of its properties.','Experiments with hassium compounds support its placement below osmium. They do not establish a measured density, color or melting point for bulk hassium. The name comes from Hesse, where GSI is located.')},
  {z:109,name:'Meitnerium',symbol:'Mt',mass:277,ids:[277,278],relatives:'cobalt, rhodium and iridium',
   words:L('Meitnerium (Mt) is human-made and radioactive. It is named after the physicist Lise Meitner.','Meitnerium is element 109, a synthetic radioactive element in group 9 below iridium. Scientists have produced it atom by atom. Its chemistry is mostly predicted.','Meitnerium’s predicted configuration is [Rn] 5f¹⁴ 6d⁷ 7s². Group 9 links it with cobalt, rhodium and iridium. The selected evaluation gives Mt-277 a very short half-life, while Mt-278 lasts seconds. Nuclear observations provide evidence of the element, but its chemistry remains mostly theoretical. This model is simplified.'),
   context:L('Meitnerium honors Lise Meitner. Scientists study its atoms in special laboratories.','Its group-9 position guides predictions, but experiments are very limited. Meitnerium has no ordinary commercial use.','Meitnerium honors physicist Lise Meitner. Decay observations are nuclear evidence; they do not directly measure neutral-electron arrangements or bulk chemistry. Comparisons with iridium remain predictions to test.')},
  {z:110,name:'Darmstadtium',symbol:'Ds',mass:281,ids:[281],relatives:'nickel, palladium and platinum',
   words:L('Darmstadtium (Ds) is human-made and radioactive. It is named after Darmstadt, Germany.','Darmstadtium is element 110, a synthetic radioactive element in group 10 below platinum. Only small numbers of atoms have been produced. It is named after the city where it was discovered.','Darmstadtium’s predicted configuration is [Rn] 5f¹⁴ 6d⁸ 7s². Its group-10 relatives are nickel, palladium and platinum. Ds-281 has a half-life of about 12 seconds in the selected evaluation. Strong relativistic effects help explain why its predicted arrangement differs from platinum’s. This model is simplified.'),
   context:L('Darmstadtium helps scientists explore the limits of very heavy atoms.','Scientists identify darmstadtium through its radioactive changes. Its electron arrangement and chemistry are largely theoretical.','The discovery of element 110 is credited to the GSI team in Darmstadt. Ds-281 supports research on very heavy nuclei; no ordinary industrial use is established. A predicted relationship to platinum is not a measurement of platinum-like material.')}
 ];
 // A label identifies an observed nuclear state when its ground-state ordering is unsettled.
 const detail=[
  ['Rf',261,68,'seconds','About 68 seconds',3,3,['Alpha (α) decay to nobelium-257'],'Longer-lived observed state','The selected longer-lived Rf-261 state has supported chemical studies. The ordering of its observed nuclear states is not settled.'],
  ['Rf',267,1.3,'hours','About 1.3 hours (uncertain)',.5,2.3,['Spontaneous fission'],null,'Rf-267 is relatively long-lived among these isotopes. The evaluated half-life comes from two events and has a large uncertainty.'],
  ['Db',262,35,'seconds','About 35 seconds',5,5,['Mainly alpha (α) decay to lawrencium-258','Fission-related branch; electron-capture contribution unresolved'],null,'Db-262 helps researchers study a short-lived nucleus and compare it with longer-lived dubnium. Branching details remain limited.'],
  ['Db',268,28,'hours','About 28 hours',3,3,['Spontaneous fission observed; other branches not excluded'],null,'Db-268 lasts much longer than Db-262. Its observed decay events support studies of superheavy nuclei, not an everyday material use.'],
  ['Sg',265,14.4,'seconds','About 14 seconds',2.5,3.7,['Alpha (α) decay to rutherfordium-261; fission branch possible'],'Longer-lived observed state','This choice represents the longer-lived observed Sg-265 state. Its ordering relative to another nuclear state is unsettled.'],
  ['Sg',269,5,'minutes','About 5 minutes (uncertain)',2,2,['Alpha (α) decay to rutherfordium-265'],null,'Sg-269 provides a longer-lived comparison for research. Its lifetime is an evaluated estimate from sparse observations.'],
  ['Bh',270,3.8,'minutes','About 4 minutes (very uncertain)',3,3,['Alpha (α) decay to dubnium-266'],null,'Bh-270 is the representative isotope used here. Very few decay observations leave a large uncertainty in its half-life.'],
  ['Bh',274,57,'seconds','About 1 minute (uncertain)',27,27,['Alpha (α) decay to dubnium-270'],null,'Bh-274 extends studies of neutron-rich bohrium nuclei. Its half-life remains uncertain because observations are sparse.'],
  ['Hs',269,13,'seconds','About 13 seconds (uncertain)',4,10,['Alpha (α) decay to seaborgium-265'],null,'Hs-269 is the representative isotope on this table. Its adopted half-life is based on five decay events.'],
  ['Hs',270,7.6,'seconds','About 8 seconds (uncertain)',2.2,4.9,['Mainly alpha (α) decay to seaborgium-266; fission not excluded'],null,'Hs-270 supports studies of very heavy nuclei and their stability. Its half-life is still uncertain.'],
  ['Mt',277,.004,'seconds','About 0.004 seconds (4 milliseconds)',.001,.004,['Spontaneous fission'],null,'The 2022 ENSDF evaluation gives Mt-277 a millisecond-scale half-life. This supersedes the seconds-scale entry in NUBASE2020 for this project.'],
  ['Mt',278,4.5,'seconds','About 5 seconds (uncertain)',1.3,3.5,['Alpha (α) decay to bohrium-274'],null,'Mt-278 is identified from a small number of radioactive-decay observations. It has no ordinary commercial use.'],
  ['Ds',281,12,'seconds','About 12 seconds',2,4,['Mainly spontaneous fission','Alpha (α) branch to hassium-277'],null,'Ds-281 supports research on the decay of superheavy nuclei. Most observed decays end in fission; a small alpha branch is also evaluated.']
 ];
 const safety=L('Every kind of this element is radioactive. Scientists study these atoms only in special research laboratories.','All known isotopes are radioactive. These atoms are produced and studied only in specialized research facilities.','All known isotopes of this element are radioactive. These atoms are produced and studied only in specialized research facilities. A longer half-life does not mean safe handling.');
 const limits=L('Only tiny numbers of atoms can be studied. Scientists use calculations to help understand them.','Accelerators and nuclear-reaction facilities make tiny numbers of these atoms. They often decay quickly, so ordinary visible samples cannot be collected.','Accelerators and nuclear-reaction facilities produce only small numbers of atoms. Researchers may need to identify one atom before it decays. There are no ordinary visible samples; many physical properties remain theoretical predictions.');
 const progression=L('These elements come after the separate actinide row. An inside electron group grows across the row.','The model keeps a full 5f group and two outer 7s electrons. The 6d group grows from two electrons in rutherfordium to eight in darmstadtium.','The listed configurations retain 5f¹⁴ and 7s² while 6d grows: Rf 6d², Db 6d³, Sg 6d⁴, Bh 6d⁵, Hs 6d⁶, Mt 6d⁷ and Ds 6d⁸. Very large positive nuclear charges make relativistic physics important: it changes orbital energies and can alter chemical behavior. Lighter group relatives are useful comparisons, not exact predictions.');
 const outer=L('This electron belongs to an outside group. Nearby electron groups may also help atoms join together.','Two 7s electrons occupy shell 7. The nearby 6d electrons also matter in predictions about bonding.','This electron is in an outer occupied state. For these elements, 6d and 7s states are important to predicted chemical behavior.');
 const inner=L('An electron has negative charge and very little mass. It is found around the nucleus.','An electron has negative charge and extremely small mass compared with a proton. It occupies an allowed state around the nucleus.','An electron has negative charge and about 1/1836 the mass of a proton. It occupies a quantum state, not a fixed planetary path.');
 const core=C.elements[86].neutralSubshells;
 for(const row of rows){const {z,name,symbol,mass,ids}=row,slug=name.toLowerCase(),d=z-102,subs=[...core,{id:'5f',n:5,l:'f',occupancy:14},{id:'6d',n:6,l:'d',occupancy:d},{id:'7s',n:7,l:'s',occupancy:2}],shells=[2,8,18,32,32,8+d,2],keys=['d6Nist',z===105?'d6Db':z===110?'d6Ds':z>=106?'d6Theory':'d6Nist','d6Names','d6Gsi','d6Chemistry'];
  const modelNotice=L('This is a simplified atom picture. Its electron counts follow an arrangement based on scientific calculations.','This model counts electrons using the listed configuration. Scientists have made only tiny numbers of atoms, so some details are calculated rather than measured.','This is a simplified educational model. Electron totals follow the listed configuration, but only small numbers of atoms have been produced and some details are theoretical.');
  elements[z]={atomicNumber:z,name,symbol,defaultIsotope:slug+'-'+mass,availableIsotopes:ids.map(m=>slug+'-'+m),synthetic:true,transactinideExplorer:true,exactHeavyParticles:true,groupedCoreElectronCount:86,fullDetail:false,waveResolution:'subshell',conciseOverview:true,noStableIsotopes:true,neutralElectronCount:z,neutralShells:shells,neutralSubshells:subs,neutralConfiguration:C.fullConfiguration(subs),fullConfiguration:C.fullConfiguration(subs),shorthandConfiguration:'[Rn] '+C.fullConfiguration(subs.slice(core.length)),dataStatus:{atomicNumber:'measured',configuration:'predicted',chemistry:z<=108?'partiallyMeasured':'predicted',bulkProperties:'predicted',representativeMass:'representative'},modelNotice,descriptions:row.words,context:{title:'Scientific Research',descriptions:Object.fromEntries(['elementary','middle','high'].map(l=>[l,row.context[l]+' '+limits[l]+' '+safety[l]]))},valence:{shells:[7],importantSubshells:['5f','6d','7s'],descriptions:outer,studentNote:outer.high},groupRelatives:row.relatives,sources:[...new Set(keys)],isotopeSourceKeys:[...new Set(keys)],periodProgressionTitle:'Beginning the 6d Sequence',periodProgression:progression,isotopeGuideKeys:['isotope','radioactive','abundance','halfLife','decay','weighted','cosmic'],isotopeEducation:{
   isotope:L('These are versions of '+slug+' with different neutron counts.','Every '+slug+' isotope has '+z+' protons. Changing neutrons changes the mass number.','Every neutral isotope here retains '+z+' electrons and the same listed configuration. Chemical reactions involve electrons; radioactive changes involve the nucleus.'),
   radioactive:L('A radioactive nucleus can change and release radiation.','Radioactive atoms change on their own. A longer half-life does not make them safe to handle.','Radioactive decay is a spontaneous nuclear change. Half-life describes a group of nuclei, not the exact lifetime of an individual atom.'),
   abundance:L('Scientists make these atoms for research.','These are synthetic isotopes, made for research. There is no ordinary natural mixture.','These selected isotopes are synthetic. No characteristic natural terrestrial abundance is assigned.'),
   halfLife:L('Half-life describes how long it takes about half of a group of atoms to change.','Scientists estimate half-life from observed decays. Estimates from very few atoms can be quite uncertain.','Half-life describes a group of nuclei, not one individual atom. Sparse observations produce substantial uncertainties, shown with the isotope evidence.'),
   decay:L('A nucleus can change and release particles or energy.','Alpha decay releases two protons and two neutrons together. Spontaneous fission means a nucleus splits on its own.','Alpha decay emits two protons and two neutrons together. Spontaneous fission splits a heavy nucleus. The listed branches summarize evidence; no decay chain is simulated.'),
   weighted:L('The number in brackets counts protons and neutrons in one chosen kind of atom.','A number in brackets is the mass number of a representative isotope. It is not an average atomic weight.','A bracketed number identifies a representative isotope, not an average atomic weight. These synthetic elements have no standard atomic weight based on a characteristic terrestrial mixture.'),
   cosmic:L('These records describe atoms made in special research laboratories.','No natural or cosmic abundance is claimed for the selected isotopes.','These records describe laboratory-produced isotopes. Their existence does not imply a measured natural or cosmic abundance.')},education:{concepts:{'inner-electron':inner,'valence-electron':outer},regions:{waveInner:inner,orbitalInner:inner,waveValence:outer,orbitalValence:outer},models:{bohr:L(name+' has '+z+' electrons in seven counting shells. Rings are not real tracks.','Seven shells contain '+shells.join(', ')+' electrons. Rings help count them; they are not literal paths.',modelNotice.high+' Rings are shell-counting aids, not literal paths.'),wave:L('Electrons behave like waves. These patterns show that idea.','Only certain electron states are allowed. These simple patterns represent many interacting electrons.','This view shows one conceptual pattern per occupied subshell. An atom with over 100 electrons has a complex many-electron state; this app does not calculate the complete wavefunction.'),quantum:L('The cloud shows where electrons might be found. It is not a solid surface.','Overview groups 86 inner electrons and shows the filled 5f group, growing 6d group and outer 7s group. Clouds summarize possible electron locations.','Overview groups the 86-electron radon core and emphasizes 5f¹⁴, 6d'+String(d).replace(/\d/g,n=>'⁰¹²³⁴⁵⁶⁷⁸⁹'[n])+' and 7s². These qualitative clouds are not hard boundaries or measured pictures; the listed electron configuration is primarily predicted.')}}};
  for(const m of ids){const [, ,value,unit,display,minus,plus,modes,state,significance]=detail.find(v=>v[0]===symbol&&v[1]===m),id=slug+'-'+m,nubase=symbol==='Bh'||symbol==='Sg'&&m===269,sourceKey=nubase?'d6Nubase':'d6'+symbol+m;
   if(!nubase)source(sourceKey,'NNDC / ENSDF',symbol+'-'+m+' adopted levels','https://www.nndc.bnl.gov/ensnds/'+m+'/'+symbol+'/adopted.pdf','Selected observed '+(state?state.toLowerCase():'nuclear activity')+': '+value+' '+unit+', uncertainty +'+plus+'/−'+minus+' '+unit+'. '+(state?'Ground-state ordering is not assumed. ':symbol==='Mt'&&m===277?'The 2022 evaluation gives milliseconds, unlike the older NUBASE2020 seconds entry. ':'')+'Decay information is a concise selection, not an exhaustive branch table.');
   const descriptions=L(name+'-'+m+' has '+z+' protons and '+(m-z)+' neutrons. It is radioactive.',name+'-'+m+' has '+(m-z)+' neutrons. Its observed radioactive changes help scientists study heavy nuclei.',name+'-'+m+' has '+z+' protons and '+(m-z)+' neutrons. It is radioactive and retains the same neutral electron configuration.'),uses=L('Scientists study this kind of '+slug+' to learn about very heavy atoms.',significance,significance),originDescriptions=L('Made in special research laboratories.','Synthetic: produced in specialized research facilities.','Synthetic isotope produced and studied in specialized nuclear-reaction facilities.'),measurementStatus=symbol==='Db'?'measured':'partiallyMeasured';
   isotopes[id]={id,element:name,symbol,elementSymbol:symbol,atomicNumber:z,massNumber:m,protons:z,neutrons:m-z,neutralElectronCount:z,stable:false,synthetic:true,stabilityClassification:'Radioactive',common:false,displayName:name+'-'+m+(state?' · longer-lived state':''),halfLife:{value,unit,display,uncertainty:{minus,plus,unit}},measurementStatus,dataStatus:{halfLife:measurementStatus,nuclearState:state?'representative':'partiallyMeasured'},decayModes:modes,primaryDecay:modes[0],origin:'Synthetic; produced for scientific research',originDescriptions,naturalComponent:false,naturalAbundance:null,abundanceTextByLevel:originDescriptions,abundanceText:originDescriptions.high,descriptions,note:descriptions.high,uses:uses.high,usesByLevel:uses,safety:safety.high,safetyDescriptions:safety,sources:[sourceKey],...(state?{nuclearStateLabel:state,nuclearStateDescriptions:L('This choice shows one observed version of the nucleus.','This choice represents a longer-lived nuclear state. Scientists have not settled which observed state has the lowest energy.','Selected longer-lived observed state, not an asserted ground state. The nuclear-level ordering is unsettled; other evaluations may label the states differently.')}:{})};
  }
 }
 C.isotopeSources=C.deepFreeze({...C.isotopeSources,...sources});C.isotopes=C.deepFreeze({...C.isotopes,...isotopes});C.elements=C.deepFreeze({...C.elements,...elements});
 C.validateTransactinideData=(catalog=elements,nuclides=C.isotopes)=>{const r=C.validatePeriod4Data(catalog,nuclides);for(const e of Object.values(catalog)){const j=e.atomicNumber-104,row=rows[j];if(!row||e.name!==row.name||e.symbol!==row.symbol){r.errors.push('Transactinide identity');continue;}const expected=[...core,{id:'5f',n:5,l:'f',occupancy:14},{id:'6d',n:6,l:'d',occupancy:j+2},{id:'7s',n:7,l:'s',occupancy:2}];if(JSON.stringify(e.neutralSubshells)!==JSON.stringify(expected)||JSON.stringify(e.neutralShells)!==JSON.stringify([2,8,18,32,32,10+j,2]))r.errors.push(e.symbol+': explicit 5f14 6d2–8 7s2 required');if(!e.synthetic||e.dataStatus?.configuration!=='predicted'||e.dataStatus?.chemistry!==(j<=4?'partiallyMeasured':'predicted'))r.errors.push(e.symbol+': scientific status');if(nuclides[e.defaultIsotope]?.massNumber!==row.mass)r.errors.push(e.symbol+': representative default');for(const id of e.availableIsotopes){const i=nuclides[id];if(i?.stable!==false||!i.synthetic||!i.halfLife?.value||!i.halfLife.uncertainty||!i.safety||!i.origin||!i.decayModes?.length||!['measured','partiallyMeasured'].includes(i.measurementStatus)||i.naturalAbundance)r.errors.push(id+': radioactive synthetic evidence required');}}r.ok=!r.errors.length;return r;};
 C.enabledValidation=C.validateEnabledData();if(!C.enabledValidation.ok)throw Error(C.enabledValidation.errors.join("; "));
 C.transactinideValidation=C.validateTransactinideData();if(!C.transactinideValidation.ok)throw Error(C.transactinideValidation.errors.join('; '));
})(window.Copper);
