const {chromium}=require('C:/Users/arial/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),{pathToFileURL}=require('url'),path=require('path'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[],remote=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith('file:'))remote.push(r.url());});const url=pathToFileURL(path.resolve('periodic-table-visualizer/index.html')).href;await p.goto(url+'#explore=Cu');await p.evaluate(()=>{const a=Copper.app,load=a.loadAtom;a.loadAtom=function(...args){window.loadCount++;return load.apply(this,args);};window.loadCount=0;});const massRejections=await p.evaluate(()=>{let count=0;for(const z of [96,97,98,99,100,101,102,103]){const records=structuredClone(Copper.basicElements);records.find(e=>e.atomicNumber===z).mass={kind:'standard',value:'209',uncertainty:'1'};if(Copper.validatePeriodicData(records).ok)throw Error('Bracketed mass overwritten');count++;}return count;});assert.equal(massRejections,8);let entries=0,panels=0;
 for(const [symbol,mass] of [['Cm','[247]'],['Bk','[247]'],['Cf','[251]'],['Es','[252]'],['Fm','[257]'],['Md','[258]'],['No','[259]'],['Lr','[262]']]){await p.click('#back-table');await p.evaluate(()=>window.loadCount=0);const tile=p.locator('#tile-'+symbol);assert.equal(await tile.locator('.element-mass').textContent(),mass);await tile.scrollIntoViewIfNeeded();assert.equal(await tile.evaluate(e=>{const n=e.querySelector('.element-number').getBoundingClientRect(),m=e.querySelector('.element-mass').getBoundingClientRect();return n.right>m.left&&n.bottom>m.top&&m.bottom>n.top;}),false);await tile.dblclick();await p.waitForFunction(s=>Copper.applicationState.page==='explorer'&&Copper.app.atom.element.symbol===s,symbol);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>window.loadCount),1);entries++;
  for(const level of ['elementary','middle','high']){await p.click('[data-level="'+level+'"]');await p.locator('#isotope-information details').evaluateAll(es=>es.forEach(e=>e.open=true));const ids=await p.locator('#isotope-select option').evaluateAll(es=>es.map(e=>e.value));for(const id of ids){await p.selectOption('#isotope-select',id);const stable=await p.evaluate(()=>Copper.app.atom.isotope.stable);assert.equal(await p.locator('#isotope-abundance').textContent(),await p.evaluate(()=>Copper.app.atom.isotope.abundanceTextByLevel[Copper.app.state.level]));assert.equal(await p.locator('#isotope-half-life').evaluate(e=>e.hidden),stable);const text=await p.locator('#isotope-information').innerText();assert.equal(/copper|63\.546|29 protons/i.test(text),false);assert.equal(await p.locator('#isotope-information').evaluate(e=>e.scrollWidth>e.clientWidth),false);panels++;}
   const text=await p.locator('#particle-info').innerText();assert.equal(/copper/i.test(text),false);assert.match(await p.locator('#weighted-explanation').textContent(),/not an average|not a weighted average/);
  }
  assert.deepEqual(await p.locator('#particle-list option').evaluateAll(es=>es.map(e=>e.textContent)),['Choose a particle type…','Proton','Neutron','Electron','Outer-region electron']);
  for(const model of ['bohr','wave','quantum']){await p.click('[data-model="'+model+'"]');for(const category of ['proton','neutron','inner-electron','valence-electron']){await p.selectOption('#particle-list',category);assert.equal(await p.locator('#particle-info').evaluate(e=>e.scrollWidth>e.clientWidth),false);if(category==='inner-electron')assert.equal((await p.locator('#particle-info').textContent()).includes('The shell-7 count alone'),false);}}
  assert.match(await p.locator('.conduction p').textContent(),/trained personnel and regulated equipment/);
  assert.match(await p.locator('#simplification-notice').textContent(),/Electron totals and configurations are accurate/);assert.match(await p.locator('#isotope-guide').textContent(),/Chemical reactions involve electrons/);assert.match(await p.locator('#isotope-guide').textContent(),/one individual atom/);
  await p.screenshot({path:'qa/phase6m-'+symbol+'-expanded-phone.png',fullPage:true});
 }
 await p.click('[data-level="high"]');assert.match(await p.locator('.conduction p').textContent(),/does not directly identify/);
 await p.click('#back-table');await p.click('#tile-Lr');assert.equal(await p.locator('.mass-value').textContent(),'[262]');assert.match(await p.locator('.mass-label').textContent(),/Representative isotope/);await p.setViewportSize({width:1366,height:1000});await p.locator('#tile-Lr').scrollIntoViewIfNeeded();await p.locator('#tile-Lr').screenshot({path:'qa/phase6m-Lr-tile.png'});
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);const out={result:'PASS',singleEntryDoubleClicks:entries,massRejections,isotopeLevelPanels:panels,checks:'Published mass labels; no header overlap; one load per double-click; no copper examples; readable isotope panels; all choices radioactive; Cm–Lr bracketed masses; four particle categories; radioactivity/chemistry distinctions; measurement limits',errors,remote};fs.writeFileSync('qa/phase6m-content-results.json',JSON.stringify(out,null,2));console.log(out);
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
