const {chromium}=require('C:/Users/arial/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),{pathToFileURL}=require('url'),path=require('path'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const context=await b.newContext({viewport:{width:1366,height:1000},hasTouch:true,reducedMotion:'reduce'}),p=await context.newPage(),errors=[],remote=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith('file:'))remote.push(r.url());});const url=pathToFileURL(path.resolve('periodic-table-visualizer/index.html')).href,opened=async s=>p.waitForFunction(s=>Copper.app?.atom.element.symbol===s&&Copper.applicationState.page==='explorer',s),symbols=['Hg','Tl','Pb','Bi','Po','At','Rn'];
await p.goto(url);const positions=await p.locator('#periodic-grid .element-tile').evaluateAll(es=>es.map(e=>[e.style.gridRow,e.style.gridColumn]));for(let j=0;j<7;j++){const tile=p.locator('#tile-'+symbols[j]);assert.deepEqual(await tile.evaluate(e=>[e.style.gridRow,e.style.gridColumn]),['7',String(j+13)]);}
await p.locator('#tile-Hg').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>document.activeElement.id),'tile-Tl');await p.keyboard.press('Enter');await p.click('#explore-element');await opened('Tl');await p.click('#previous-element');await opened('Hg');for(const symbol of [...symbols.slice(1),'Fr','Ra','Ac','Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds']){await p.locator('#next-element').focus();await p.keyboard.press('Enter');await opened(symbol);}assert.equal(await p.locator('#next-element').isDisabled(),true);assert.match(await p.locator('#next-element').getAttribute('aria-label'),/Rutherfordium.*unavailable/);await p.click('#previous-element');await opened('No');await p.click('#previous-element');await opened('Md');await p.goBack();await opened('No');await p.reload();await opened('No');
for(const s of ['Rf','Db','Sg']){await p.goto(url+'#explore='+s);await p.waitForFunction(()=>Copper.applicationState.page==='table');assert.equal(await p.locator('#explore-element').count(),0);}
const validated=await p.evaluate(()=>{const C=Copper;let negative=0;for(let z=80;z<=86;z++){const e=C.elements[z];for(const mutate of [e=>e.neutralSubshells=e.neutralSubshells.filter(s=>s.id!=='6s'),e=>e.neutralSubshells.at(-1).occupancy++,e=>e.neutralShells[3]++,e=>e.defaultIsotope='wrong']){const copy=structuredClone(e);mutate(copy);if(C.validatePeriod6CompletionData({[z]:copy}).ok)throw Error('Bad config accepted');negative++;}for(const key of e.sources){const s=C.isotopeSources[key];if(!s?.title||!s.organization||!s.accessed||!s.supports||!s.url.startsWith('https://'))throw Error('Missing source');}for(const id of e.availableIsotopes){const i=C.isotopes[id];if(z>=83){const bad={...i,stable:true,halfLife:null,decayModes:[],primaryDecay:null};if(C.validatePeriod6CompletionData({[z]:e},{...C.isotopes,[id]:bad}).ok)throw Error('Radioactivity lost');negative++;}if(z>=84&&i.naturalAbundance)throw Error('Artificial fixed abundance');}}
for(const [z,m] of [[84,209],[85,210],[86,222]]){const e=C.basicElements.find(e=>e.atomicNumber===z);if(e.mass.kind==='standard'||e.mass.massNumber!==m)throw Error('Bracketed mass');}
if(C.isotopes['bismuth-209'].halfLife.value!==2.01e19)throw Error('Bi-209 measurement');
const ranges={'thallium-203':[29.44,29.59],'thallium-205':[70.41,70.56],'lead-204':[0,1.58],'lead-206':[1.9,86.73],'lead-207':[.35,23.51],'lead-208':[3.38,97.75]};for(const [id,range] of Object.entries(ranges))if(JSON.stringify(C.isotopes[id].naturalAbundance.rangePercent)!==JSON.stringify(range))throw Error('Range');return negative;});assert.equal(validated,36);
let gestures=0;const cdp=await context.newCDPSession(p);for(let j=0;j<symbols.length;j++){const symbol=symbols[j],f=14,d=10;await p.goto(url+'#explore='+symbol);await opened(symbol);
for(const model of ['bohr','wave','quantum']){await p.click('[data-model="'+model+'"]');await p.click('#reset');await p.locator('#atom').scrollIntoViewIfNeeded();const box=await p.locator('#atom').boundingBox(),x=Math.round(box.x+160),y=Math.round(box.y+160);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+35,y:y+25,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(await p.evaluate(()=>Copper.app.state.yaw>.3&&Copper.app.state.pitch<.62));await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1},{x:x+100,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-25,y,id:1},{x:x+125,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(await p.evaluate(()=>Copper.app.state.zoom>1));gestures++;await p.click('#reset');assert.equal(await p.evaluate(()=>!!Copper.app.renderer.nucleonPath),true);await p.locator('#stage').screenshot({path:'qa/phase6k-'+symbol+'-overview-'+model+'.png'});}
await p.evaluate(()=>Copper.app.select('core-overview'));assert.match(await p.locator('#particle-info').innerText(),/Combined inner core · 78 electrons/);assert.equal(await p.evaluate(()=>Copper.app.state.subshell),'all');assert.equal(await p.evaluate(()=>Copper.app.renderer.visibleLayers),j?3:2);await p.click('[data-quantum="explore"]');await p.selectOption('#subshell',f?'4f':'5d');if(f){assert.match(await p.locator('#subshell-info').innerText(),new RegExp(f+' of 14'));assert.equal(await p.evaluate(()=>Copper.app.renderer.focusCloud.points.every(p=>p.orientation===0)),true);}await p.locator('#stage').screenshot({path:'qa/phase6k-'+symbol+'-focused.png'});assert.equal(await p.locator('#subshell option[value="4f"]').count(),f?1:0);assert.equal(await p.locator('#subshell option[value="5d"]').count(),d?1:0);
for(const level of ['elementary','middle','high']){await p.click('[data-level="'+level+'"]');assert.match(await p.locator('#period-progression p').textContent(),/sixth|6p/);assert.match(await p.locator('#period-progression p').textContent(),/electron|6s/);if(f)assert.match(await p.locator('#subshell-info').innerText(),/seven|Seven/);}await p.setViewportSize({width:390,height:844});await p.locator('#isotope-information details').evaluateAll(es=>es.forEach(e=>e.open=true));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:'qa/phase6k-'+symbol+'-reading-390.png',fullPage:true});await p.setViewportSize({width:1366,height:1000});}
await p.goto(url);await p.fill('#element-search','promethium');await p.press('#element-search','Enter');await p.waitForFunction(()=>Copper.applicationState.selectedElement==='Pm');await p.click('[data-family="lanthanide"]');assert.deepEqual(await p.locator('#periodic-grid .element-tile').evaluateAll(es=>es.map(e=>[e.style.gridRow,e.style.gridColumn])),positions);assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);const out={result:'PASS',negativeCases:validated,gestureModelCases:gestures,checks:'Period-six positions and labels; Tab and arrow access; Au-Hg-Rn-Fr-Ra/Ac boundary; history/reload; exact occupied 4f/5d; 78-electron core; representative f shape/capacity; source metadata and isotope sums; three levels; mobile expanded panels; search/filter positions',errors,remote};fs.writeFileSync('qa/phase6k-roles-results.json',JSON.stringify(out,null,2));console.log(out);
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
