const {chromium}=require('C:/Users/arial/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('url'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const context=await browser.newContext({viewport:{width:1366,height:900},hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage(),errors=[],remote=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(!r.url().startsWith('file:'))remote.push(r.url());});
 await page.goto(pathToFileURL(path.resolve('periodic-table-visualizer/index.html')).href+'#explore=Cu');const science=await page.evaluate(()=>JSON.stringify(Copper.app.atom));
 const view=()=>page.evaluate(()=>Copper.app.state.view);const settled=()=>page.waitForFunction(()=>!Copper.app.state.transitioning);
 for(const model of ['bohr','wave','quantum'])for(const type of ['proton','neutron']){
  await page.click('[data-model="'+model+'"]');await page.selectOption('#particle-list',type);const prior=await page.evaluate(()=>{const s=Copper.app.state;return {model:s.model,yaw:s.yaw,pitch:s.pitch,zoom:s.zoom,selected:s.selected,paused:s.paused};});
  await page.locator('#explore-inside').focus();await page.keyboard.press('Enter');await settled();assert.equal(await view(),'nucleon');
  assert.equal(await page.locator('#charge-equation').innerText(),type==='proton'?'+⅔ + +⅔ − ⅓ = +1':'+⅔ − ⅓ − ⅓ = 0');
  assert.deepEqual(await page.evaluate(()=>Copper.app.renderer.components.map(c=>c.flavor)),type==='proton'?['up','up','down']:['up','down','down']);
  for(const level of ['elementary','middle','high']){await page.click('[data-level="'+level+'"]');for(const category of ['up','down','gluon','whole']){await page.selectOption('#internal-selector',category);assert.ok((await page.locator('#internal-component').innerText()).length>15);}}
  const camera=await page.evaluate(()=>[Copper.app.state.yaw,Copper.app.state.pitch,Copper.app.state.zoom]);await page.click('[data-level="middle"]');assert.deepEqual(await page.evaluate(()=>[Copper.app.state.yaw,Copper.app.state.pitch,Copper.app.state.zoom]),camera);assert.equal(await page.evaluate(()=>Copper.app.state.internalSelected),'whole');
  await page.click('#internal-clear');assert.equal(await page.evaluate(()=>Copper.app.state.internalSelected),null);
  await page.click('#back-atom');assert.equal(await view(),'atom');assert.deepEqual(await page.evaluate(()=>{const s=Copper.app.state;return {model:s.model,yaw:s.yaw,pitch:s.pitch,zoom:s.zoom,selected:s.selected,paused:s.paused};}),prior);assert.equal(await page.evaluate(()=>JSON.stringify(Copper.app.atom)),science);
 }
 // Visible pointer locations taken from renderer, with matching pick results.
 const target=async type=>{await page.evaluate(()=>{Copper.app.state.zoom=3;Copper.app.draw();});await page.locator('#atom').scrollIntoViewIfNeeded();return page.evaluate(type=>{const a=Copper.app,r=a.renderer,b=a.canvas.getBoundingClientRect(),h=r.hits.find(h=>h.p.type===type&&r.isVisible(h)&&r.pick(h.x,h.y)===h.p.id);return {id:h.p.id,x:b.x+h.x,y:b.y+h.y};},type);};
 for(const type of ['proton','neutron']){const point=await target(type);await page.mouse.click(point.x,point.y);assert.equal(await view(),'atom');assert.equal(await page.evaluate(()=>Copper.app.state.selected),point.id);await page.waitForTimeout(700);await page.mouse.dblclick(point.x,point.y,{delay:180});await settled();assert.equal(await page.evaluate(()=>Copper.app.state.nucleon),type);await page.keyboard.press('Escape');assert.equal(await view(),'atom');}
 // Emulated double tap and accessible button tap.
 const cdp=await context.newCDPSession(page),touch=async(point)=>{await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:Math.round(point.x),y:Math.round(point.y),id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});};
 const point=await target('neutron');await touch(point);await page.waitForTimeout(160);await touch(point);await settled();assert.equal(await page.evaluate(()=>Copper.app.state.nucleon),'neutron');await page.click('#back-atom');
 await page.selectOption('#particle-list','proton');await page.locator('#explore-inside').tap();await settled();assert.equal(await view(),'nucleon');await page.click('#back-atom');
 // A drag invalidates the double-tap chain, even if it returns to its start.
 const drag=await target('proton');await page.mouse.click(drag.x,drag.y);await page.mouse.move(drag.x,drag.y);await page.mouse.down();await page.mouse.move(drag.x+30,drag.y+20);await page.mouse.move(drag.x,drag.y);await page.mouse.up();await page.mouse.click(drag.x,drag.y);assert.equal(await view(),'atom');
 // Smooth transition remains active at half a second, finishes in ~1.5s.
 await page.emulateMedia({reducedMotion:'no-preference'});await page.selectOption('#particle-list','proton');await page.click('#explore-inside');await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>Copper.app.state.transitioning),true);await settled();
 // Direct quark, field, and boundary selection.
 for(const category of ['up','down','gluon','whole']){
  const point=await page.evaluate(category=>{const r=Copper.app.renderer,b=Copper.app.canvas.getBoundingClientRect();let h;if(['up','down'].includes(category))h=r.hits.find(h=>h.p.flavor===category);else if(category==='gluon')h=r.fieldHits.find(h=>r.pick(h.x,h.y)==='gluon');else h={x:r.boundary.x+r.boundary.r,y:r.boundary.y};return {x:b.x+h.x,y:b.y+h.y};},category);await page.mouse.click(point.x,point.y);assert.ok(await page.evaluate(()=>Copper.app.state.internalSelected));
 }
 await page.click('#pause');const t=await page.evaluate(()=>Copper.app.state.time);await page.waitForTimeout(100);assert.ok(await page.evaluate(()=>Copper.app.state.time)>t);await page.click('#pause');
 const box=await page.locator('#atom').boundingBox();await page.mouse.move(box.x+200,box.y+200);await page.mouse.down();await page.mouse.move(box.x+240,box.y+230);await page.mouse.up();assert.ok(await page.evaluate(()=>Copper.app.state.yaw>.3&&Copper.app.state.pitch<.2));await page.mouse.wheel(0,-100);await page.waitForTimeout(50);assert.ok(await page.evaluate(()=>Copper.app.state.zoom>1));await page.click('#reset');assert.equal(await page.evaluate(()=>Copper.app.state.zoom),1);
 // Fullscreen from within, and entry/return while fullscreen was already active.
 await page.click('#fullscreen');assert.equal(await page.evaluate(()=>!!document.fullscreenElement),true);assert.equal(await page.locator('#internal-panel').isVisible(),false);assert.equal(await page.locator('#presentation-back').isVisible(),true);await page.click('#presentation-back');assert.equal(await view(),'atom');assert.equal(await page.evaluate(()=>Copper.app.state.presentation),true);
 await page.evaluate(()=>Copper.app.enterNucleon(Copper.app.particles.find(p=>p.type==='neutron').id));await settled();assert.equal(await page.evaluate(()=>Copper.app.state.presentation),true);await page.click('#exit-fullscreen');assert.equal(await view(),'nucleon');assert.equal(await page.evaluate(()=>Copper.app.state.presentation),false);await page.keyboard.press('Escape');assert.equal(await view(),'atom');
 // Resource disposal and constant physical inventory after repeated entries.
 const cycles=await page.evaluate(()=>{const a=Copper.app;for(let i=0;i<30;i++){a.enterNucleon(a.particles.find(p=>p.type===(i%2?'proton':'neutron')).id);const old=a.renderer;a.backToAtom();if(old.hits.length||old.components.length||old.fieldHits.length)throw Error('Undisposed resources');}return {count:a.particles.length,renderers:Object.keys(a.renderers).length,view:a.state.view};});assert.deepEqual(cycles,{count:92,renderers:3,view:'atom'});
 await page.emulateMedia({reducedMotion:'reduce'});
 for(const width of [320,390,768,1366]){await page.setViewportSize({width,height:900});for(const type of ['proton','neutron']){await page.selectOption('#particle-list',type);await page.click('#explore-inside');await settled();for(const level of ['elementary','middle','high']){await page.click('[data-level="'+level+'"]');await page.selectOption('#internal-selector','whole');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('#internal-panel').evaluate(e=>e.scrollWidth>e.clientWidth),false);}await page.screenshot({path:'qa/phase3-'+width+'-'+type+'.png',fullPage:true});await page.click('#back-atom');}}
 assert.equal(await page.evaluate(()=>JSON.stringify(Copper.app.atom)),science);assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);console.log(JSON.stringify({result:'PASS',cycles,errors,remote,checks:'all models, both nucleons, exact charges, mouse/doubletap, keyboard/touch Explore, drag rejection, transition, components, levels, restoration, fullscreen, 30 disposal cycles, 4 widths'},null,2));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
