const {chromium}=require('C:/Users/arial/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('url'),path=require('path'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[],remote=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith('file:'))remote.push(r.url());});
 const url=pathToFileURL(path.resolve('periodic-table-visualizer/index.html')).href;await p.goto(url+'#explore=Ta');
 const negative=await p.evaluate(()=>{const C=Copper;let n=0;for(const z of [78,79]){const e=structuredClone(C.elements[z]);e.neutralSubshells.find(s=>s.id==='5d').occupancy--;e.neutralSubshells.find(s=>s.id==='6s').occupancy++;e.neutralShells[4]--;e.neutralShells[5]++;e.neutralConfiguration=C.fullConfiguration(e.neutralSubshells);e.fullConfiguration=e.neutralConfiguration;if(C.validateHeavyDData({[z]:e}).ok)throw Error('Simple filling overwrite accepted');n++;}
 const original=C.isotopes['tantalum-180m'];for(const mutate of [i=>i.observationallyStable=false,i=>i.stable=false,i=>i.halfLife={value:1.5e19,unit:'years',display:'A search bound'},i=>i.metastableStateLabel=null,i=>i.excitationStateId='ground',i=>i.excitationEnergyKeV=0,i=>i.groundState.selectable=true,i=>i.naturalComponent=false,i=>i.decayModes=['Unobserved alpha'],i=>i.primaryDecay='Unobserved decay']){const i=structuredClone(original);mutate(i);if(C.validateHeavyDData({73:C.elements[73]},{...C.isotopes,[i.id]:i}).ok)throw Error('Incoherent isomer accepted');n++;}
 for(const id of ['technetium-99m','silver-110m','tin-117m']){const i=C.isotopes[id];if(!i)throw Error('Missing old isomer');const bad={...structuredClone(i),stable:true};let rejected=false;try{C.createAtom({element:C.elements[i.atomicNumber],isotope:bad});}catch{rejected=true;}if(!rejected)throw Error('Produced isomer became stable');n++;}return n;});assert.equal(negative,15);
 assert.equal(await p.locator('#isotope-select option[value="tantalum-180"]').count(),0);
 assert.equal(await p.locator('#isotope-select option[value="tantalum-180m"]').evaluate(e=>e.parentElement.label),'Observationally stable');
 let cases=0;for(const model of ['bohr','wave','quantum']){await p.click('[data-model="'+model+'"]');for(const level of ['elementary','middle','high']){await p.click('[data-level="'+level+'"]');await p.selectOption('#isotope-select','tantalum-180m');await p.locator('#isotope-information details').evaluateAll(es=>es.forEach(e=>e.open=true));
 assert.match(await p.locator('#stability').innerText(),/Observationally stable.*nuclear isomer/);assert.equal(await p.locator('#isotope-half-life').isVisible(),false);assert.equal(await p.locator('#isotope-decay').isVisible(),false);assert.match(await p.locator('#isotope-nuclear-state').innerText(),/extra energy|excited/);assert.match(await p.locator('#nuclear-symbol').innerText(),/ᵐ/);assert.match(await p.locator('.abundance-labels').innerText(),/Tantalum-180m: 0.01176/);assert.match(await p.locator('#abundance-bar').getAttribute('aria-label'),/Tantalum-180m/);
 assert.deepEqual(await p.evaluate(()=>{const a=Copper.app.atom;return [a.protons,a.neutrons,a.electrons,a.massNumber,a.isotope.excitationEnergyKeV,a.shells];}),[73,107,73,180,76.79,[2,8,18,32,11,2]]);
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.locator('#isotope-information').evaluate(e=>e.scrollWidth>e.clientWidth),false);
 await p.selectOption('#particle-list','neutron');await p.click('#explore-inside');await p.waitForFunction(()=>Copper.app.state.view==='nucleon'&&!Copper.app.state.transitioning);assert.match(await p.locator('#breadcrumb').innerText(),/Tantalum-180m/);await p.click('#back-atom');await p.selectOption('#isotope-select','tantalum-181');assert.equal(await p.evaluate(()=>Copper.app.atom.neutrons),108);assert.equal(await p.locator('#isotope-nuclear-state').isVisible(),false);cases++;}}
 await p.selectOption('#isotope-select','tantalum-180m');await p.screenshot({path:'qa/phase6j-Ta180m-phone.png',fullPage:true});
 await p.goto(url+'#explore=Os');await p.selectOption('#isotope-select','osmium-184');assert.match(await p.locator('#stability').innerText(),/Observationally stable/);assert.equal(await p.locator('#isotope-half-life').isVisible(),false);await p.selectOption('#isotope-select','osmium-186');assert.equal(await p.locator('#isotope-half-life').evaluate(e=>e.hidden),false);
 for(const symbol of ['Pt','Au']){await p.goto(url+'#explore='+symbol);assert.equal(await p.evaluate(()=>Copper.app.atom.shells.at(-1)),1);assert.equal(await p.locator('#particle-list option[value="valence-electron"]').textContent(),'Outermost 6s electron');await p.click('[data-level="high"]');assert.match(await p.locator('#period-progression p').textContent(),symbol==='Au'?/relativistic/:/5d⁹ 6s¹/);}
 await p.goto(url+'#explore=Cu');assert.equal(await p.locator('#isotope-half-life').evaluate(e=>e.hidden),false);
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);const out={result:'PASS',negativeCases:negative,isomerModelLevelCases:cases,errors,remote};fs.writeFileSync('qa/phase6j-isomers-results.json',JSON.stringify(out,null,2));console.log(out);
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
