const {chromium}=require('C:/Users/arial/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),{pathToFileURL}=require('url'),path=require('path'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[],remote=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith('file:'))remote.push(r.url());});const url=pathToFileURL(path.resolve('periodic-table-visualizer/index.html')).href;await p.goto(url+'#explore=Cu');await p.evaluate(()=>{const a=Copper.app,load=a.loadAtom;a.loadAtom=function(...args){window.loadCount++;return load.apply(this,args);};window.loadCount=0;});const massRejections=await p.evaluate(()=>{let count=0;for(const z of [84,85,86]){const records=structuredClone(Copper.basicElements);records.find(e=>e.atomicNumber===z).mass={kind:'standard',value:'209',uncertainty:'1'};if(Copper.validatePeriodicData(records).ok)throw Error('Bracketed mass overwritten');count++;}return count;});assert.equal(massRejections,3);let entries=0,panels=0;
 for(const [symbol,mass] of [['Hg','200.59'],['Tl','204.38'],['Pb','207.2'],['Bi','208.98'],['Po','[209]'],['At','[210]'],['Rn','[222]']]){await p.click('#back-table');await p.evaluate(()=>window.loadCount=0);const tile=p.locator('#tile-'+symbol);assert.equal(await tile.locator('.element-mass').textContent(),mass);await tile.scrollIntoViewIfNeeded();assert.equal(await tile.evaluate(e=>{const n=e.querySelector('.element-number').getBoundingClientRect(),m=e.querySelector('.element-mass').getBoundingClientRect();return n.right>m.left&&n.bottom>m.top&&m.bottom>n.top;}),false);await tile.dblclick();await p.waitForFunction(s=>Copper.applicationState.page==='explorer'&&Copper.app.atom.element.symbol===s,symbol);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>window.loadCount),1);entries++;
  for(const level of ['elementary','middle','high']){await p.click('[data-level="'+level+'"]');await p.locator('#isotope-information details').evaluateAll(es=>es.forEach(e=>e.open=true));const ids=await p.locator('#isotope-select option').evaluateAll(es=>es.map(e=>e.value));for(const id of ids){await p.selectOption('#isotope-select',id);const stable=await p.evaluate(()=>Copper.app.atom.isotope.stable);assert.equal(await p.locator('#isotope-half-life').evaluate(e=>e.hidden),stable);const text=await p.locator('#isotope-information').innerText();assert.equal(/copper|63\.546|29 protons/i.test(text),false);assert.equal(await p.locator('#isotope-information').evaluate(e=>e.scrollWidth>e.clientWidth),false);panels++;}
   const text=await p.locator('#particle-info').innerText();assert.equal(/copper/i.test(text),false);if(['Po','At','Rn'].includes(symbol))assert.match(await p.locator('#weighted-explanation').textContent(),/not an average|not an average atomic mass|not a weighted average/);
  }
  if(symbol==='Bi'){assert.match(await p.locator('#stability').textContent(),/^Radioactive|☢Radioactive/);assert.match(await p.locator('#isotope-uses').textContent(),/effectively stable/);assert.equal(await p.evaluate(()=>Copper.app.atom.isotope.halfLife.value),2.01e19);}
  if(['Tl','Pb'].includes(symbol)){assert.equal(await p.locator('#abundance-bar').isVisible(),false);assert.match(await p.locator('.abundance-labels').textContent(),/–/);}
  await p.screenshot({path:'qa/phase6k-'+symbol+'-expanded-phone.png',fullPage:true});
 }
 await p.click('[data-level="high"]');assert.match(await p.locator('.conduction p').textContent(),/Colorless and odorless/);assert.match(await p.locator('.conduction p').textContent(),/lung-cancer/);assert.match(await p.locator('.conduction p').textContent(),/mitigation/);
 await p.click('#back-table');await p.click('#tile-Rn');assert.equal(await p.locator('.mass-value').textContent(),'[222]');assert.match(await p.locator('.mass-label').textContent(),/Representative isotope/);await p.setViewportSize({width:1366,height:1000});await p.locator('#tile-Rn').scrollIntoViewIfNeeded();await p.locator('#tile-Rn').screenshot({path:'qa/phase6k-Rn-tile.png'});
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);const out={result:'PASS',singleEntryDoubleClicks:entries,massRejections,isotopeLevelPanels:panels,checks:'Published mass labels; no header overlap; one load per double-click; no copper examples; readable isotope panels; half-life only for radioactive choices; Bi-209 and bracketed masses; Tl/Pb ranges; radon risk and mitigation',errors,remote};fs.writeFileSync('qa/phase6k-content-results.json',JSON.stringify(out,null,2));console.log(out);
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
