const {chromium}=require('C:/Users/arial/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),{pathToFileURL}=require('url'),path=require('path'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:1366,height:1000},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));const url=pathToFileURL(path.resolve('periodic-table-visualizer/index.html')).href;await p.goto(url+'#explore=Tc');await p.waitForFunction(()=>Copper.app?.atom.protons===43);
 const invalid=await p.evaluate(()=>{const C=Copper,e=C.elements[43],i=C.isotopes['technetium-99m'];return [x=>x.massNumber++,x=>x.groundState.atomicNumber++,x=>delete x.groundState,x=>x.excitationStateId='ground',x=>x.stable=true,x=>x.neutralElectronCount--,x=>x.naturalAbundance={percent:1},x=>x.excitationEnergyKeV=0].map(f=>{const copy=structuredClone(i);f(copy);return C.validateRecord(e,copy).ok;});});assert.deepEqual(invalid,Array(8).fill(false));let cases=0;
 for(const model of ['bohr','wave','quantum'])for(const level of ['elementary','middle','high']){await p.click('[data-model="'+model+'"]');await p.click('[data-level="'+level+'"]');await p.selectOption('#isotope-select','technetium-99');await p.selectOption('#particle-list','proton');await p.evaluate(()=>{const a=Copper.app;a.state.yaw=.4;a.state.pitch=.5;a.state.zoom=1.1;a.draw();window.savedIsomer={particles:a.particles,objects:[...a.particles],geometry:JSON.stringify(a.particles),renderers:Object.values(a.renderers),state:[a.state.selected,a.state.model,a.state.yaw,a.state.pitch,a.state.zoom,a.state.paused,a.state.time],make:Copper.makeNucleus};Copper.makeNucleus=()=>{throw Error('State-only switch rebuilt the nucleus');};});
  for(const id of ['technetium-99m','technetium-99','technetium-99m']){await p.selectOption('#isotope-select',id);assert.deepEqual(await p.evaluate(()=>{const a=Copper.app,s=window.savedIsomer;return {array:a.particles===s.particles,objects:a.particles.every((v,i)=>v===s.objects[i]),geometry:JSON.stringify(a.particles)===s.geometry,renderers:s.renderers.every(r=>Object.values(a.renderers).includes(r)&&r.atom===a.atom&&r.particles===a.particles),state:JSON.stringify([a.state.selected,a.state.model,a.state.yaw,a.state.pitch,a.state.zoom,a.state.paused,a.state.time])===JSON.stringify(s.state),counts:[a.atom.protons,a.atom.neutrons,a.atom.electrons]};}),{array:true,objects:true,geometry:true,renderers:true,state:true,counts:[43,56,43]});assert.match(await p.locator('#isotope-nuclear-state').innerText(),/same|not particle counts/);cases++;}
  await p.evaluate(()=>{Copper.makeNucleus=window.savedIsomer.make;delete window.savedIsomer;});assert.match(await p.locator('#nuclear-symbol').innerText(),/ᵐ/);assert.match(await p.locator('#presentation-model').textContent(),/Technetium-99m/);await p.click('#fullscreen');assert.match(await p.locator('#presentation-model').innerText(),/99m/);await p.click('#exit-fullscreen');await p.click('#explore-inside');assert.match(await p.locator('#breadcrumb').innerText(),/Technetium-99m/);await p.click('#back-atom');
 }
 await p.goto(url+'#explore=Ag');await p.waitForFunction(()=>Copper.app?.atom.protons===47);await p.selectOption('#isotope-select','silver-110m');assert.deepEqual(await p.evaluate(()=>[Copper.app.atom.protons,Copper.app.atom.neutrons,Copper.app.atom.electrons,Copper.app.atom.isotope.groundState.id]),[47,63,47,'silver-110']);assert.match(await p.locator('#isotope-nuclear-state').innerText(),/Silver-110/);await p.goto(url+'#explore=Pd');await p.waitForFunction(()=>Copper.app?.atom.protons===46);assert.equal(await p.locator('#isotope-nuclear-state').isVisible(),false);
 const validation=await p.evaluate(()=>{const C=Copper,v=C.validatePeriod5TransitionData();for(const e of Object.values(C.elements).filter(e=>e.atomicNumber>=41)){const nat=e.availableIsotopes.map(id=>C.isotopes[id]).filter(i=>i.naturalAbundance);if(nat.some(i=>i.naturalAbundance.rangePercent)){for(const i of nat){const range=i.naturalAbundance.rangePercent;if(!range||range.length!==2||range[0]<0||range[1]>100||range[0]>range[1])throw Error('abundance range '+e.symbol);}}else if(nat.length&&Math.abs(nat.reduce((n,i)=>n+i.naturalAbundance.percent,0)-(e.atomicNumber===72?100.011:100))>.00001)throw Error('abundance sum '+e.symbol);}return v;});assert.equal(validation.ok,true);assert.deepEqual(errors,[]);const out={result:'PASS',stateOnlySwitches:cases,invalidRecordsRejected:invalid.length,validation,errors};fs.writeFileSync('qa/phase7b-isomers-results.json',JSON.stringify(out,null,2));console.log(out);
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
