const {chromium}=require('C:/Users/arial/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('url'),path=require('path'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage(),errors=[],remote=[],missing=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(!r.url().startsWith('file:'))remote.push(r.url());});page.on('requestfailed',r=>missing.push(r.url()));
 const url=pathToFileURL(path.resolve('periodic-table-visualizer/index.html')).href;
 const table=async()=>{await page.click('#back-table');await page.waitForFunction(()=>Copper.applicationState.page==='table');};
 const opened=async symbol=>page.waitForFunction(symbol=>Copper.applicationState.page==='explorer'&&Copper.app?.atom.element.symbol===symbol,symbol);
 await page.goto(url);assert.deepEqual(await page.evaluate(()=>Copper.basicElements.filter(e=>e.explorerAvailable).map(e=>e.symbol)),['H','He','Li','Be','B','C','N','O','F','Ne','Na','Mg','Al','Si','P','S','Cl','Ar','K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr','Rb','Sr','Y','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd','In','Sn','Sb','Te','I','Xe','Cs','Ba','La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu','Hf','Ta','W','Re','Os','Ir','Pt','Au','Hg','Tl','Pb','Bi','Po','At','Rn','Fr','Ra','Ac','Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds']);assert.equal(await page.evaluate(()=>Copper.hydrogenValidation.ok),true);
 // Native mouse sequence: a single click selects only, double-click routes via the same hash.
 await page.click('#tile-H');assert.equal(await page.locator('#selected-element-title').innerText(),'Hydrogen');assert.equal(await page.evaluate(()=>!!Copper.app),false);await page.dblclick('#tile-H');await opened('H');assert.equal(await page.locator('#explorer-title').innerText(),'Hydrogen Atom Explorer');
 await table();await page.dblclick('#tile-Cu');await opened('Cu');await table();await page.dblclick('#tile-Rg');await page.waitForFunction(()=>Copper.applicationState.selectedElement==='Rg');assert.equal(await page.evaluate(()=>Copper.applicationState.page),'table');assert.equal(await page.locator('#explore-element').count(),0);
 for(const symbol of ['H','Cu']){await page.locator('#tile-'+symbol).focus();await page.keyboard.press('Space');await page.waitForFunction(symbol=>Copper.applicationState.selectedElement===symbol,symbol);await page.locator('#explore-element').focus();await page.keyboard.press('Enter');await opened(symbol);await table();}
 await page.click('[data-table-view="list"]');await page.dblclick('#list-H');await opened('H');await table();await page.click('[data-table-view="table"]');
 // Two touchscreen taps retain the card. No custom touch shortcut overrides browser gestures.
 await page.locator('#tile-H').tap();await page.locator('#tile-H').tap();assert.equal(await page.evaluate(()=>Copper.applicationState.page),'table');
 await page.click('#explore-element');await opened('H');
 const scientific=[];
 for(const [mass,nickname] of [[1,'Protium'],[2,'Deuterium'],[3,'Tritium']]){
  await page.selectOption('#isotope-select','hydrogen-'+mass);
  const data=await page.evaluate(()=>{const C=Copper,a=C.app.atom;return {p:a.protons,n:a.neutrons,e:a.electrons,shells:a.shells,sub:C.fullConfiguration(a.subshells),stable:a.isotope.stable,half:a.isotope.halfLife,charge:a.charge};});
  assert.deepEqual([data.p,data.n,data.e,data.shells,data.sub,data.stable,data.charge],[1,mass-1,1,[1],'1s¹',mass!==3,0]);if(mass===3){assert.equal(data.half.value,12.3);assert.equal(data.half.unit,'years');assert.match(await page.locator('#isotope-decay').innerText(),/Beta-minus/);assert.match(await page.locator('#isotope-half-life').innerText(),/12.3 years/);}scientific.push(data);
  assert.equal(await page.locator('#isotope-select option:checked').innerText(),'Hydrogen-'+mass+' ('+nickname+')');assert.equal(await page.locator('#particle-list option[value="neutron"]').isDisabled(),mass===1);assert.equal(await page.locator('#particle-list option[value="inner-electron"]').count(),0);
  for(const model of ['bohr','wave','quantum']){
   await page.click('[data-model="'+model+'"]');await page.click('#reset');
   const r=await page.evaluate(()=>{const a=Copper.app,r=a.renderer;return {electrons:r.hits.filter(h=>h.p.type==='electron').length,n:r.hits.filter(h=>h.p.type==='neutron').length,extent:Copper.displayExtent(a.atom),objects:r.electronObjects().map(o=>o.kind),waves:[...new Set((r.regionHits||[]).map(h=>h.p.shell))],subs:r.clouds?.map(c=>c.sub.id),layers:r.visibleLayers};});
   assert.equal(r.n,mass-1);assert.equal(r.extent,76);
   if(model==='bohr'){assert.equal(r.electrons,1);assert.equal(r.objects.filter(k=>k==='line').length,120);}
   else {assert.equal(r.electrons,0);assert.deepEqual(r.objects,[]);assert.deepEqual(r.waves,[1]);}
   if(model==='wave'){const closed=await page.evaluate(()=>{const h=Copper.app.renderer.regionHits;return Math.hypot(h[0].x-h.at(-1).x,h[0].y-h.at(-1).y);});assert.ok(closed<.001);}
   if(model==='quantum'){
    assert.deepEqual(r.subs,['1s']);assert.equal(r.layers,1);await page.click('[data-quantum="explore"]');assert.deepEqual(await page.locator('#subshell option:not([value="all"])').evaluateAll(es=>es.map(e=>e.value)),['1s']);assert.match(await page.locator('#quantum-summary').innerText(),/1s¹/);assert.equal(await page.evaluate(()=>Copper.app.renderer.visibleLayers),1);await page.click('[data-quantum="overview"]');
    const shape=await page.evaluate(()=>{const pts=Copper.app.renderer.clouds[0].points,R=Copper.app.renderer.clouds[0].radius;const variance=['x','y','z'].map(k=>pts.reduce((n,p)=>n+p[k]**2,0)/pts.length);const inner=pts.filter(p=>Math.hypot(p.x,p.y,p.z)<R*.25).length,outer=pts.filter(p=>Math.hypot(p.x,p.y,p.z)>R*.75).length;return {ratio:Math.max(...variance)/Math.min(...variance),densityRatio:(inner/.25**3)/(outer/(1-.75**3))};});assert.ok(shape.ratio<1.2);assert.ok(shape.densityRatio>3);
   }
   for(const category of ['proton',...(mass>1?['neutron']:[]),'valence-electron']){
    await page.selectOption('#particle-list',category);assert.equal(await page.evaluate(()=>Copper.categoryFor(Copper.app.selectionTarget(Copper.app.state.selected))),category);
    if(category==='valence-electron')assert.match(await page.locator('#particle-info').innerText(),/one electron|single electron/);
    else {await page.click('#explore-inside');await page.waitForTimeout(220);assert.match(await page.locator('#breadcrumb').innerText(),new RegExp('Hydrogen-'+mass));assert.equal(await page.evaluate(()=>Copper.nucleonCharge(Copper.app.state.nucleon).value),category==='proton'?1:0);await page.click('#fullscreen');assert.equal(await page.evaluate(()=>Copper.app.state.presentation),true);await page.click('#exit-fullscreen');await page.click('#back-atom');}
   }
   for(const level of ['elementary','middle','high']){await page.click('[data-level="'+level+'"]');if(await page.locator('#clear').isVisible())await page.click('#clear');const text=await page.locator('#explorer-page').innerText();assert.equal(/copper/i.test(text),false,'Copper content leaked into hydrogen');assert.match(await page.locator('#isotope-why').innerText(),new RegExp(mass===1?'Hydrogen-1':nickname));}
   if(mass===1)await page.locator('#stage').screenshot({path:'qa/phase51-hydrogen-'+model+'.png'});
  }
 }
 // Native particle double-click still enters a proton.
 await page.click('[data-model="bohr"]');await page.selectOption('#particle-list','proton');const hit=await page.evaluate(()=>{const a=Copper.app,h=a.renderer.hits.find(h=>h.p.id===a.state.selected),r=a.canvas.getBoundingClientRect();return {x:r.left+h.x,y:r.top+h.y};});await page.mouse.dblclick(hit.x,hit.y);await page.waitForFunction(()=>Copper.app.state.view==='nucleon');await page.waitForTimeout(220);await page.click('#back-atom');
 // Camera, animation and isotope remain unchanged by presentation.
 await page.click('#reset');await page.click('#pause');await page.locator('#atom').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('+');const before=await page.evaluate(()=>{const a=Copper.app;return [a.atom.isotope.id,a.state.model,a.state.yaw,a.state.pitch,a.state.zoom,a.state.paused];});await page.click('#fullscreen');await page.click('#exit-fullscreen');assert.deepEqual(await page.evaluate(()=>{const a=Copper.app;return [a.atom.isotope.id,a.state.model,a.state.yaw,a.state.pitch,a.state.zoom,a.state.paused];}),before);await page.click('#pause');
 // Pointer rotation and wheel zoom use the same engine controls for hydrogen.
 await page.locator('#atom').scrollIntoViewIfNeeded();const box=await page.locator('#atom').boundingBox(),x=box.x+box.width*.7,y=box.y+box.height*.5;const yaw=await page.evaluate(()=>Copper.app.state.yaw);await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+40,y+20,{steps:5});await page.mouse.up();assert.notEqual(await page.evaluate(()=>Copper.app.state.yaw),yaw);const zoom=await page.evaluate(()=>Copper.app.state.zoom);await page.mouse.wheel(0,-120);await page.waitForTimeout(100);assert.ok(await page.evaluate(z=>Copper.app.state.zoom>z,zoom));
 await table();await page.fill('#element-search','1');await page.click('[data-family="nonmetal"]');await page.press('#element-search','Enter');const scroll=await page.locator('#table-scroll').evaluate(e=>e.scrollLeft);await page.click('#explore-element');await opened('H');await table();assert.equal(await page.locator('#element-search').inputValue(),'1');assert.equal(await page.locator('[data-family="nonmetal"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#table-scroll').evaluate(e=>e.scrollLeft),scroll);await page.goBack();await opened('H');await page.goForward();await page.waitForFunction(()=>Copper.applicationState.page==='table');
 for(const symbol of ['H','Cu']){await page.goto(url+'#explore='+symbol);await page.reload();await opened(symbol);assert.equal(await page.title(),(symbol==='H'?'Hydrogen':'Copper')+' Atom Explorer');}
 await page.goto(url+'#explore=Rg');await page.waitForFunction(()=>location.hash==='#element=Rf');assert.equal(await page.locator('#periodic-page').isVisible(),true);
 // Disposal and framing over 40 actual route changes, including all model caches.
 const cycle=async count=>{for(let n=0;n<count;n++){const symbol=n%2?'Cu':'H';await page.evaluate(()=>{window.oldRenderers=Object.values(Copper.app.renderers);window.oldAtom=Copper.app.atom;});await page.goto(url+'#explore='+symbol);await opened(symbol);const resource=await page.evaluate(()=>{const a=Copper.app;for(const model of ['bohr','wave','quantum']){a.switchModel(model);a.draw();}return {disposed:oldAtom===a.atom||oldRenderers.every(r=>!r.particles.length&&!r.hits.length&&!r.clouds?.length),particles:a.particles.length,unique:new Set(a.particles.map(p=>p.id)).size,renderers:Object.keys(a.renderers).length,extent:Copper.displayExtent(a.atom)};});assert.equal(resource.disposed,true);assert.equal(resource.particles,resource.unique);assert.equal(resource.renderers,3);assert.equal(resource.extent,symbol==='H'?76:214);assert.equal(resource.particles,symbol==='H'?2:92);}};
 await page.goto(url+'#explore=Cu');await opened('Cu');const cdp=await context.newCDPSession(page);await cdp.send('Performance.enable');const heap=async()=>Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value])).JSHeapUsedSize;await cycle(4);await cdp.send('HeapProfiler.collectGarbage');const heapBefore=await heap();await cycle(40);await cdp.send('HeapProfiler.collectGarbage');const heapAfter=await heap();assert.ok(heapAfter-heapBefore<4*1024*1024);
 const widths=[320,390,768,1024,1366,1920];for(const width of widths){await page.setViewportSize({width,height:900});await page.goto(url+'#explore=H');await opened('H');await page.selectOption('#isotope-select','hydrogen-3');for(const model of ['bohr','wave','quantum']){await page.click('[data-model="'+model+'"]');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('#particle-info').evaluate(e=>e.scrollWidth>e.clientWidth),false);}await page.screenshot({path:'qa/phase51-'+width+'.png',fullPage:true});}
 // Touch drag/pinch on canvas; native scrolling over tiles cannot enter an explorer.
 await page.setViewportSize({width:390,height:844});await page.click('[data-model="bohr"]');await page.click('#reset');await page.locator('#atom').scrollIntoViewIfNeeded();const tb=await page.locator('#atom').boundingBox(),tx=tb.x+tb.width/2,ty=tb.y+tb.height/2;let state=await page.evaluate(()=>[Copper.app.state.yaw,Copper.app.state.zoom]);
 const touch=(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(([x,y,id])=>({x,y,id,radiusX:2,radiusY:2}))});await touch('touchStart',[[tx,ty,1]]);await touch('touchMove',[[tx+35,ty+10,1]]);await touch('touchEnd',[]);assert.notEqual(await page.evaluate(()=>Copper.app.state.yaw),state[0]);await touch('touchStart',[[tx-30,ty,1],[tx+30,ty,2]]);await touch('touchMove',[[tx-60,ty,1],[tx+60,ty,2]]);await touch('touchEnd',[]);assert.ok(await page.evaluate(z=>Copper.app.state.zoom>z,state[1]));
 await table();await page.click('#clear-search');await page.click('#clear-filters');await page.locator('#tile-H').scrollIntoViewIfNeeded();const tile=await page.locator('#tile-H').boundingBox(),px=tile.x+tile.width/2,py=tile.y+tile.height/2;await touch('touchStart',[[px,py,1]]);await touch('touchMove',[[px+100,py-30,1]]);await touch('touchEnd',[]);assert.equal(await page.evaluate(()=>Copper.applicationState.page),'table');await touch('touchStart',[[px,py,1],[px+60,py,2]]);await touch('touchMove',[[px-10,py,1],[px+80,py,2]]);await touch('touchEnd',[]);assert.equal(await page.evaluate(()=>Copper.applicationState.page),'table');
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);assert.deepEqual(missing,[]);const report={result:'PASS',available:['H','Cu'],isotopes:scientific,models:3,levels:3,widths,routeSwitches:44,heapGrowth:heapAfter-heapBefore,errors,remote,missing,checks:'single/double click, unavailable guard, list, keyboard, touch taps/scroll/pinch, hydrogen isotopes and models, occupied 1s, spherical density, both nucleon interiors and charges, fullscreen, mouse/touch rotation and zoom, offline routing/history/reload/state, disposal and responsive panels'};fs.writeFileSync('qa/phase51-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

