const {chromium}=require('C:/Users/arial/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('url'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const context=await browser.newContext({viewport:{width:1366,height:900},hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage(),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>requests.push(r.url()));
 await page.goto(pathToFileURL(path.resolve('periodic-table-visualizer/index.html')).href+'#explore=Cu');
 assert.equal(await page.locator('#isotope-select').inputValue(),'copper-63');assert.deepEqual(await page.locator('#isotope-select option').allTextContents(),['Copper-63','Copper-65','Copper-64','Copper-67']);
 await page.evaluate(()=>{window.originalElectrons=Copper.app.particles.filter(p=>p.type==='electron');});
 for(const model of ['bohr','wave','quantum']){await page.click('[data-model="'+model+'"]');for(const mass of [63,64,65,67]){
  const camera=await page.evaluate(()=>[Copper.app.state.yaw,Copper.app.state.pitch,Copper.app.state.zoom,Copper.app.state.level]);await page.selectOption('#isotope-select','copper-'+mass);
  const result=await page.evaluate(()=>{const a=Copper.app;return {counts:['proton','neutron','electron'].map(t=>a.particles.filter(p=>p.type===t).length),charge:a.atom.charge,shells:a.atom.shells,mass:a.atom.massNumber,model:a.state.model,electronsSame:a.particles.filter(p=>p.type==='electron').every((p,i)=>p===originalElectrons[i]),renderersSame:Object.values(a.renderers).every(r=>r.atom===a.atom&&r.particles===a.particles)};});
  assert.deepEqual(result,{counts:[29,mass-29,29],charge:0,shells:[2,8,18,1],mass,model,electronsSame:true,renderersSame:true});assert.deepEqual(await page.evaluate(()=>[Copper.app.state.yaw,Copper.app.state.pitch,Copper.app.state.zoom,Copper.app.state.level]),camera);
  assert.equal(await page.locator('#neutrons').innerText(),String(mass-29));assert.match(await page.locator('#nuclear-symbol').getAttribute('aria-label'),new RegExp(String(mass)));
  if([63,65].includes(mass)){assert.match(await page.locator('#isotope-half-life').innerText(),/Stable — no radioactive decay/);assert.equal(await page.locator('#isotope-decay').isVisible(),false);}else{assert.match(await page.locator('#isotope-half-life').innerText(),mass===64?/12.7 hours/:/2.58 days/);assert.match(await page.locator('#stability').innerText(),/Radioactive/);assert.match(await page.locator('#isotope-abundance').innerText(),/Not present/);}
  for(const level of ['elementary','middle','high']){await page.click('[data-level="'+level+'"]');assert.equal(await page.locator('#isotope-select').inputValue(),'copper-'+mass);assert.ok((await page.locator('#cosmic-explanation').textContent()).length>40);}
  for(const type of ['proton','neutron']){await page.selectOption('#particle-list',type);await page.click('#explore-inside');await page.waitForFunction(()=>!Copper.app.state.transitioning);assert.deepEqual(await page.evaluate(()=>Copper.app.renderer.components.map(p=>p.flavor)),type==='proton'?['up','up','down']:['up','down','down']);await page.click('#back-atom');}
 }}
 // Changing while inside must return before rebuilding, even during transition.
 await page.selectOption('#particle-list','neutron');await page.click('#explore-inside');await page.evaluate(()=>Copper.app.setIsotope(Copper.isotopes['copper-65']));assert.equal(await page.evaluate(()=>Copper.app.state.view),'atom');assert.equal(await page.evaluate(()=>Copper.app.state.selected),null);assert.equal(await page.locator('#neutrons').innerText(),'36');
 // Statistical concepts and terrestrial-only bar, with keyboard selection.
 await page.locator('#isotope-select').focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');assert.equal(await page.locator('#isotope-select').evaluate(e=>document.activeElement===e),true);
 await page.selectOption('#isotope-select','copper-63');await page.locator('#isotope-information details').evaluateAll(es=>es.forEach(e=>e.open=true));assert.match(await page.locator('#abundance-bar').getAttribute('aria-label'),/Copper-63 69.15.*Copper-65 30.85/);assert.ok(!(await page.locator('#abundance-comparison').innerText()).includes('Copper-64'));assert.match(await page.locator('#weighted-explanation').innerText(),/62.929597/);
 for(const mass of [63,65,64,67]){await page.selectOption('#isotope-select','copper-'+mass);await page.click('#fullscreen');assert.equal(await page.locator('#isotope-information').isVisible(),false);assert.equal(await page.evaluate(()=>Copper.app.atom.massNumber),mass);await page.click('#exit-fullscreen');}
 const repeated=await page.evaluate(()=>{const a=Copper.app;for(let i=0;i<80;i++)a.setIsotope(Copper.isotopes[['copper-63','copper-65','copper-64','copper-67'][i%4]]);return {cached:Object.keys(a.renderers).length,physical:a.particles.length,electrons:a.particles.filter(p=>p.type==='electron').length};});assert.deepEqual(repeated,{cached:3,physical:96,electrons:29});
 // The isotope replacement function preserves an ion's explicitly supplied state.
 const ion=await page.evaluate(()=>{const C=Copper,a=C.app.atom,i=C.createAtom({element:a.element,isotope:C.isotopes['copper-63'],ion:{charge:1},electronStructure:{shells:[2,8,18],valence:{shells:[3]}}});const changed=C.withIsotope(i,C.isotopes['copper-67']);return [changed.protons,changed.neutrons,changed.electrons,changed.charge];});assert.deepEqual(ion,[29,38,28,1]);
 for(const width of [320,390,768,1366]){await page.setViewportSize({width,height:900});for(const mass of [63,65,64,67]){await page.selectOption('#isotope-select','copper-'+mass);for(const level of ['elementary','middle','high']){await page.click('[data-level="'+level+'"]');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}if(mass===63||mass===67)await page.screenshot({path:'qa/phase4-'+width+'-'+mass+'.png',fullPage:true});}}
 await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(()=>!Copper.app.state.reducedMotion);await page.selectOption('#isotope-select','copper-64');assert.equal(await page.evaluate(()=>Copper.app.state.transitioning),true);await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>Copper.app.state.transitioning),false);
 assert.deepEqual(errors,[]);assert.ok(requests.every(url=>url.startsWith('file:')));console.log(JSON.stringify({result:'PASS',combinations:12,internalViews:24,repeated,errors,remoteRequests:0,checks:'counts, sources present, terrestrial bar, half-lives/status, levels, keyboard/focus, 4 widths, fullscreen, isotope change from nucleon, ion independence, fade'},null,2));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
