const {chromium}=require('C:/Users/arial/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),{pathToFileURL}=require('url'),path=require('path'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:320,height:900},reducedMotion:'reduce'}),errors=[],remote=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith('file:'))remote.push(r.url());});const url=pathToFileURL(path.resolve('periodic-table-visualizer/index.html')).href;let cases=0;
for(const symbol of ['La','Ce','Pr','Nd','Pm','Sm','Eu','Gd']){await p.goto(url+'#explore='+symbol);await p.waitForFunction(s=>Copper.app?.atom.element.symbol===s,symbol);
if(symbol==='Pm'){assert.equal(await p.locator('#isotope-select optgroup[label="Stable"]').count(),0);assert.equal(await p.locator('#abundance-comparison').isVisible(),false);assert.equal(await p.locator('.abundance-labels').textContent(),'');}
if(symbol==='Eu'){await p.selectOption('#isotope-select','europium-151');assert.match(await p.locator('#stability').innerText(),/Radioactive/);assert.match(await p.locator('.abundance-labels').textContent(),/151 \(radioactive\)/);}
if(symbol==='Ce'){await p.selectOption('#isotope-select','cerium-142');assert.equal(await p.evaluate(()=>Copper.app.atom.isotope.halfLife),null);}
for(const width of [320,390,768,1024,1366,1920]){await p.setViewportSize({width,height:900});for(const model of ['bohr','wave','quantum']){await p.click('[data-model="'+model+'"]');for(const level of ['elementary','middle','high']){await p.click('[data-level="'+level+'"]');await p.selectOption('#particle-list','valence-electron');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);for(const id of ['particle-info','configuration','isotope-information'])assert.equal(await p.locator('#'+id).evaluate(e=>e.scrollWidth>e.clientWidth),false);cases++;}}}
const count=await p.evaluate(()=>{const a=Copper.app; a.state.lowDetail=true;let out=[];for(const model of ['bohr','wave','quantum']){a.switchModel(model);a.state.subshell='all';a.state.quantumMode='overview';a.state.selected=null;a.draw();out.push([model,a.renderer.hits.filter(h=>h.p.type!=='electron').length,a.renderer.hits.filter(h=>h.p.type==='electron').length]);}return {mass:a.atom.massNumber,z:a.atom.protons,counts:out};});for(const [model,n,e] of count.counts){assert.equal(n,count.mass);assert.equal(e,model==='bohr'?count.z:0);}await p.setViewportSize({width:390,height:844});await p.click('[data-model="bohr"]');await p.selectOption('#particle-list','valence-electron');await p.locator('#particle-info').screenshot({path:'qa/phase6h-'+symbol+'-particle-phone.png'});}
assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);const data=await p.evaluate(()=>({enabled:Copper.enabledValidation,batch:Copper.lanthanideValidation}));assert.deepEqual(data.enabled,{ok:true,elements:110,isotopes:409,errors:[]});assert.deepEqual(data.batch,{ok:true,elements:15,isotopes:64,errors:[]});const out={result:'PASS',responsiveModelLevelCases:cases,lowDetailCases:24,...data,errors,remote};fs.writeFileSync('qa/phase6h-final-results.json',JSON.stringify(out,null,2));console.log(out);
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
