const {chromium}=require('C:/Users/arial/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('url'),path=require('path'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage(),errors=[],remote=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(!r.url().startsWith('file:'))remote.push(r.url());});page.on('requestfailed',r=>missing.push(r.url()));
 const url=pathToFileURL(path.resolve('periodic-table-visualizer/index.html')).href;await page.goto(url);assert.equal(await page.locator('#periodic-page').isVisible(),true);assert.equal(await page.evaluate(()=>!!Copper.app),false);
 const records=await page.evaluate(()=>Copper.basicElements),facts=JSON.parse(fs.readFileSync('qa/phase5-source-facts.json','utf8'));assert.equal(records.length,118);assert.equal(await page.locator('#periodic-grid .element-tile').count(),118);assert.equal(new Set(records.map(e=>e.symbol)).size,118);
 for(const f of facts){const e=records[f.atomicNumber-1];assert.equal(e.name.toLowerCase(),f.name);assert.equal(e.symbol,f.symbol);assert.equal(e.mass.kind==='standard'?e.mass.value+' ± '+e.mass.uncertainty:'—',f.weight);}
 const reps={43:97,61:145,84:209,85:210,86:222,87:223,88:226,89:227,93:237,94:244,95:243,96:247,97:247,98:251,99:252,100:257,101:258,102:259,103:262,104:267,105:268,106:269,107:270,108:269,109:277,110:281,111:282,112:285,113:286,114:290,115:290,116:293,117:294,118:294};
 for(const [z,mass] of Object.entries(reps))assert.deepEqual(records[z-1].mass,{kind:'representative',massNumber:mass,source:'iupac-2022'});
 const rows=[[1,2],[3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18],Array.from({length:18},(_,i)=>19+i),Array.from({length:18},(_,i)=>37+i),[55,56,...Array.from({length:15},(_,i)=>72+i)],[87,88,...Array.from({length:15},(_,i)=>104+i)]];
 rows.forEach((row,i)=>row.forEach((z,j)=>{const group=i===0?(j?18:1):i===1||i===2?(j<2?j+1:j+11):i>=5?(j<2?j+1:j+2):j+1;assert.equal(records[z-1].period,i+1);assert.equal(records[z-1].group,group);assert.deepEqual(records[z-1].grid,{row:i+1,column:group});}));
 for(let z=57;z<=71;z++)assert.deepEqual(records[z-1].grid,{row:9,column:z-54});for(let z=89;z<=103;z++)assert.deepEqual(records[z-1].grid,{row:10,column:z-86});assert.deepEqual(records.filter(e=>e.explorerAvailable).map(e=>e.symbol),['H','He','Li','Be','B','C','N','O','F','Ne','Na','Mg','Al','Si','P','S','Cl','Ar','K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr','Rb','Sr','Y','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd','In','Sn','Sb','Te','I','Xe','Cs','Ba','La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu','Hf','Ta','W','Re','Os','Ir','Pt','Au','Hg','Tl','Pb','Bi','Po','At','Rn','Fr','Ra','Ac','Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds']);
 assert.equal(await page.evaluate(()=>Copper.periodicValidation.ok),true);
 // Every tile opens accurate basic information; no unfinished explorer is offered.
 for(const e of records){await page.click('#tile-'+e.symbol);await page.waitForFunction(symbol=>Copper.applicationState.selectedElement===symbol,e.symbol);assert.equal(await page.locator('#selected-element-title').innerText(),e.name);assert.equal(await page.locator('#explore-element').count(),e.explorerAvailable?1:0);assert.match(await page.locator('#tile-'+e.symbol).getAttribute('aria-label'),new RegExp(e.atomicNumber+', '+e.name+', '+e.symbol));if(e.mass.kind==='representative')assert.match(await page.locator('.mass-label').innerText(),/Representative isotope/);else assert.match(await page.locator('.mass-label').innerText(),/Standard atomic weight/);}
 assert.equal(await page.evaluate(()=>!!Copper.app),false);
 const positions=await page.locator('#periodic-grid .element-tile').evaluateAll(es=>es.map(e=>e.style.gridRow+':'+e.style.gridColumn));
 for(const [query,symbol] of [['copper','Cu'],['cU','Cu'],['29','Cu'],['aluminum','Al'],['cesium','Cs'],['2','He']]){await page.fill('#element-search',query);await page.press('#element-search','Enter');await page.waitForFunction(symbol=>Copper.applicationState.selectedElement===symbol,symbol);if(/^\d+$/.test(query))assert.match(await page.locator('#match-count').innerText(),/^1 of 118/);}
 await page.click('#clear-search');assert.equal(await page.locator('#element-search').inputValue(),'');await page.click('[data-family="halogen"]');assert.match(await page.locator('#match-count').innerText(),/^5 of 118/);await page.click('[data-family="noble"]');assert.match(await page.locator('#match-count').innerText(),/^11 of 118/);await page.fill('#element-search','29');assert.match(await page.locator('#match-count').innerText(),/^0 of 118/);await page.click('#clear-filters');assert.match(await page.locator('#match-count').innerText(),/^1 of 118/);assert.deepEqual(await page.locator('#periodic-grid .element-tile').evaluateAll(es=>es.map(e=>e.style.gridRow+':'+e.style.gridColumn)),positions);
 await page.click('#clear-search');await page.click('[data-table-view="list"]');assert.equal(await page.locator('#element-list').isVisible(),true);await page.fill('#element-search','29');assert.equal(await page.locator('#element-list .element-tile:visible').count(),1);await page.click('#list-Cu');await page.click('[data-table-view="table"]');await page.click('#clear-search');
 await page.locator('#tile-Cu').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>document.activeElement.id),'tile-Zn');await page.keyboard.press('ArrowUp');assert.equal(await page.evaluate(()=>document.activeElement.id),'tile-Zn');await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement.id),'tile-Cd');await page.locator('#tile-La').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>document.activeElement.id),'tile-Ce');await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement.id),'tile-Th');await page.keyboard.press('Enter');await page.waitForFunction(()=>Copper.applicationState.selectedElement==='Th');await page.keyboard.press('Escape');await page.waitForFunction(()=>!Copper.applicationState.selectedElement);assert.equal(await page.evaluate(()=>document.activeElement.id),'tile-Th');
 await page.fill('#element-search','29');await page.press('#element-search','Enter');await page.waitForFunction(()=>Copper.applicationState.selectedElement==='Cu');await page.click('[data-family="transition"]');await page.click('[data-home-level="middle"]');assert.equal(await page.locator('#element-search').inputValue(),'29');assert.equal(await page.locator('[data-family="transition"]').getAttribute('aria-pressed'),'true');await page.click('#explore-element');await page.waitForFunction(()=>Copper.app?.active===true);assert.equal(await page.evaluate(()=>Copper.app.state.level),'middle');
 await page.selectOption('#isotope-select','copper-67');await page.click('[data-model="quantum"]');await page.click('[data-quantum="explore"]');await page.selectOption('#subshell','3d');await page.evaluate(()=>{const a=Copper.app;a.state.yaw=1.2;a.state.pitch=.4;a.state.zoom=1.8;window.savedRenderer=a.renderer;window.savedParticles=a.particles;});
 await page.click('#back-table');await page.waitForFunction(()=>Copper.applicationState.page==='table');assert.equal(await page.evaluate(()=>Copper.app.active),false);const time=await page.evaluate(()=>Copper.app.state.time);await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>Copper.app.state.time),time);assert.equal(await page.locator('#element-search').inputValue(),'29');assert.equal(await page.locator('[data-family="transition"]').getAttribute('aria-pressed'),'true');await page.click('[data-home-level="elementary"]');await page.click('#explore-element');await page.waitForFunction(()=>Copper.app.active);assert.deepEqual(await page.evaluate(()=>{const a=Copper.app;return [a.atom.massNumber,a.state.model,a.state.subshell,a.state.yaw,a.state.pitch,a.state.zoom,a.state.level,a.renderer===savedRenderer,a.particles===savedParticles];}),[67,'quantum','3d',1.2,.4,1.8,'elementary',true,true]);
 await page.click('#reset');await page.selectOption('#particle-list','proton');await page.click('#explore-inside');await page.waitForTimeout(220);await page.click('#back-table');await page.waitForFunction(()=>Copper.applicationState.page==='table');await page.click('#explore-element');await page.waitForFunction(()=>Copper.applicationState.page==='explorer');assert.equal(await page.evaluate(()=>Copper.app.state.view),'nucleon');assert.equal(await page.locator('#internal-panel').isVisible(),true);await page.click('#back-atom');
 await page.click('#fullscreen');assert.equal(await page.evaluate(()=>Copper.app.state.presentation),true);await page.click('#exit-fullscreen');assert.equal(await page.evaluate(()=>Copper.app.state.presentation),false);
 await page.click('#back-table');await page.waitForFunction(()=>Copper.applicationState.page==='table');await page.goBack();await page.waitForFunction(()=>Copper.applicationState.page==='explorer');await page.goForward();await page.waitForFunction(()=>Copper.applicationState.page==='table');
 for(const hash of ['#invalid','#element=NoSuch','#%invalid']){await page.goto(url+hash);await page.reload();await page.waitForFunction(()=>location.hash==='#periodic-table');assert.equal(await page.locator('#periodic-page').isVisible(),true);assert.equal(await page.evaluate(()=>!!Copper.app),false);}
 await page.goto(url+'#explore=Cn');await page.reload();await page.waitForFunction(()=>location.hash==='#element=Db');assert.equal(await page.locator('#selected-element-title').innerText(),'Dubnium');assert.equal(await page.evaluate(()=>!!Copper.app),false);
 await page.goto(url+'#explore=Cu');await page.waitForFunction(()=>!!Copper.app);await page.reload();await page.waitForFunction(()=>Copper.applicationState.page==='explorer');assert.equal(await page.locator('#isotope-select').inputValue(),'copper-63');
 // Viewport, touch targets, labels and controlled horizontal overflow.
 for(const width of [320,390,768,1024,1366,1920]){await page.setViewportSize({width,height:1000});await page.goto(url);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const targets=await page.locator('#periodic-grid button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().width>=44&&e.getBoundingClientRect().height>=44));assert.equal(targets,true);const namesFit=await page.locator('#periodic-grid button').evaluateAll(es=>es.every(e=>{const n=e.querySelector('.element-name'),a=e.getBoundingClientRect(),b=n.getBoundingClientRect();return b.bottom<=a.bottom+1;}));assert.equal(namesFit,true,'name bounds '+width);await page.fill('#element-search','29');await page.press('#element-search','Enter');await page.waitForFunction(()=>Copper.applicationState.selectedElement==='Cu');const scroll=await page.locator('#table-scroll').evaluate(e=>{const r=e.getBoundingClientRect(),b=document.getElementById('tile-Cu').getBoundingClientRect();return b.left>=r.left&&b.right<=r.right;});assert.equal(scroll,true,'selected tile horizontal visibility');const saved=await page.locator('#table-scroll').evaluate(e=>e.scrollLeft);await page.click('[data-home-level="elementary"]');assert.equal(await page.locator('#table-scroll').evaluate(e=>e.scrollLeft),saved);await page.click('#explore-element');await page.waitForFunction(()=>Copper.app?.active);await page.click('#back-table');await page.waitForFunction(()=>Copper.applicationState.page==='table');assert.equal(await page.locator('#table-scroll').evaluate(e=>e.scrollLeft),saved);await page.click('#clear-search');await page.screenshot({path:'qa/phase5-'+width+'.png',fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.goto(url);await page.locator('#tile-H').tap();await page.waitForFunction(()=>Copper.applicationState.selectedElement==='H');await page.locator('#tile-H').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#tile-He').evaluate(e=>getComputedStyle(e).outlineStyle),'solid');await page.uncheck('#category-color');assert.equal(await page.locator('#periodic-page').evaluate(e=>e.classList.contains('no-category-color')),true);assert.equal(await page.locator('#tile-H').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);assert.deepEqual(missing,[]);const report={result:'PASS',records:118,sourceRowsMatched:118,representativeMassNumbersChecked:Object.keys(reps).length,cardsOpened:118,widths:[320,390,768,1024,1366,1920],errors,remote,missing,checks:'lazy initialization, table placement, search/filter/list, labels, arrow/Enter/Escape/touch, availability guards, offline hashes/back/forward/reload, state preservation, inactive drawing, copper models/isotope/subshell/interior/fullscreen'};fs.writeFileSync('qa/phase5-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
