const {chromium}=require('C:/Users/arial/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),{pathToFileURL}=require('url'),path=require('path'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true,reducedMotion:'reduce'}),p=await context.newPage(),errors=[],remote=[],missing=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('request',r=>{if(!r.url().startsWith('file:'))remote.push(r.url());});p.on('requestfailed',r=>missing.push(r.url()));
 const url=pathToFileURL(path.resolve('periodic-table-visualizer/index.html')).href,enabled=['H','He','Li','Be','B','C','N','O','F','Ne','Na','Mg','Al','Si','P','S','Cl','Ar','K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr','Rb','Sr','Y','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd','In','Sn','Sb','Te','I','Xe','Cs','Ba','La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu','Hf','Ta','W','Re','Os','Ir','Pt','Au','Hg','Tl','Pb','Bi','Po','At','Rn','Fr','Ra','Ac','Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds'];const opened=async symbol=>p.waitForFunction(symbol=>Copper.app?.atom.element.symbol===symbol&&Copper.applicationState.page==='explorer',symbol);const table=async()=>{await p.click('#back-table');await p.waitForFunction(()=>Copper.applicationState.page==='table');};
 await p.goto(url);assert.equal(await p.locator('#periodic-grid .element-tile').count(),118);assert.equal(await p.locator('.explorer-badge').count(),0);assert.equal(await p.locator('.element-tile').evaluateAll(es=>es.some(e=>/3D/.test(e.textContent+e.getAttribute('aria-label')))),false);assert.deepEqual(await p.evaluate(()=>Copper.basicElements.filter(e=>e.explorerAvailable).map(e=>e.symbol)),enabled);assert.deepEqual(await p.evaluate(()=>[Copper.enabledValidation.ok,Copper.enabledValidation.elements,Copper.enabledValidation.isotopes]),[true,110,409]);
 const positions=await p.locator('#periodic-grid .element-tile').evaluateAll(es=>es.map(e=>[e.style.gridRow,e.style.gridColumn]));
 for(const symbol of enabled){await p.click('#tile-'+symbol);await p.waitForFunction(symbol=>Copper.applicationState.selectedElement===symbol,symbol);assert.equal(await p.evaluate(()=>Copper.applicationState.page),'table');assert.match(await p.locator('#tile-'+symbol).getAttribute('aria-label'),/interactive atom explorer available/);await p.click('#explore-element');await opened(symbol);await table();await p.dblclick('#tile-'+symbol);await opened(symbol);await table();}
 await p.dblclick('#tile-Rg');await p.waitForFunction(()=>Copper.applicationState.selectedElement==='Rg');assert.equal(await p.evaluate(()=>Copper.applicationState.page),'table');assert.equal(await p.locator('#explore-element').count(),0);
 // Independent expected defaults, neutron arithmetic and all requested isotope identities.
 const expected=[['He','helium',4,[3,4]],['Li','lithium',7,[6,7]],['Be','beryllium',9,[9,10]],['B','boron',11,[10,11]],['C','carbon',12,[12,13,14]],['N','nitrogen',14,[14,15,13]],['O','oxygen',16,[16,17,18,15]],['F','fluorine',19,[19,18]],['Ne','neon',20,[20,21,22]]];
 const radioactive={'beryllium-10':[1390000,'years','Beta-minus'],'carbon-14':[5730,'years','Beta-minus'],'nitrogen-13':[9.97,'minutes','positron'],'oxygen-15':[2,'minutes','positron'],'fluorine-18':[109.8,'minutes','positron']};let isotopeCases=0,modelCases=0,interiors=0;
 for(let j=0;j<expected.length;j++){
  const [symbol,slug,mass,masses]=expected[j],z=j+2,outer=z===2?2:z-2,subs=z===2?['1s']:z<=4?['1s','2s']:['1s','2s','2p'];await p.goto(url+'#explore='+symbol);await p.reload();await opened(symbol);assert.equal(await p.locator('#isotope-select').inputValue(),slug+'-'+mass);assert.equal(await p.title(),slug[0].toUpperCase()+slug.slice(1)+' Atom Explorer');
  assert.deepEqual(await p.locator('#isotope-select option').evaluateAll(es=>es.map(e=>e.value).sort()),masses.map(m=>slug+'-'+m).sort());
  for(const m of masses){isotopeCases++;const id=slug+'-'+m;await p.selectOption('#isotope-select',id);const a=await p.evaluate(()=>Copper.app.atom);assert.deepEqual([a.protons,a.neutrons,a.electrons,a.shells],[z,m-z,z,z===2?[2]:[2,z-2]]);assert.deepEqual(a.subshells.map(s=>s.id),subs);assert.equal(a.subshells.reduce((sum,s)=>sum+s.occupancy,0),z);assert.equal(a.isotope.stable,!radioactive[id]);
   if(radioactive[id]){assert.deepEqual([a.isotope.halfLife.value,a.isotope.halfLife.unit],radioactive[id].slice(0,2));assert.ok(a.isotope.decayModes.join().includes(radioactive[id][2]));assert.equal(a.isotope.naturalAbundance,null);assert.match(await p.locator('#stability').innerText(),/Radioactive/);}else assert.match(await p.locator('#stability').innerText(),/Stable/);
   for(const level of ['elementary','middle','high'])assert.ok(a.isotope.descriptions[level].length>15);assert.equal(await p.locator('#isotope-sources a').count()>0,true);
   for(const model of ['bohr','wave','quantum']){modelCases++;await p.click('[data-model="'+model+'"]');await p.click('#reset');
    const render=await p.evaluate(()=>{const a=Copper.app,r=a.renderer;return {electrons:r.hits.filter(h=>h.p.type==='electron').length,nucleons:r.hits.filter(h=>h.p.type!=='electron').length,lines:r.electronObjects().filter(o=>o.kind==='line').length,states:[...new Set((r.regionHits||[]).map(h=>h.p.subshell))],clouds:r.clouds?.map(c=>c.sub.id)};});assert.equal(render.nucleons,m);
    if(model==='bohr'){assert.equal(render.electrons,z);assert.equal(render.lines,subs.length===1?120:240);await p.selectOption('#particle-list','valence-electron');assert.equal(await p.locator('#particle-list option[value="valence-electron"]').innerText(),outer>1?'Valence electrons':'Valence electron');if(outer>1){assert.equal(await p.evaluate(()=>Copper.app.state.selected),'group-valence');assert.equal(await p.evaluate(()=>Copper.app.renderer.highlightedValenceCount),outer);}await p.locator('#stage').screenshot({path:'qa/phase6a-'+symbol+'-bohr.png'});}
    else {assert.equal(render.electrons,0);assert.equal(render.lines,0);assert.deepEqual(render.states,subs);}
    if(model==='wave'){assert.deepEqual(await p.locator('#wave-shell option').evaluateAll(es=>es.map(e=>e.value)),['all',...subs]);for(const sub of subs){await p.selectOption('#wave-shell',sub);assert.match(await p.locator('#particle-info').innerText(),new RegExp(sub+':'));assert.equal(await p.evaluate(()=>new Set(Copper.app.renderer.regionHits.map(h=>h.p.subshell)).size),1);}await p.selectOption('#wave-shell','all');}
    if(model==='quantum'){assert.deepEqual(render.clouds,subs);await p.click('[data-quantum="explore"]');assert.deepEqual(await p.locator('#subshell option:not([value="all"])').evaluateAll(es=>es.map(e=>e.value)),subs);for(const sub of subs){await p.selectOption('#subshell',sub);assert.match(await p.locator('#subshell-info').innerText(),/of (2|6) electrons/);assert.match(await p.locator('#subshell-info').innerText(),/Inner subshell|Valence subshell/);assert.equal(await p.evaluate(()=>Copper.app.renderer.visibleLayers),1);}await p.click('[data-quantum="overview"]');}
   }
   // Each isotope supports both nucleons; electron configuration survives the round trip.
   for(const category of ['proton','neutron']){await p.selectOption('#particle-list',category);const before=await p.evaluate(()=>{const a=Copper.app;return [a.atom.isotope.id,a.state.model,a.state.level,a.state.yaw,a.state.pitch,a.state.zoom];});await p.click('#explore-inside');await p.waitForTimeout(200);assert.match(await p.locator('#breadcrumb').innerText(),new RegExp(slug[0].toUpperCase()+slug.slice(1)+'-'+m));assert.equal(await p.evaluate(()=>Copper.nucleonCharge(Copper.app.state.nucleon).value),category==='proton'?1:0);await p.click('#back-atom');assert.deepEqual(await p.evaluate(()=>{const a=Copper.app;return [a.atom.isotope.id,a.state.model,a.state.level,a.state.yaw,a.state.pitch,a.state.zoom];}),before);interiors++;}
  }
  if(z===2)assert.equal(await p.locator('#particle-list option[value="inner-electron"]').count(),0);
  // Explanation changes must preserve model/subshell/camera/pause and presentation state.
  await p.click('[data-model="quantum"]');await p.click('[data-quantum="explore"]');await p.selectOption('#subshell',subs.at(-1));const before=await p.evaluate(()=>{const a=Copper.app;a.state.yaw=.8;a.state.pitch=.4;a.state.zoom=1.2;return [a.atom.isotope.id,a.state.model,a.state.subshell,a.state.yaw,a.state.pitch,a.state.zoom,a.state.paused];});const descriptions=[];
  for(const level of ['elementary','middle','high']){await p.click('[data-level="'+level+'"]');descriptions.push(await p.locator('.conduction p').innerText());assert.deepEqual(await p.evaluate(()=>{const a=Copper.app;return [a.atom.isotope.id,a.state.model,a.state.subshell,a.state.yaw,a.state.pitch,a.state.zoom,a.state.paused];}),before);assert.equal((await p.locator('#model-description').innerText()).includes('Copper'),false);}assert.equal(new Set(descriptions).size,3);
  for(const model of ['bohr','wave','quantum']){await p.click('[data-model="'+model+'"]');const state=await p.evaluate(()=>{const a=Copper.app;return [a.atom.isotope.id,a.state.model,a.state.level,a.state.yaw,a.state.pitch,a.state.zoom,a.state.paused];});await p.click('#fullscreen');assert.equal(await p.evaluate(()=>Copper.app.state.presentation),true);await p.click('#exit-fullscreen');assert.deepEqual(await p.evaluate(()=>{const a=Copper.app;return [a.atom.isotope.id,a.state.model,a.state.level,a.state.yaw,a.state.pitch,a.state.zoom,a.state.paused];}),state);}
  await p.locator('#stage').screenshot({path:'qa/phase6a-'+symbol+'-quantum.png'});await table();await p.goBack();await opened(symbol);await p.goForward();await p.waitForFunction(()=>Copper.applicationState.page==='table');
 }
 await p.fill('#element-search','oxygen');await p.press('#element-search','Enter');await p.waitForFunction(()=>Copper.applicationState.selectedElement==='O');await p.click('[data-family="nonmetal"]');const scroll=await p.locator('#table-scroll').evaluate(e=>e.scrollLeft);await p.click('#explore-element');await opened('O');await table();assert.equal(await p.locator('#element-search').inputValue(),'oxygen');assert.equal(await p.locator('[data-family="nonmetal"]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('#table-scroll').evaluate(e=>e.scrollLeft),scroll);assert.deepEqual(await p.locator('#periodic-grid .element-tile').evaluateAll(es=>es.map(e=>[e.style.gridRow,e.style.gridColumn])),positions);
 await p.click('#clear-search');await p.click('#clear-filters');await p.locator('#tile-Ne').focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>Copper.applicationState.selectedElement==='Ne');await p.locator('#explore-element').focus();await p.keyboard.press('Enter');await opened('Ne');await p.locator('#isotope-select').focus();await p.keyboard.press('ArrowDown');assert.equal(await p.locator('#isotope-select').inputValue(),'neon-21');
 for(const width of [320,390,768,1024,1366,1920]){await p.setViewportSize({width,height:900});for(const symbol of ['He','B','Ne']){await p.goto(url+'#explore='+symbol);await opened(symbol);await p.click('[data-model="wave"]');await p.selectOption('#particle-list','valence-electron');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.locator('#particle-info').evaluate(e=>e.scrollWidth>e.clientWidth),false);}await p.screenshot({path:'qa/phase6a-'+width+'.png',fullPage:true});await table();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.locator('#periodic-grid button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().width>=44)),true);}
 await p.setViewportSize({width:390,height:844});await p.locator('#tile-He').tap();await p.waitForFunction(()=>Copper.applicationState.selectedElement==='He');assert.equal(await p.evaluate(()=>Copper.applicationState.page),'table');await p.locator('#explore-element').tap();await opened('He');assert.equal(await p.evaluate(()=>Copper.app.state.reducedMotion),true);
 for(const hash of ['#explore=Rg','#explore=Cn','#explore=XYZ']){await p.goto(url+hash);await p.waitForFunction(()=>Copper.applicationState.page==='table');}
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);assert.deepEqual(missing,[]);const result={result:'PASS',enabled,records:118,isotopeCases,modelCases,interiors,levels:3,widths:[320,390,768,1024,1366,1920],errors,remote,missing,checks:'badge removal, buttons/double-click, guards, every isotope/model, group valence selection, occupied wave/subshell choices, charges, interiors and restoration, levels/state, fullscreen, history, keyboard/touch, responsive/offline'};fs.writeFileSync('qa/phase6a-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
