// Generated by build-portable.mjs. Edit js/ sources, then rebuild.
(() => {
"use strict";

// Module: track
const { TRACK, TRACKS, DIFFICULTIES, withDifficulty, bestLapKey, WORLD, buildTrack } = (() => {
// Track definitions are data: add another set of clockwise control points to extend the lab.
const TRACK = {
  id: "workshop-v1",
  name: "The Workshop",
  subtitle: "Original indoor circuit · Balanced",
  vehicleScale: 1,
  width: 112,
  points: [
    [370, 145],
    [750, 145],
    [1010, 205],
    [1040, 400],
    [935, 585],
    [730, 592],
    [635, 455],
    [480, 445],
    [395, 593],
    [210, 578],
    [155, 400],
    [180, 220],
  ],
};
// Hand-traced from the supplied reference images, then rotated to fit the table.
// These are RC adaptations, not surveyed full-size replicas. Narrow sections
// use a smaller car and matching speed scale to preserve usable steering room.
const MONACO = {
  id: "monaco-v1",
  name: "Monaco",
  subtitle: "Reference-inspired street circuit · Technical",
  width: 24,
  vehicleScale: 0.4,
  points: [
    [130, 925],
    [125, 800],
    [145, 690],
    [165, 640],
    [270, 617],
    [420, 580],
    [530, 557],
    [640, 515],
    [780, 487],
    [835, 445],
    [850, 402],
    [830, 345],
    [785, 293],
    [785, 252],
    [830, 185],
    [890, 104],
    [920, 70],
    [925, 20],
    [960, 20],
    [970, 65],
    [975, 115],
    [985, 170],
    [1010, 210],
    [1050, 205],
    [1060, 170],
    [1030, 105],
    [1040, 75],
    [1060, 48],
    [1109, 37],
    [1128, 59],
    [1122, 120],
    [1110, 210],
    [1085, 300],
    [1040, 403],
    [1000, 446],
    [910, 500],
    [810, 550],
    [700, 581],
    [616, 599],
    [594, 610],
    [580, 633],
    [561, 638],
    [525, 626],
    [455, 632],
    [350, 644],
    [260, 655],
    [220, 681],
    [192, 744],
    [182, 815],
    [191, 854],
    [220, 897],
    [235, 959],
    [247, 1020],
    [249, 1043],
    [226, 1080],
    [229, 1121],
    [255, 1182],
    [295, 1236],
    [349, 1271],
    [356, 1293],
    [323, 1308],
    [270, 1318],
    [249, 1304],
    [237, 1270],
    [205, 1215],
    [180, 1156],
    [156, 1068],
    [140, 995],
  ].map(([x, y]) => [80 + (y - 30) * 0.8, 55 + (1130 - x) * 0.6]),
};
const LE_MANS = {
  id: "le-mans-v1",
  name: "Le Mans",
  subtitle: "Reference-inspired endurance circuit · Fast straights",
  width: 66,
  vehicleScale: 0.8,
  points: [
    [160, 82],
    [175, 62],
    [190, 46],
    [220, 43],
    [245, 45],
    [266, 37],
    [292, 41],
    [295, 77],
    [283, 139],
    [273, 182],
    [266, 197],
    [269, 210],
    [258, 258],
    [245, 316],
    [241, 330],
    [247, 345],
    [237, 355],
    [227, 388],
    [206, 431],
    [184, 475],
    [176, 480],
    [142, 455],
    [110, 400],
    [93, 355],
    [94, 340],
    [71, 334],
    [82, 299],
    [87, 259],
    [89, 232],
    [113, 208],
    [109, 185],
    [121, 180],
    [138, 152],
    [149, 122],
  ].map(([x, y]) => [90 + (y - 35) * 2.2, 100 + (295 - x) * 2.3]),
};
const TRACKS = [TRACK, MONACO, LE_MANS];
const DIFFICULTIES = {
  easy: { label: "Easy", widthMultiplier: 1.35 },
  medium: { label: "Medium", widthMultiplier: 1 },
  hard: { label: "Hard", widthMultiplier: 0.75 },
};
// Monaco's closely spaced return lanes limit safe widening. Keep its road
// surfaces separate so easy mode never opens a shortcut between sections.
function withDifficulty(definition, difficulty = "medium") {
  const level = Object.hasOwn(DIFFICULTIES, difficulty) ? difficulty : "medium";
  const maximum = definition.id === "monaco-v1" ? 26.4 : Infinity;
  return {
    ...definition,
    difficulty: level,
    width: Math.min(
      definition.width * DIFFICULTIES[level].widthMultiplier,
      maximum,
    ),
  };
}
// Medium keeps the original geometry and existing personal best records.
const bestLapKey = (track) =>
  `micro-circuit:${track.id}${track.difficulty && track.difficulty !== "medium" ? `:${track.difficulty}` : ""}:best`;
const WORLD = { width: 1200, height: 760 };
const mix = (a, b, c, d, t) =>
  0.5 *
  (2 * b +
    (-a + c) * t +
    (2 * a - 5 * b + 4 * c - d) * t * t +
    (-a + 3 * b - 3 * c + d) * t * t * t);
function buildTrack(definition = TRACK) {
  const samples = [],
    p = definition.points,
    n = p.length;
  for (let i = 0; i < n; i++)
    for (let j = 0; j < 24; j++) {
      const t = j / 24,
        a = p[(i + n - 1) % n],
        b = p[i],
        c = p[(i + 1) % n],
        d = p[(i + 2) % n];
      samples.push({
        x: mix(a[0], b[0], c[0], d[0], t),
        y: mix(a[1], b[1], c[1], d[1], t),
      });
    }
  let length = 0;
  const segments = samples.map((a, i) => {
    const b = samples[(i + 1) % samples.length],
      dx = b.x - a.x,
      dy = b.y - a.y,
      len = Math.hypot(dx, dy);
    const segment = { a, b, dx, dy, len, start: length };
    length += len;
    return segment;
  });
  function at(distance) {
    const s = ((distance % length) + length) % length;
    const seg = segments.find((v) => s < v.start + v.len) || segments[0],
      t = (s - seg.start) / seg.len;
    return {
      x: seg.a.x + seg.dx * t,
      y: seg.a.y + seg.dy * t,
      angle: Math.atan2(seg.dy, seg.dx),
      s,
    };
  }
  function nearest(x, y) {
    let best = { distance: Infinity };
    for (const v of segments) {
      const t = Math.max(
        0,
        Math.min(
          1,
          ((x - v.a.x) * v.dx + (y - v.a.y) * v.dy) / (v.len * v.len),
        ),
      );
      const px = v.a.x + t * v.dx,
        py = v.a.y + t * v.dy,
        distance = Math.hypot(x - px, y - py);
      if (distance < best.distance)
        best = {
          x: px,
          y: py,
          distance,
          s: v.start + t * v.len,
          angle: Math.atan2(v.dy, v.dx),
        };
    }
    return best;
  }
  return { ...definition, samples, segments, length, at, nearest };
}

return { TRACK, TRACKS, DIFFICULTIES, withDifficulty, bestLapKey, WORLD, buildTrack };
})();

// Module: car
const { TUNING, Car } = (() => {
// All tuning values use world pixels and seconds. Change one variable at a time in class.
const TUNING = {
  acceleration: 175,
  braking: 300,
  drag: 0.7,
  maxSpeed: 300,
  reverseSpeed: 85,
  steering: 2.8,
  radius: 13,
};
class Car {
  constructor(track) {
    this.reset(track);
  }
  reset(track) {
    this.scale = track.vehicleScale ?? 1;
    Object.assign(this, track.at(0));
    this.speed = 0;
    this.impact = 0;
  }
  update(dt, input, track) {
    const t = TUNING,
      gas = input.has("w") || input.has("arrowup"),
      brake = input.has("s") || input.has("arrowdown");
    const steer =
      Number(input.has("d") || input.has("arrowright")) -
      Number(input.has("a") || input.has("arrowleft"));
    if (brake)
      this.speed -=
        (this.speed > 0 ? t.braking : t.acceleration * 0.55) * this.scale * dt;
    else if (gas) this.speed += t.acceleration * this.scale * dt;
    this.speed *= Math.exp(-t.drag * dt);
    this.speed = Math.max(
      -t.reverseSpeed * this.scale,
      Math.min(t.maxSpeed * this.scale, this.speed),
    );
    this.angle +=
      steer *
      t.steering *
      Math.min(1, Math.abs(this.speed) / (100 * this.scale)) *
      Math.sign(this.speed) *
      dt;
    this.x += Math.cos(this.angle) * this.speed * dt;
    this.y += Math.sin(this.angle) * this.speed * dt;
    const near = track.nearest(this.x, this.y),
      limit = track.width / 2 - t.radius * this.scale;
    this.impact = Math.max(0, this.impact - dt);
    if (near.distance > limit) {
      // Project back inside the barrier. Remove outward velocity while preserving tangential motion.
      const nx = (this.x - near.x) / near.distance,
        ny = (this.y - near.y) / near.distance;
      this.x = near.x + nx * limit;
      this.y = near.y + ny * limit;
      const outward =
        (Math.cos(this.angle) * nx + Math.sin(this.angle) * ny) *
        Math.sign(this.speed);
      if (outward > 0) this.speed *= Math.max(0.15, 1 - outward * 0.85);
      this.impact = 0.12;
    }
    return track.nearest(this.x, this.y);
  }
}

return { TUNING, Car };
})();

// Module: race
const { LAP_COUNT, MAX_LAPS, normalizeLapCount, formatTime, Race } = (() => {
const LAP_COUNT = 3;
const MAX_LAPS = 99;
function normalizeLapCount(value) {
  const count = Number(value);
  return Number.isFinite(count) && count >= 1
    ? Math.min(MAX_LAPS, Math.floor(count))
    : LAP_COUNT;
}
function formatTime(seconds) {
  if (seconds == null) return "—";
  const ms = Math.floor(seconds * 1000);
  return `${String(Math.floor(ms / 60000)).padStart(2, "0")}:${String(Math.floor(ms / 1000) % 60).padStart(2, "0")}.${String(ms % 1000).padStart(3, "0")}`;
}
// Race logic is independent of Canvas, so teachers can add scoring or export functions here.
class Race {
  constructor(length, lapCount = LAP_COUNT) {
    this.length = length;
    this.lapCount = normalizeLapCount(lapCount);
    this.reset();
    this.state = "ready";
  }
  reset() {
    this.state = "countdown";
    this.countdown = 3;
    this.elapsed = 0;
    this.lapStart = 0;
    this.laps = [];
    this.progress = 0;
    this.lastS = 0;
    this.checkpoint = 0;
  }
  update(dt, s) {
    if (this.state === "countdown") {
      this.countdown -= dt;
      if (this.countdown <= 0) this.state = "racing";
      return;
    }
    if (this.state !== "racing") return;
    this.elapsed += dt;
    let delta = s - this.lastS;
    if (delta > this.length / 2) delta -= this.length;
    if (delta < -this.length / 2) delta += this.length;
    this.lastS = s;
    // Signed distance prevents reversing across a gate from awarding repeated checkpoints.
    this.progress += delta;
    this.checkpoint = Math.max(
      0,
      Math.min(4, Math.floor(this.progress / (this.length / 4))),
    );
    if (this.progress >= this.length) {
      this.laps.push(this.elapsed - this.lapStart);
      this.lapStart = this.elapsed;
      this.progress -= this.length;
      this.checkpoint = 0;
      if (this.laps.length === this.lapCount) this.state = "finished";
    }
  }
  get currentLap() {
    return this.elapsed - this.lapStart;
  }
  get average() {
    return this.laps.length === this.lapCount
      ? this.laps.reduce((a, b) => a + b, 0) / this.lapCount
      : null;
  }
}

return { LAP_COUNT, MAX_LAPS, normalizeLapCount, formatTime, Race };
})();

// Module: camera
const { Camera } = (() => {
// Camera coordinates are presentation only: physics and lap timing stay in world space.
class Camera {
  constructor() {
    this.mode = "follow";
    this.x = WORLD.width / 2;
    this.y = WORLD.height / 2;
    this.zoom = 1;
    this.needsSnap = true;
  }
  reset() {
    this.needsSnap = true;
  }
  update(car, dt) {
    if (this.mode === "overview") {
      this.x = WORLD.width / 2;
      this.y = WORLD.height / 2;
      this.zoom = 1;
      return;
    }
    // Compensate for the smaller cars on reference tracks. Keep north fixed,
    // and look slightly ahead in the direction of travel (including reverse).
    this.zoom = 1.7 / car.scale;
    const lead = car.speed * 0.35;
    const targetX = car.x + Math.cos(car.angle) * lead;
    const targetY = car.y + Math.sin(car.angle) * lead;
    const blend = this.needsSnap ? 1 : 1 - Math.exp(-8 * dt);
    this.x += (targetX - this.x) * blend;
    this.y += (targetY - this.y) * blend;
    this.needsSnap = false;
  }
  get bounds() {
    const width = WORLD.width / this.zoom,
      height = WORLD.height / this.zoom;
    return { x: this.x - width / 2, y: this.y - height / 2, width, height };
  }
}

return { Camera };
})();

// Module: renderer
const { Renderer } = (() => {
class Renderer {
  constructor(canvas, track) {
    this.canvas = canvas;
    this.ctx = canvas.getContext("2d");
    this.track = track;
    this.camera = new Camera();
    this.resize();
    this.observer = new ResizeObserver(() => this.resize());
    this.observer.observe(canvas);
  }
  resize() {
    const rect = this.canvas.getBoundingClientRect(),
      dpr = Math.min(window.devicePixelRatio || 1, 2);
    this.canvas.width = Math.round(rect.width * dpr);
    this.canvas.height = Math.round(rect.height * dpr);
  }
  path() {
    const c = this.ctx;
    c.beginPath();
    this.track.samples.forEach((p, i) =>
      i ? c.lineTo(p.x, p.y) : c.moveTo(p.x, p.y),
    );
    c.closePath();
  }
  stroke(width, color, dash = []) {
    const c = this.ctx;
    this.path();
    c.lineWidth = width;
    c.strokeStyle = color;
    c.setLineDash(dash);
    c.stroke();
    c.setLineDash([]);
  }
  gate(s, color, number) {
    const p = this.track.at(s),
      c = this.ctx;
    c.save();
    c.translate(p.x, p.y);
    c.rotate(p.angle);
    c.fillStyle = color;
    c.globalAlpha = 0.25;
    c.fillRect(-2, -this.track.width / 2, 4, this.track.width);
    c.globalAlpha = 1;
    c.font = "bold 10px monospace";
    c.textAlign = "center";
    c.fillText(number, 0, -this.track.width / 2 - 23);
    c.restore();
  }
  draw(car, race, dt = 0) {
    const c = this.ctx,
      t = this.track;
    c.setTransform(
      this.canvas.width / WORLD.width,
      0,
      0,
      this.canvas.height / WORLD.height,
      0,
      0,
    );
    c.fillStyle = "#343e3e";
    c.fillRect(0, 0, WORLD.width, WORLD.height);
    this.camera.update(car, dt);
    c.save();
    c.translate(WORLD.width / 2, WORLD.height / 2);
    c.scale(this.camera.zoom, this.camera.zoom);
    c.translate(-this.camera.x, -this.camera.y);
    // Carpet tile seams create an indoor scale reference without external artwork.
    c.strokeStyle = "#3c4645";
    c.lineWidth = 1;
    c.beginPath();
    const view = this.camera.bounds;
    for (
      let x = Math.floor(view.x / 60) * 60;
      x < view.x + view.width;
      x += 60
    ) {
      c.moveTo(x, view.y);
      c.lineTo(x, view.y + view.height);
    }
    for (
      let y = Math.floor(view.y / 60) * 60;
      y < view.y + view.height;
      y += 60
    ) {
      c.moveTo(view.x, y);
      c.lineTo(view.x + view.width, y);
    }
    c.stroke();
    c.lineJoin = "round";
    c.lineCap = "round";
    const scale = t.vehicleScale ?? 1;
    this.stroke(t.width + 28 * scale, "#202a2b");
    this.stroke(t.width + 18 * scale, "#a6b29d");
    this.stroke(t.width + 18 * scale, "#d6f56a", [25 * scale, 25 * scale]);
    this.stroke(t.width + 7 * scale, "#202a2c");
    this.stroke(t.width, "#535c5c");
    this.stroke(1, "#737c7766", [7, 13]);
    // Painted infield markings and low-profile workshop planters.
    c.save();
    c.translate(580, t.id === "workshop-v1" ? 292 : 690);
    c.font = '800 43px "Arial Narrow",sans-serif';
    c.textAlign = "center";
    c.fillStyle = "#a2ad9b";
    c.globalAlpha = 0.22;
    c.fillText(t.name.toUpperCase(), 0, 0);
    c.font = "12px monospace";
    c.fillText("PRECISION AT EVERY SCALE", 0, 25);
    c.restore();
    if (t.id === "workshop-v1") {
      this.planter(255, 360, 38, 125);
      this.planter(895, 340, 43, 110);
    }
    c.fillStyle = "#879380";
    c.font = "10px monospace";
    c.fillText("PIT LANE / 01", 380, 58);
    c.fillStyle = "#d6f56a";
    c.fillRect(350, 48, 17, 3);
    for (let i = 1; i <= 3; i++)
      this.gate(
        (t.length * i) / 4,
        i <= race.checkpoint ? "#d6f56a" : "#b7c4b4",
        `0${i}`,
      );
    const start = t.at(0);
    c.save();
    c.translate(start.x, start.y);
    c.rotate(start.angle);
    for (let row = 0; row < 10; row++)
      for (let col = 0; col < 2; col++) {
        c.fillStyle = (row + col) % 2 ? "#283131" : "#e5e9d9";
        c.fillRect(
          col * 8 - 8,
          -t.width / 2 + (row * t.width) / 10,
          8,
          t.width / 10,
        );
      }
    c.fillStyle = "#d6f56a";
    c.font = "bold 10px monospace";
    c.fillText("START / FINISH", -35, -t.width / 2 - 25);
    c.restore();
    for (let s = t.length / 16; s < t.length; s += t.length / 8) {
      const p = t.at(s);
      c.save();
      c.translate(p.x, p.y);
      c.rotate(p.angle);
      c.strokeStyle = "#b7c4b04d";
      c.lineWidth = 2;
      c.beginPath();
      c.moveTo(-6, -6);
      c.lineTo(1, 0);
      c.lineTo(-6, 6);
      c.stroke();
      c.restore();
    }
    this.drawCar(car);
    c.restore();
    this.drawMinimap(car);
  }
  drawMinimap(car) {
    // Draw after restoring the world transform so this stays pinned to the HUD.
    const c = this.ctx,
      x = WORLD.width - 255,
      y = 20,
      width = 235,
      height = 182;
    c.save();
    c.fillStyle = "#152027f2";
    c.strokeStyle = "#65735b";
    c.lineWidth = 1;
    c.beginPath();
    c.roundRect(x, y, width, height, 9);
    c.fill();
    c.stroke();
    c.fillStyle = "#d6f56a";
    c.font = "bold 11px monospace";
    c.fillText("CIRCUIT MAP", x + 14, y + 21);
    const mapScale = (width - 24) / WORLD.width;
    c.translate(x + 12, y + 34);
    c.beginPath();
    c.rect(0, 0, width - 24, height - 43);
    c.clip();
    c.scale(mapScale, mapScale);
    this.stroke(Math.max(this.track.width, 3 / mapScale), "#67766c");
    const view = this.camera.bounds;
    c.fillStyle = "#d6f56a14";
    c.strokeStyle = "#d6f56a88";
    c.lineWidth = 1 / mapScale;
    c.fillRect(view.x, view.y, view.width, view.height);
    c.strokeRect(view.x, view.y, view.width, view.height);
    const start = this.track.at(0);
    c.fillStyle = "#ffffff";
    c.fillRect(
      start.x - 2 / mapScale,
      start.y - 2 / mapScale,
      4 / mapScale,
      4 / mapScale,
    );
    c.translate(car.x, car.y);
    c.rotate(car.angle);
    c.fillStyle = "#d6f56a";
    c.strokeStyle = "#152027";
    c.lineWidth = 1.5 / mapScale;
    c.beginPath();
    c.arc(0, 0, 4.5 / mapScale, 0, Math.PI * 2);
    c.fill();
    c.stroke();
    c.beginPath();
    c.moveTo(9 / mapScale, 0);
    c.lineTo(4 / mapScale, -3 / mapScale);
    c.lineTo(4 / mapScale, 3 / mapScale);
    c.closePath();
    c.fill();
    c.restore();
  }
  planter(x, y, w, h) {
    const c = this.ctx;
    c.fillStyle = "#242f2e";
    c.fillRect(x - 5, y - 5, w + 10, h + 10);
    c.fillStyle = "#506044";
    c.fillRect(x, y, w, h);
    c.fillStyle = "#657454";
    for (let i = 8; i < h; i += 17) {
      c.beginPath();
      c.arc(x + w / 2 + Math.sin(i) * 6, y + i, 10, 0, Math.PI * 2);
      c.fill();
    }
  }
  drawCar(car) {
    const c = this.ctx;
    c.save();
    c.translate(car.x, car.y);
    c.rotate(car.angle);
    c.scale(car.scale, car.scale);
    c.shadowColor = "#0008";
    c.shadowBlur = 8;
    c.shadowOffsetY = 5;
    c.fillStyle = "#10171b";
    for (const x of [-12, 10])
      for (const y of [-13, 9]) c.fillRect(x - 4, y, 9, 5);
    c.fillStyle = car.impact ? "#fff0bf" : "#d6f56a";
    c.beginPath();
    c.roundRect(-23, -11, 46, 22, 6);
    c.fill();
    c.shadowBlur = 0;
    c.shadowOffsetY = 0;
    c.fillStyle = "#263a3c";
    c.fillRect(6, -8, 8, 16);
    c.fillRect(-16, -8, 6, 16);
    c.fillStyle = "#f6ffe0";
    c.fillRect(19, -8, 3, 4);
    c.fillRect(19, 4, 3, 4);
    c.fillStyle = "#fa725c";
    c.fillRect(-22, -8, 2, 4);
    c.fillRect(-22, 4, 2, 4);
    c.fillStyle = "#354623";
    c.font = "bold 10px Arial";
    c.textAlign = "center";
    c.textBaseline = "middle";
    c.fillText("01", -2, 0);
    c.fillStyle = "#131f22";
    c.fillRect(-23, -14, 3, 28);
    c.restore();
  }
}

return { Renderer };
})();

// Module: main
(() => {
const $ = (id) => document.getElementById(id);
let track = buildTrack(withDifficulty(TRACKS[0])),
  race = new Race(track.length, $("lap-count").value);
const car = new Car(track),
  renderer = new Renderer($("track"), track),
  input = new Set();
let storageKey = bestLapKey(track);
let best = null,
  previousState = "",
  previousLap = 0,
  resumeState = "racing";
function loadBest() {
  best = null;
  try {
    const stored = Number(localStorage.getItem(storageKey));
    if (Number.isFinite(stored) && stored > 0) best = stored;
  } catch {
    /* Storage may be disabled; the game still works. */
  }
}
loadBest();
// Selecting a circuit replaces all session state together, avoiding stale laps
// or checkpoint distances from the previous layout.
for (const definition of TRACKS) {
  const option = document.createElement("option");
  option.value = definition.id;
  option.textContent = definition.name;
  $("circuit-select").append(option);
}
function updateCircuitLabels() {
  $("track").parentElement.classList.toggle(
    "reference-track",
    track.id !== "workshop-v1",
  );
  $("circuit-name").textContent = track.name.toUpperCase();
  $("circuit-number").textContent =
    ` / CIRCUIT ${String(TRACKS.findIndex((t) => t.id === track.id) + 1).padStart(2, "0")}`;
  $("circuit-footer").textContent = track.name.toUpperCase();
  $("circuit-description").textContent =
    `${track.subtitle} · ${DIFFICULTIES[track.difficulty].label}`;
  $("track").setAttribute(
    "aria-label",
    `${track.name} RC racing track. Use arrow keys or WASD to drive.`,
  );
}
function changeTrackSettings() {
  const definition = TRACKS.find((t) => t.id === $("circuit-select").value);
  if (!definition) return;
  input.clear();
  track = buildTrack(withDifficulty(definition, $("difficulty-select").value));
  race = new Race(track.length, $("lap-count").value);
  car.reset(track);
  renderer.track = track;
  renderer.camera.reset();
  storageKey = bestLapKey(track);
  loadBest();
  previousLap = 0;
  previousState = "";
  resumeState = "racing";
  accumulator = 0;
  $("start").textContent = "Start session ↗";
  renderLapList();
  updateCircuitLabels();
  updateHUD();
  $("announcement").textContent =
    `${track.name}, ${DIFFICULTIES[track.difficulty].label} difficulty. Start a new ${race.lapCount}-lap session.`;
}
$("circuit-select").addEventListener("change", changeTrackSettings);
$("difficulty-select").addEventListener("change", changeTrackSettings);
updateCircuitLabels();
function renderLapList() {
  $("lap-list").innerHTML = Array.from(
    { length: race.lapCount },
    (_, i) =>
      `<li><span>LAP ${String(i + 1).padStart(2, "0")}</span><b>— — : — —</b></li>`,
  ).join("");
}
renderLapList();
$("lap-count").addEventListener("change", () => {
  const count = normalizeLapCount($("lap-count").value);
  $("lap-count").value = count;
  if (count === race.lapCount) return;
  input.clear();
  race = new Race(track.length, count);
  car.reset(track);
  renderer.camera.reset();
  previousLap = 0;
  previousState = "";
  resumeState = "racing";
  accumulator = 0;
  $("start").textContent = "Start session ↗";
  renderLapList();
  updateHUD();
  $("announcement").textContent =
    `${count}-lap session selected. Ready to race.`;
});
function start() {
  input.clear();
  car.reset(track);
  renderer.camera.reset();
  race.reset();
  previousLap = 0;
  previousState = "";
  $("start").textContent = "Restart session ↗";
}
function pause() {
  if (race.state === "paused") {
    race.state = resumeState;
  } else if (["countdown", "racing"].includes(race.state)) {
    resumeState = race.state;
    race.state = "paused";
  }
  input.clear();
}
function recover() {
  if (race.state !== "racing") return;
  const p = track.at(race.lastS);
  Object.assign(car, p);
  car.speed = 0; /* Clock and checkpoint progress are preserved. */
  renderer.camera.reset();
}
$("camera-select").addEventListener("change", (event) => {
  renderer.camera.mode = event.target.value;
  renderer.camera.reset();
});
$("start").addEventListener("click", start);
$("pause").addEventListener("click", pause);
const drivingKeys = [
  "w",
  "a",
  "s",
  "d",
  "arrowup",
  "arrowdown",
  "arrowleft",
  "arrowright",
];
window.addEventListener("keydown", (e) => {
  // Let arrow keys operate the native track selector without driving the car.
  if (["SELECT", "INPUT", "TEXTAREA"].includes(e.target.tagName)) return;
  const key = e.key.toLowerCase();
  if (drivingKeys.includes(key)) {
    e.preventDefault();
    input.add(key);
  }
  if (e.code === "Space" && !["ready", "finished"].includes(race.state)) {
    e.preventDefault();
    if (!e.repeat) pause();
  }
  if (key === "r" && !e.repeat) recover();
});
window.addEventListener("keyup", (e) => input.delete(e.key.toLowerCase()));
window.addEventListener("blur", () => {
  input.clear();
  if (["racing", "countdown"].includes(race.state)) pause();
});
document.addEventListener("visibilitychange", () => {
  if (document.hidden) {
    input.clear();
    if (["racing", "countdown"].includes(race.state)) pause();
  }
});
document.querySelectorAll("[data-key]").forEach((button) => {
  button.addEventListener("pointerdown", (e) => {
    e.preventDefault();
    button.setPointerCapture(e.pointerId);
    input.add(button.dataset.key);
  });
  for (const event of ["pointerup", "pointercancel", "lostpointercapture"])
    button.addEventListener(event, () => input.delete(button.dataset.key));
});
function updateHUD() {
  if (race.laps.length !== previousLap) {
    const newest = race.laps.at(-1);
    if (best === null || newest < best) {
      best = newest;
      try {
        localStorage.setItem(storageKey, String(best));
      } catch {}
    }
    previousLap = race.laps.length;
    $("announcement").textContent =
      `Lap ${previousLap} completed in ${formatTime(newest)}.`;
  }
  $("status").textContent = {
    ready: "READY TO RACE",
    countdown: "ON THE GRID",
    racing: "SESSION LIVE",
    paused: "PAUSED",
    finished: "SESSION COMPLETE",
  }[race.state];
  $("lap").textContent = String(
    Math.min(race.lapCount, race.laps.length + 1),
  ).padStart(2, "0");
  $("time").textContent = formatTime(
    race.state === "finished" ? race.laps.at(-1) : race.currentLap,
  );
  $("best").textContent = formatTime(best);
  $("average").textContent = formatTime(race.average);
  $("lap-target").textContent = ` / ${String(race.lapCount).padStart(2, "0")}`;
  $("average-label").textContent = `${race.lapCount}-LAP AVERAGE`;
  $("session-lap-count").textContent =
    `${String(race.lapCount).padStart(2, "0")} ${race.lapCount === 1 ? "LAP" : "LAPS"}`;
  $("checkpoint").textContent = `Checkpoint ${race.checkpoint} / 4`;
  $("session-note").textContent =
    race.state === "finished"
      ? "All laps recorded"
      : `${race.lapCount}-lap time trial`;
  $("average-note").textContent = race.average
    ? "Session average recorded"
    : `${race.laps.length} of ${race.lapCount} laps recorded`;
  $("total").textContent = race.elapsed ? formatTime(race.elapsed) : "—";
  $("speed").textContent = Math.round(
    (Math.abs(car.speed) / car.scale) * 0.012,
  );
  $("speed-bar").style.width =
    `${(Math.abs(car.speed) / (TUNING.maxSpeed * car.scale)) * 100}%`;
  const fastest = Math.min(...race.laps);
  [...$("lap-list").children].forEach((row, i) => {
    row.className =
      (i === race.laps.length && race.state !== "finished" ? "active " : "") +
      (race.laps[i] === fastest ? "fastest" : "");
    row.lastElementChild.textContent =
      race.laps[i] != null
        ? formatTime(race.laps[i])
        : i === race.laps.length && race.state === "racing"
          ? "IN PROGRESS"
          : "— — : — —";
  });
  $("pause").textContent =
    race.state === "paused" ? "Resume session" : "Pause session";
  $("pause").disabled = ["ready", "finished"].includes(race.state);
  $("overlay").classList.toggle("hidden", race.state === "racing");
  if (race.state === "countdown") {
    $("overlay-title").textContent = Math.max(1, Math.ceil(race.countdown));
    $("overlay-text").textContent =
      "Get ready. Follow the arrows around the circuit.";
    $("overlay-hint").textContent = "THROTTLE OPENS AT ZERO";
  }
  if (race.state !== previousState) {
    if (race.state === "ready") {
      $("overlay-title").textContent = track.name;
      $("overlay-text").textContent =
        `${race.lapCount} ${race.lapCount === 1 ? "lap" : "laps"}. Find your line on this circuit.`;
      $("overlay-hint").textContent = "START SESSION WHEN YOU ARE READY";
    }
    if (race.state === "paused") {
      $("overlay-title").textContent = "Take a breather.";
      $("overlay-text").textContent = "Your session clock is paused.";
      $("overlay-hint").textContent = "SPACE OR RESUME SESSION TO CONTINUE";
    }
    if (race.state === "finished") {
      $("overlay-title").textContent = "Session complete. Nicely driven.";
      $("overlay-text").textContent =
        `Average ${formatTime(race.average)} · Total ${formatTime(race.elapsed)}`;
      $("overlay-hint").textContent = "RESTART TO CHASE YOUR BEST";
    }
    if (race.state === "racing")
      $("announcement").textContent = "Go! Session started.";
    previousState = race.state;
  }
}
// Fixed 120 Hz physics keeps steering and collisions consistent on different displays.
const STEP = 1 / 120;
let last = performance.now(),
  accumulator = 0;
function frame(now) {
  const frameDt = Math.min((now - last) / 1000, 0.1);
  accumulator += frameDt;
  last = now;
  while (accumulator >= STEP) {
    if (race.state === "racing") {
      const location = car.update(STEP, input, track);
      race.update(STEP, location.s);
    } else race.update(STEP, race.lastS);
    accumulator -= STEP;
  }
  renderer.draw(car, race, race.state === "racing" ? frameDt : 0);
  updateHUD();
  requestAnimationFrame(frame);
}
updateHUD();
requestAnimationFrame(frame);

})();
})();
